export const defaultSuffix = [
    {
        id: 1,
        name: "文档类",
        suffix: [
            ".docx",
            ".dotx",
            ".dot",
            ".doc",
            ".odt",
            ".wps",
            ".docm",
            ".dotm",
            ".xlsx",
            ".et",
            ".xlsm",
            ".xlsb",
            ".xls",
            ".xltx",
            ".xltm",
            ".xlt",
            ".xla",
            ".pptx",
            ".ppt",
            ".pot",
            ".pps",
            ".ppsx",
            ".dps",
            ".ppam",
            ".pptm",
            ".potx",
            ".potm",
            ".ppsm",
            ".ppa",
            ".pdf",
            ".txt",
            ".htm",
            ".rtf",
            ".dic",
            ".log",
            ".xml",
            ".html",
        ],
    },
    {
        id: 2,
        name: "视频/音频",
        suffix: [
            ".flv",
            ".wmv",
            ".mkv",
            ".mov",
            ".mp4",
            ".asf",
            ".mpg",
            ".rm",
            ".3gp",
            ".rmvb",
            ".mpeg",
            ".mts",
            ".m2ts",
            ".avi",
            ".wif",
            ".vob",
            ".mp3",
            ".wav",
            ".ogg",
            ".m4a",
            ".flac",
            ".ape",
            ".aac",
            ".wma",
            ".wv",
            ".mp2",
            ".ac3",
            ".mpc",
            ".mka",
            ".mpa",
            ".dts",
            ".mid",
        ],
    },
    {
        id: 3,
        name: "图片",
        suffix: [
            ".jpeg",
            ".tif",
            ".bmp",
            ".gif",
            ".png",
            ".jpg",
            ".wmf",
            ".emf",
            ".raw",
            ".ioc",
            ".tga",
            ".svg",
        ],
    },
    {
        id: 4,
        name: "压缩包",
        suffix: [
            ".zip",
            ".rar",
            ".tgz",
            ".tar",
            ".cab",
            ".uue",
            ".jar",
            ".ace",
            ".lzh",
            ".arj",
            ".gzip",
            ".gz",
            ".gz2",
            ".bz",
            ".bz2",
            ".7z",
            ".iso",
            ".rpm",
        ],
    },
    {
        id: 5,
        name: "可疑文件",
        suffix: [
            ".exe",
            ".dll",
            ".bat",
            ".com",
            ".cmd",
            ".inf",
            ".ocx",
            ".sys",
            ".vn",
            ".vbs",
            ".vbe",
            ".vbx",
            ".vxd",
            ".js",
            ".jse",
            ".wsh",
            ".wsf",
            ".asd",
            ".cpl",
            ".crt",
            ".dbx",
            ".hlp",
            ".hta",
            ".isp",
            ".nws",
            ".ops",
            ".pcd",
            ".pi",
            ".prf",
            ".reg",
            ".scf",
            ".scr",
            ".sct",
            ".uue",
            ".wab",
            ".wsc",
            ".rtf",
            ".pas",
            ".mp8",
            ".tbb",
            ".sht",
            ".mbx",
            ".eml",
            ".pmr",
            ".fpt",
            ".inb",
            ".adb",
            ".cfg",
            ".cgi",
            ".dhtm",
            ".mmf",
            ".mht",
            ".nch",
            ".ods",
            ".oft",
            ".pl",
            ".shtm",
            ".stm",
            ".uin",
        ],
    },
    {
        id: 6,
        name: "病毒文件",
        suffix: [
            ".onion",
            ".wallet",
            ".wmcry",
            ".WNCRY",
            ".b01e",
            ".locky",
            ".Cerber3",
            ".CHAK",
            ".GOTHAM",
            ".YAYA",
            ".GRANNY",
            ".SKUNK",
            ".TRUE",
            ".SEXY",
            ".MAKGR",
            ".BIG1",
            ".LIN",
            ".BIIT",
            ".THIRD",
            ".DREAM",
            ".freeman",
            ".BUNNY",
        ],
    },
    {
        id: 7,
        name: "其它",
        suffix: [],
    },
];

/**
 * 文件类型
 */
export enum FileCategory {
    /**
     * 文档类
     */
    Document = 1,

    /**
     * 媒体类
     */
    VideoAudio = 2,

    /**
     * 图片
     */
    Image = 3,

    /**
     * 压缩包
     */
    Archive = 4,

    /**
     * 可疑文件
     */
    SuspiciousFile = 5,

    /**
     * 病毒文件
     */
    VirusFile = 6,

    /**
     * 其他
     */
    Others = 7,
}
