// tslint:disable
/**
 * 内容自动化
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExecutorActionOutputDto
 */
export interface ExecutorActionOutputDto {
    key: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutorActionOutputDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutorActionOutputDto
     */
    type: ExecutorActionOutputDtoTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ExecutorActionOutputDtoTypeEnum {
    String = 'string',
    Number = 'number',
    Datetime = 'datetime',
    AsFile = 'asFile',
    AsFolder = 'asFolder',
    MultipleFiles = 'multipleFiles'
}



