// Code generated by MockGen. DO NOT EDIT.
// Source: oauth2_client.go

// Package mock_httpclient is a generated GoMock package.
package mock_httpclient

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOAuth2Client is a mock of OAuth2Client interface.
type MockOAuth2Client struct {
	ctrl     *gomock.Controller
	recorder *MockOAuth2ClientMockRecorder
}

// MockOAuth2ClientMockRecorder is the mock recorder for MockOAuth2Client.
type MockOAuth2ClientMockRecorder struct {
	mock *MockOAuth2Client
}

// NewMockOAuth2Client creates a new mock instance.
func NewMockOAuth2Client(ctrl *gomock.Controller) *MockOAuth2Client {
	mock := &MockOAuth2Client{ctrl: ctrl}
	mock.recorder = &MockOAuth2ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuth2Client) EXPECT() *MockOAuth2ClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockOAuth2Client) Get(url string, headers map[string]string) (int, interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", url, headers)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockOAuth2ClientMockRecorder) Get(url, headers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOAuth2Client)(nil).Get), url, headers)
}

// Request mocks base method.
func (m *MockOAuth2Client) Request(url, method string, headers map[string]string, reqParam *[]byte) (int, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", url, method, headers, reqParam)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Request indicates an expected call of Request.
func (mr *MockOAuth2ClientMockRecorder) Request(url, method, headers, reqParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockOAuth2Client)(nil).Request), url, method, headers, reqParam)
}
