// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/mq_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMQAccess is a mock of MQAccess interface.
type MockMQAccess struct {
	ctrl     *gomock.Controller
	recorder *MockMQAccessMockRecorder
}

// MockMQAccessMockRecorder is the mock recorder for MockMQAccess.
type MockMQAccessMockRecorder struct {
	mock *MockMQAccess
}

// NewMockMQAccess creates a new mock instance.
func NewMockMQAccess(ctrl *gomock.Controller) *MockMQAccess {
	mock := &MockMQAccess{ctrl: ctrl}
	mock.recorder = &MockMQAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMQAccess) EXPECT() *MockMQAccessMockRecorder {
	return m.recorder
}

// CreateTopicsOrPartitions mocks base method.
func (m *MockMQAccess) CreateTopicsOrPartitions(ctx context.Context, topicNames []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopicsOrPartitions", ctx, topicNames)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTopicsOrPartitions indicates an expected call of CreateTopicsOrPartitions.
func (mr *MockMQAccessMockRecorder) CreateTopicsOrPartitions(ctx, topicNames interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopicsOrPartitions", reflect.TypeOf((*MockMQAccess)(nil).CreateTopicsOrPartitions), ctx, topicNames)
}

// DeleteTopics mocks base method.
func (m *MockMQAccess) DeleteTopics(ctx context.Context, topicNames []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTopics", ctx, topicNames)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTopics indicates an expected call of DeleteTopics.
func (mr *MockMQAccessMockRecorder) DeleteTopics(ctx, topicNames interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTopics", reflect.TypeOf((*MockMQAccess)(nil).DeleteTopics), ctx, topicNames)
}
