// Code generated by MockGen. DO NOT EDIT.
// Source: ../management/storage.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockManagementService is a mock of ManagementService interface.
type MockManagementService struct {
	ctrl     *gomock.Controller
	recorder *MockManagementServiceMockRecorder
}

// MockManagementServiceMockRecorder is the mock recorder for MockManagementService.
type MockManagementServiceMockRecorder struct {
	mock *MockManagementService
}

// NewMockManagementService creates a new mock instance.
func NewMockManagementService(ctrl *gomock.Controller) *MockManagementService {
	mock := &MockManagementService{ctrl: ctrl}
	mock.recorder = &MockManagementServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManagementService) EXPECT() *MockManagementServiceMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockManagementService) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockManagementServiceMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockManagementService)(nil).Start))
}

// Stop mocks base method.
func (m *MockManagementService) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockManagementServiceMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockManagementService)(nil).Stop))
}
