// Code generated by MockGen. DO NOT EDIT.
// Source: ./pipeline_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "flow-stream-data-pipeline/pipeline-mgmt/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPipelineMgmtAccess is a mock of PipelineMgmtAccess interface.
type MockPipelineMgmtAccess struct {
	ctrl     *gomock.Controller
	recorder *MockPipelineMgmtAccessMockRecorder
}

// MockPipelineMgmtAccessMockRecorder is the mock recorder for MockPipelineMgmtAccess.
type MockPipelineMgmtAccessMockRecorder struct {
	mock *MockPipelineMgmtAccess
}

// NewMockPipelineMgmtAccess creates a new mock instance.
func NewMockPipelineMgmtAccess(ctrl *gomock.Controller) *MockPipelineMgmtAccess {
	mock := &MockPipelineMgmtAccess{ctrl: ctrl}
	mock.recorder = &MockPipelineMgmtAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPipelineMgmtAccess) EXPECT() *MockPipelineMgmtAccessMockRecorder {
	return m.recorder
}

// CheckPipelineExistByID mocks base method.
func (m *MockPipelineMgmtAccess) CheckPipelineExistByID(ctx context.Context, ID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPipelineExistByID", ctx, ID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckPipelineExistByID indicates an expected call of CheckPipelineExistByID.
func (mr *MockPipelineMgmtAccessMockRecorder) CheckPipelineExistByID(ctx, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPipelineExistByID", reflect.TypeOf((*MockPipelineMgmtAccess)(nil).CheckPipelineExistByID), ctx, ID)
}

// CheckPipelineExistByName mocks base method.
func (m *MockPipelineMgmtAccess) CheckPipelineExistByName(ctx context.Context, name string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPipelineExistByName", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckPipelineExistByName indicates an expected call of CheckPipelineExistByName.
func (mr *MockPipelineMgmtAccessMockRecorder) CheckPipelineExistByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPipelineExistByName", reflect.TypeOf((*MockPipelineMgmtAccess)(nil).CheckPipelineExistByName), ctx, name)
}

// CreatePipeline mocks base method.
func (m *MockPipelineMgmtAccess) CreatePipeline(ctx context.Context, pipelineInfo *interfaces.Pipeline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePipeline", ctx, pipelineInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePipeline indicates an expected call of CreatePipeline.
func (mr *MockPipelineMgmtAccessMockRecorder) CreatePipeline(ctx, pipelineInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePipeline", reflect.TypeOf((*MockPipelineMgmtAccess)(nil).CreatePipeline), ctx, pipelineInfo)
}

// DeletePipeline mocks base method.
func (m *MockPipelineMgmtAccess) DeletePipeline(ctx context.Context, pipelineID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePipeline", ctx, pipelineID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePipeline indicates an expected call of DeletePipeline.
func (mr *MockPipelineMgmtAccessMockRecorder) DeletePipeline(ctx, pipelineID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePipeline", reflect.TypeOf((*MockPipelineMgmtAccess)(nil).DeletePipeline), ctx, pipelineID)
}

// GetPipeline mocks base method.
func (m *MockPipelineMgmtAccess) GetPipeline(ctx context.Context, pipelineID string) (*interfaces.Pipeline, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipeline", ctx, pipelineID)
	ret0, _ := ret[0].(*interfaces.Pipeline)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPipeline indicates an expected call of GetPipeline.
func (mr *MockPipelineMgmtAccessMockRecorder) GetPipeline(ctx, pipelineID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipeline", reflect.TypeOf((*MockPipelineMgmtAccess)(nil).GetPipeline), ctx, pipelineID)
}

// GetPipelinesTotal mocks base method.
func (m *MockPipelineMgmtAccess) GetPipelinesTotal(ctx context.Context, pipelineQuery *interfaces.ListPipelinesQuery) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelinesTotal", ctx, pipelineQuery)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelinesTotal indicates an expected call of GetPipelinesTotal.
func (mr *MockPipelineMgmtAccessMockRecorder) GetPipelinesTotal(ctx, pipelineQuery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelinesTotal", reflect.TypeOf((*MockPipelineMgmtAccess)(nil).GetPipelinesTotal), ctx, pipelineQuery)
}

// ListPipelines mocks base method.
func (m *MockPipelineMgmtAccess) ListPipelines(ctx context.Context, pipelineQuery *interfaces.ListPipelinesQuery) ([]*interfaces.Pipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPipelines", ctx, pipelineQuery)
	ret0, _ := ret[0].([]*interfaces.Pipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPipelines indicates an expected call of ListPipelines.
func (mr *MockPipelineMgmtAccessMockRecorder) ListPipelines(ctx, pipelineQuery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPipelines", reflect.TypeOf((*MockPipelineMgmtAccess)(nil).ListPipelines), ctx, pipelineQuery)
}

// UpdatePipeline mocks base method.
func (m *MockPipelineMgmtAccess) UpdatePipeline(ctx context.Context, pipelineInfo *interfaces.Pipeline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePipeline", ctx, pipelineInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePipeline indicates an expected call of UpdatePipeline.
func (mr *MockPipelineMgmtAccessMockRecorder) UpdatePipeline(ctx, pipelineInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipeline", reflect.TypeOf((*MockPipelineMgmtAccess)(nil).UpdatePipeline), ctx, pipelineInfo)
}

// UpdatePipelineStatus mocks base method.
func (m *MockPipelineMgmtAccess) UpdatePipelineStatus(ctx context.Context, pipelineInfo *interfaces.Pipeline, isInnerRequest bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePipelineStatus", ctx, pipelineInfo, isInnerRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePipelineStatus indicates an expected call of UpdatePipelineStatus.
func (mr *MockPipelineMgmtAccessMockRecorder) UpdatePipelineStatus(ctx, pipelineInfo, isInnerRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipelineStatus", reflect.TypeOf((*MockPipelineMgmtAccess)(nil).UpdatePipelineStatus), ctx, pipelineInfo, isInnerRequest)
}
