// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/pipeline_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "flow-stream-data-pipeline/pipeline-mgmt/interfaces"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockPipelineMgmtService is a mock of PipelineMgmtService interface.
type MockPipelineMgmtService struct {
	ctrl     *gomock.Controller
	recorder *MockPipelineMgmtServiceMockRecorder
}

// MockPipelineMgmtServiceMockRecorder is the mock recorder for MockPipelineMgmtService.
type MockPipelineMgmtServiceMockRecorder struct {
	mock *MockPipelineMgmtService
}

// NewMockPipelineMgmtService creates a new mock instance.
func NewMockPipelineMgmtService(ctrl *gomock.Controller) *MockPipelineMgmtService {
	mock := &MockPipelineMgmtService{ctrl: ctrl}
	mock.recorder = &MockPipelineMgmtServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPipelineMgmtService) EXPECT() *MockPipelineMgmtServiceMockRecorder {
	return m.recorder
}

// CheckPipelineExistByID mocks base method.
func (m *MockPipelineMgmtService) CheckPipelineExistByID(ctx context.Context, ID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPipelineExistByID", ctx, ID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckPipelineExistByID indicates an expected call of CheckPipelineExistByID.
func (mr *MockPipelineMgmtServiceMockRecorder) CheckPipelineExistByID(ctx, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPipelineExistByID", reflect.TypeOf((*MockPipelineMgmtService)(nil).CheckPipelineExistByID), ctx, ID)
}

// CheckPipelineExistByName mocks base method.
func (m *MockPipelineMgmtService) CheckPipelineExistByName(ctx context.Context, name string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPipelineExistByName", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckPipelineExistByName indicates an expected call of CheckPipelineExistByName.
func (mr *MockPipelineMgmtServiceMockRecorder) CheckPipelineExistByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPipelineExistByName", reflect.TypeOf((*MockPipelineMgmtService)(nil).CheckPipelineExistByName), ctx, name)
}

// CreatePipeline mocks base method.
func (m *MockPipelineMgmtService) CreatePipeline(ctx context.Context, pipelineInfo *interfaces.Pipeline) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePipeline", ctx, pipelineInfo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePipeline indicates an expected call of CreatePipeline.
func (mr *MockPipelineMgmtServiceMockRecorder) CreatePipeline(ctx, pipelineInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePipeline", reflect.TypeOf((*MockPipelineMgmtService)(nil).CreatePipeline), ctx, pipelineInfo)
}

// DeletePipeline mocks base method.
func (m *MockPipelineMgmtService) DeletePipeline(ctx context.Context, pipelineID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePipeline", ctx, pipelineID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePipeline indicates an expected call of DeletePipeline.
func (mr *MockPipelineMgmtServiceMockRecorder) DeletePipeline(ctx, pipelineID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePipeline", reflect.TypeOf((*MockPipelineMgmtService)(nil).DeletePipeline), ctx, pipelineID)
}

// GetPipeline mocks base method.
func (m *MockPipelineMgmtService) GetPipeline(ctx context.Context, pipelineID string, isListen bool) (*interfaces.Pipeline, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipeline", ctx, pipelineID, isListen)
	ret0, _ := ret[0].(*interfaces.Pipeline)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPipeline indicates an expected call of GetPipeline.
func (mr *MockPipelineMgmtServiceMockRecorder) GetPipeline(ctx, pipelineID, isListen interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipeline", reflect.TypeOf((*MockPipelineMgmtService)(nil).GetPipeline), ctx, pipelineID, isListen)
}

// GetPipelineTotals mocks base method.
func (m *MockPipelineMgmtService) GetPipelineTotals(ctx context.Context, pipelineQuery *interfaces.ListPipelinesQuery) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelineTotals", ctx, pipelineQuery)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelineTotals indicates an expected call of GetPipelineTotals.
func (mr *MockPipelineMgmtServiceMockRecorder) GetPipelineTotals(ctx, pipelineQuery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelineTotals", reflect.TypeOf((*MockPipelineMgmtService)(nil).GetPipelineTotals), ctx, pipelineQuery)
}

// ListPipelineResources mocks base method.
func (m *MockPipelineMgmtService) ListPipelineResources(ctx context.Context, param *interfaces.ListPipelinesQuery) ([]*interfaces.Resource, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPipelineResources", ctx, param)
	ret0, _ := ret[0].([]*interfaces.Resource)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPipelineResources indicates an expected call of ListPipelineResources.
func (mr *MockPipelineMgmtServiceMockRecorder) ListPipelineResources(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPipelineResources", reflect.TypeOf((*MockPipelineMgmtService)(nil).ListPipelineResources), ctx, param)
}

// ListPipelines mocks base method.
func (m *MockPipelineMgmtService) ListPipelines(ctx context.Context, pipelineQuery *interfaces.ListPipelinesQuery) ([]*interfaces.Pipeline, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPipelines", ctx, pipelineQuery)
	ret0, _ := ret[0].([]*interfaces.Pipeline)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPipelines indicates an expected call of ListPipelines.
func (mr *MockPipelineMgmtServiceMockRecorder) ListPipelines(ctx, pipelineQuery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPipelines", reflect.TypeOf((*MockPipelineMgmtService)(nil).ListPipelines), ctx, pipelineQuery)
}

// UpdatePipeline mocks base method.
func (m *MockPipelineMgmtService) UpdatePipeline(ctx context.Context, pipelineInfo *interfaces.Pipeline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePipeline", ctx, pipelineInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePipeline indicates an expected call of UpdatePipeline.
func (mr *MockPipelineMgmtServiceMockRecorder) UpdatePipeline(ctx, pipelineInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipeline", reflect.TypeOf((*MockPipelineMgmtService)(nil).UpdatePipeline), ctx, pipelineInfo)
}

// UpdatePipelineStatus mocks base method.
func (m *MockPipelineMgmtService) UpdatePipelineStatus(ctx context.Context, pipelineID string, pipelineStatusInfo *interfaces.PipelineStatusParamter, isInnerRequest bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePipelineStatus", ctx, pipelineID, pipelineStatusInfo, isInnerRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePipelineStatus indicates an expected call of UpdatePipelineStatus.
func (mr *MockPipelineMgmtServiceMockRecorder) UpdatePipelineStatus(ctx, pipelineID, pipelineStatusInfo, isInnerRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipelineStatus", reflect.TypeOf((*MockPipelineMgmtService)(nil).UpdatePipelineStatus), ctx, pipelineID, pipelineStatusInfo, isInnerRequest)
}

// WatchPipelineDeploys mocks base method.
func (m *MockPipelineMgmtService) WatchPipelineDeploys(ctx context.Context, interval time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatchPipelineDeploys", ctx, interval)
}

// WatchPipelineDeploys indicates an expected call of WatchPipelineDeploys.
func (mr *MockPipelineMgmtServiceMockRecorder) WatchPipelineDeploys(ctx, interval interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchPipelineDeploys", reflect.TypeOf((*MockPipelineMgmtService)(nil).WatchPipelineDeploys), ctx, interval)
}
