// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/opensearch_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "flow-stream-data-pipeline/pipeline-worker/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	opensearchutil "github.com/opensearch-project/opensearch-go/v2/opensearchutil"
)

// MockBulkIndexer is a mock of BulkIndexer interface.
type MockBulkIndexer struct {
	ctrl     *gomock.Controller
	recorder *MockBulkIndexerMockRecorder
}

// MockBulkIndexerMockRecorder is the mock recorder for MockBulkIndexer.
type MockBulkIndexerMockRecorder struct {
	mock *MockBulkIndexer
}

// NewMockBulkIndexer creates a new mock instance.
func NewMockBulkIndexer(ctrl *gomock.Controller) *MockBulkIndexer {
	mock := &MockBulkIndexer{ctrl: ctrl}
	mock.recorder = &MockBulkIndexerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBulkIndexer) EXPECT() *MockBulkIndexerMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBulkIndexer) Add(item *opensearchutil.BulkIndexerItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockBulkIndexerMockRecorder) Add(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBulkIndexer)(nil).Add), item)
}

// BufLen mocks base method.
func (m *MockBulkIndexer) BufLen() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BufLen")
	ret0, _ := ret[0].(int)
	return ret0
}

// BufLen indicates an expected call of BufLen.
func (mr *MockBulkIndexerMockRecorder) BufLen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BufLen", reflect.TypeOf((*MockBulkIndexer)(nil).BufLen))
}

// Flush mocks base method.
func (m *MockBulkIndexer) Flush(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Flush indicates an expected call of Flush.
func (mr *MockBulkIndexerMockRecorder) Flush(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockBulkIndexer)(nil).Flush), ctx)
}

// ItemsLen mocks base method.
func (m *MockBulkIndexer) ItemsLen() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ItemsLen")
	ret0, _ := ret[0].(int)
	return ret0
}

// ItemsLen indicates an expected call of ItemsLen.
func (mr *MockBulkIndexerMockRecorder) ItemsLen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ItemsLen", reflect.TypeOf((*MockBulkIndexer)(nil).ItemsLen))
}

// Reset mocks base method.
func (m *MockBulkIndexer) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockBulkIndexerMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockBulkIndexer)(nil).Reset))
}

// MockOpenSearchAccess is a mock of OpenSearchAccess interface.
type MockOpenSearchAccess struct {
	ctrl     *gomock.Controller
	recorder *MockOpenSearchAccessMockRecorder
}

// MockOpenSearchAccessMockRecorder is the mock recorder for MockOpenSearchAccess.
type MockOpenSearchAccessMockRecorder struct {
	mock *MockOpenSearchAccess
}

// NewMockOpenSearchAccess creates a new mock instance.
func NewMockOpenSearchAccess(ctrl *gomock.Controller) *MockOpenSearchAccess {
	mock := &MockOpenSearchAccess{ctrl: ctrl}
	mock.recorder = &MockOpenSearchAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenSearchAccess) EXPECT() *MockOpenSearchAccessMockRecorder {
	return m.recorder
}

// NewBulkIndexer mocks base method.
func (m *MockOpenSearchAccess) NewBulkIndexer(flushBytes int) interfaces.BulkIndexer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewBulkIndexer", flushBytes)
	ret0, _ := ret[0].(interfaces.BulkIndexer)
	return ret0
}

// NewBulkIndexer indicates an expected call of NewBulkIndexer.
func (mr *MockOpenSearchAccessMockRecorder) NewBulkIndexer(flushBytes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewBulkIndexer", reflect.TypeOf((*MockOpenSearchAccess)(nil).NewBulkIndexer), flushBytes)
}
