// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/worker_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "flow-stream-data-pipeline/pipeline-worker/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWorkerService is a mock of WorkerService interface.
type MockWorkerService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerServiceMockRecorder
}

// MockWorkerServiceMockRecorder is the mock recorder for MockWorkerService.
type MockWorkerServiceMockRecorder struct {
	mock *MockWorkerService
}

// NewMockWorkerService creates a new mock instance.
func NewMockWorkerService(ctrl *gomock.Controller) *MockWorkerService {
	mock := &MockWorkerService{ctrl: ctrl}
	mock.recorder = &MockWorkerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerService) EXPECT() *MockWorkerServiceMockRecorder {
	return m.recorder
}

// ListenErrChan mocks base method.
func (m *MockWorkerService) ListenErrChan() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListenErrChan")
}

// ListenErrChan indicates an expected call of ListenErrChan.
func (mr *MockWorkerServiceMockRecorder) ListenErrChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenErrChan", reflect.TypeOf((*MockWorkerService)(nil).ListenErrChan))
}

// StartWorker mocks base method.
func (m *MockWorkerService) StartWorker(ctx context.Context, pipeline *interfaces.Pipeline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartWorker", ctx, pipeline)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartWorker indicates an expected call of StartWorker.
func (mr *MockWorkerServiceMockRecorder) StartWorker(ctx, pipeline interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartWorker", reflect.TypeOf((*MockWorkerService)(nil).StartWorker), ctx, pipeline)
}

// StopWorker mocks base method.
func (m *MockWorkerService) StopWorker(ctx context.Context, pipeline *interfaces.Pipeline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopWorker", ctx, pipeline)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopWorker indicates an expected call of StopWorker.
func (mr *MockWorkerServiceMockRecorder) StopWorker(ctx, pipeline interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopWorker", reflect.TypeOf((*MockWorkerService)(nil).StopWorker), ctx, pipeline)
}

// UpdateWorker mocks base method.
func (m *MockWorkerService) UpdateWorker(ctx context.Context, pipeline *interfaces.Pipeline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorker", ctx, pipeline)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorker indicates an expected call of UpdateWorker.
func (mr *MockWorkerServiceMockRecorder) UpdateWorker(ctx, pipeline interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorker", reflect.TypeOf((*MockWorkerService)(nil).UpdateWorker), ctx, pipeline)
}

// WatchWorker mocks base method.
func (m *MockWorkerService) WatchWorker(ctx context.Context, pipeline *interfaces.Pipeline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchWorker", ctx, pipeline)
	ret0, _ := ret[0].(error)
	return ret0
}

// WatchWorker indicates an expected call of WatchWorker.
func (mr *MockWorkerServiceMockRecorder) WatchWorker(ctx, pipeline interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchWorker", reflect.TypeOf((*MockWorkerService)(nil).WatchWorker), ctx, pipeline)
}
