openapi: "3.0.2"
info:
  title: "DIP算子平台应用服务私有接口协议"
  description: "DIP算子平台应用服务私有接口协议RESTful API集合,用于集群内部服务调用, 无需接口认证信息"
  version: 1.0.0
servers:
  - url: http://127.0.0.1:9000/api/agent-operator-integration/internal-v1
    description: 服务器地址
tags:
  - name: "工具"
    description: "工具操作内部接口相关接口"

paths:
  /tool-box/{box_id}/tools:
    post:
      $ref: "../paths/toolbox_private.yaml#/internal/internal-toolbox-update-tool"
    get:
      $ref: "../paths/toolbox_private.yaml#/internal/query-internal-toolbox-tool"
    delete:
      $ref: "../paths/toolbox_private.yaml#/internal/delete-internal-toolbox-tool"
