// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/job_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "data-model-job/interfaces"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockJobService is a mock of JobService interface.
type MockJobService struct {
	ctrl     *gomock.Controller
	recorder *MockJobServiceMockRecorder
}

// MockJobServiceMockRecorder is the mock recorder for MockJobService.
type MockJobServiceMockRecorder struct {
	mock *MockJobService
}

// NewMockJobService creates a new mock instance.
func NewMockJobService(ctrl *gomock.Controller) *MockJobService {
	mock := &MockJobService{ctrl: ctrl}
	mock.recorder = &MockJobServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobService) EXPECT() *MockJobServiceMockRecorder {
	return m.recorder
}

// ListenToErrChan mocks base method.
func (m *MockJobService) ListenToErrChan() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListenToErrChan")
}

// ListenToErrChan indicates an expected call of ListenToErrChan.
func (mr *MockJobServiceMockRecorder) ListenToErrChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenToErrChan", reflect.TypeOf((*MockJobService)(nil).ListenToErrChan))
}

// StartJob mocks base method.
func (m *MockJobService) StartJob(ctx context.Context, jobInfo *interfaces.JobInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartJob", ctx, jobInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartJob indicates an expected call of StartJob.
func (mr *MockJobServiceMockRecorder) StartJob(ctx, jobInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartJob", reflect.TypeOf((*MockJobService)(nil).StartJob), ctx, jobInfo)
}

// StopJob mocks base method.
func (m *MockJobService) StopJob(ctx context.Context, jobId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopJob", ctx, jobId)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopJob indicates an expected call of StopJob.
func (mr *MockJobServiceMockRecorder) StopJob(ctx, jobId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopJob", reflect.TypeOf((*MockJobService)(nil).StopJob), ctx, jobId)
}

// UpdateJob mocks base method.
func (m *MockJobService) UpdateJob(ctx context.Context, jobInfo *interfaces.JobInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJob", ctx, jobInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJob indicates an expected call of UpdateJob.
func (mr *MockJobServiceMockRecorder) UpdateJob(ctx, jobInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJob", reflect.TypeOf((*MockJobService)(nil).UpdateJob), ctx, jobInfo)
}

// WatchJob mocks base method.
func (m *MockJobService) WatchJob(interval time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatchJob", interval)
}

// WatchJob indicates an expected call of WatchJob.
func (mr *MockJobServiceMockRecorder) WatchJob(interval interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchJob", reflect.TypeOf((*MockJobService)(nil).WatchJob), interval)
}
