// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/event_model_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "data-model-job/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEventModelAccess is a mock of EventModelAccess interface.
type MockEventModelAccess struct {
	ctrl     *gomock.Controller
	recorder *MockEventModelAccessMockRecorder
}

// MockEventModelAccessMockRecorder is the mock recorder for MockEventModelAccess.
type MockEventModelAccessMockRecorder struct {
	mock *MockEventModelAccess
}

// NewMockEventModelAccess creates a new mock instance.
func NewMockEventModelAccess(ctrl *gomock.Controller) *MockEventModelAccess {
	mock := &MockEventModelAccess{ctrl: ctrl}
	mock.recorder = &MockEventModelAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventModelAccess) EXPECT() *MockEventModelAccessMockRecorder {
	return m.recorder
}

// GetEventModel mocks base method.
func (m *MockEventModelAccess) GetEventModel(ctx context.Context, modelID string) (interfaces.EventModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventModel", ctx, modelID)
	ret0, _ := ret[0].(interfaces.EventModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventModel indicates an expected call of GetEventModel.
func (mr *MockEventModelAccessMockRecorder) GetEventModel(ctx, modelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventModel", reflect.TypeOf((*MockEventModelAccess)(nil).GetEventModel), ctx, modelID)
}

// UpdateEventTaskAttributesById mocks base method.
func (m *MockEventModelAccess) UpdateEventTaskAttributesById(ctx context.Context, task interfaces.EventTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEventTaskAttributesById", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEventTaskAttributesById indicates an expected call of UpdateEventTaskAttributesById.
func (mr *MockEventModelAccessMockRecorder) UpdateEventTaskAttributesById(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEventTaskAttributesById", reflect.TypeOf((*MockEventModelAccess)(nil).UpdateEventTaskAttributesById), ctx, task)
}
