// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/metric_model_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "data-model-job/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricModelAccess is a mock of MetricModelAccess interface.
type MockMetricModelAccess struct {
	ctrl     *gomock.Controller
	recorder *MockMetricModelAccessMockRecorder
}

// MockMetricModelAccessMockRecorder is the mock recorder for MockMetricModelAccess.
type MockMetricModelAccessMockRecorder struct {
	mock *MockMetricModelAccess
}

// NewMockMetricModelAccess creates a new mock instance.
func NewMockMetricModelAccess(ctrl *gomock.Controller) *MockMetricModelAccess {
	mock := &MockMetricModelAccess{ctrl: ctrl}
	mock.recorder = &MockMetricModelAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricModelAccess) EXPECT() *MockMetricModelAccessMockRecorder {
	return m.recorder
}

// GetTaskPlanTimeById mocks base method.
func (m *MockMetricModelAccess) GetTaskPlanTimeById(ctx context.Context, taskId string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskPlanTimeById", ctx, taskId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskPlanTimeById indicates an expected call of GetTaskPlanTimeById.
func (mr *MockMetricModelAccessMockRecorder) GetTaskPlanTimeById(ctx, taskId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskPlanTimeById", reflect.TypeOf((*MockMetricModelAccess)(nil).GetTaskPlanTimeById), ctx, taskId)
}

// UpdateTaskAttributesById mocks base method.
func (m *MockMetricModelAccess) UpdateTaskAttributesById(ctx context.Context, taskId string, task interfaces.MetricTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskAttributesById", ctx, taskId, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskAttributesById indicates an expected call of UpdateTaskAttributesById.
func (mr *MockMetricModelAccessMockRecorder) UpdateTaskAttributesById(ctx, taskId, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskAttributesById", reflect.TypeOf((*MockMetricModelAccess)(nil).UpdateTaskAttributesById), ctx, taskId, task)
}
