// tslint:disable
/**
 * 个性化配置 API
 * 个性化配置 API相关文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 审核对象
 * @export
 * @interface AuditObject
 */
export interface AuditObject {
    /**
     * 审核对象ID
     * @type {string}
     * @memberof AuditObject
     */
    id: string;
    /**
     * 审核对象类型
     * @type {string}
     * @memberof AuditObject
     */
    type: AuditObjectTypeEnum;
    /**
     * 审核对象名称
     * @type {string}
     * @memberof AuditObject
     */
    name: string;
}

/**
    * @export
    * @enum {string}
    */
export enum AuditObjectTypeEnum {
    User = 'user',
    Department = 'department',
    Group = 'group'
}

/**
 * 子菜单
 * @export
 * @interface ChildMenu
 */
export interface ChildMenu {
    /**
     * 插件路径
     * @type {string}
     * @memberof ChildMenu
     */
    path: string;
    /**
     * 
     * @type {Locales}
     * @memberof ChildMenu
     */
    locales: Locales;
    /**
     * 打开方式
     * @type {string}
     * @memberof ChildMenu
     */
    openType: ChildMenuOpenTypeEnum;
    /**
     * 子菜单
     * @type {Array<ChildMenu>}
     * @memberof ChildMenu
     */
    children?: Array<ChildMenu>;
}

/**
    * @export
    * @enum {string}
    */
export enum ChildMenuOpenTypeEnum {
    Docked = 'docked',
    NewTab = 'new_tab'
}

/**
 * 接口请求体参数
 * @export
 * @interface CreateTags
 */
export interface CreateTags {
    /**
     * 仅展示一级标签,默认值false
     * @type {boolean}
     * @memberof CreateTags
     */
    show_first_level_only?: boolean;
    /**
     * 用户配置需展示的标签列表
     * @type {Array<string>}
     * @memberof CreateTags
     */
    paths: Array<string>;
}
/**
 * 
 * @export
 * @interface DUploadParam
 */
export interface DUploadParam {
    /**
     * 是否秒传
     * @type {boolean}
     * @memberof DUploadParam
     */
    dupload: boolean;
    /**
     * 文件gns路径（创建协议返回）
     * @type {string}
     * @memberof DUploadParam
     */
    docid: string;
    /**
     * 整个文件的长度
     * @type {number}
     * @memberof DUploadParam
     */
    length: number;
    /**
     * 文件的md5值
     * @type {string}
     * @memberof DUploadParam
     */
    md5: string;
    /**
     * 文件的CRC32校验码，如果为空文件或者非秒传, 此字段为空
     * @type {string}
     * @memberof DUploadParam
     */
    crc32: string;
    /**
     * 文件名
     * @type {string}
     * @memberof DUploadParam
     */
    name: string;
    /**
     * 53C3FEEC9284156D47604F67945F490
     * @type {string}
     * @memberof DUploadParam
     */
    rev: string;
}
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 审核记录id
     * @type {string}
     * @memberof InlineResponse200
     */
    id?: string;
    /**
     * 审核流程id
     * @type {string}
     * @memberof InlineResponse200
     */
    workflowid?: string;
    /**
     * 待审核文件的状态, 1表示审核中，-1表示表密中, 0表示审核通过
     * @type {number}
     * @memberof InlineResponse200
     */
    status?: number;
}
/**
 * 
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     * 是否符合秒传，如果符合秒传就不用发送authrequest包含的post上传文件请求
     * @type {boolean}
     * @memberof InlineResponse2001
     */
    dupload?: boolean;
    /**
     * - authrequest[0]：请求方法  - authrequest[1]: 待上传的资源URL  - authrequest[2]及以后项：请求头，格式为“key: value”；若请求时reqmethod的值为“POST”，则为POST表单域的项，格式为“key: value”  
     * @type {Array<string>}
     * @memberof InlineResponse2001
     */
    authrequest?: Array<string>;
    /**
     * 文件的gns路径
     * @type {string}
     * @memberof InlineResponse2001
     */
    docid?: string;
    /**
     * 文件名称，UTF8编码，创建版本时返回
     * @type {string}
     * @memberof InlineResponse2001
     */
    name?: string;
    /**
     * 文件版本号
     * @type {string}
     * @memberof InlineResponse2001
     */
    rev?: string;
}
/**
 * 
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     * 审核记录id
     * @type {string}
     * @memberof InlineResponse2002
     */
    id?: string;
    /**
     * 审核流程id
     * @type {string}
     * @memberof InlineResponse2002
     */
    workflowid?: string;
    /**
     * 待审核文件的状态, 1表示审核中，2表示表密中
     * @type {number}
     * @memberof InlineResponse2002
     */
    status?: number;
}
/**
 * 插件加载时显示名称的多语言资源
 * @export
 * @interface Locales
 */
export interface Locales {
    /**
     * 资源语言中文
     * @type {string}
     * @memberof Locales
     */
    zh_cn?: string;
    /**
     * 资源语言英文
     * @type {string}
     * @memberof Locales
     */
    en_us?: string;
    /**
     * 资源语言繁体
     * @type {string}
     * @memberof Locales
     */
    zh_tw?: string;
}
/**
 * 配置详情
 * @export
 * @interface MenuInfo
 */
export interface MenuInfo {
    /**
     * 插件id,其中我的门户和文档中心id为固定值  - 我的门户: const_230411xext1el5vgj6aku5h  - 文档中心: const_230411xext1ej4sur94lbmt
     * @type {string}
     * @memberof MenuInfo
     */
    functionid: string;
    /**
     * 打开方式
     * @type {string}
     * @memberof MenuInfo
     */
    openType: MenuInfoOpenTypeEnum;
    /**
     * 子菜单
     * @type {Array<ChildMenu>}
     * @memberof MenuInfo
     */
    children?: Array<ChildMenu>;
}

/**
    * @export
    * @enum {string}
    */
export enum MenuInfoOpenTypeEnum {
    Docked = 'docked',
    NewTab = 'new_tab'
}

/**
 * 导航栏插件列表
 * @export
 * @interface MenuList
 */
export interface MenuList {
    /**
     * 仅支持内置应用(inner)使用，用于支持定制化需求,third、hosting不要求
     * @type {string}
     * @memberof MenuList
     */
    buildinkey?: string;
    /**
     * 扩展的名称，标识当前功能，方便应用间的跳转；全局的command不允许重复
     * @type {string}
     * @memberof MenuList
     */
    command?: string;
    /**
     *   子功能id，其中我的门户和文档中心id为固定值  - 我的门户: const_230411xext1el5vgj6aku5h  - 文档中心: const_230411xext1ej4sur94lbmt
     * @type {string}
     * @memberof MenuList
     */
    functionid?: string;
    /**
     * 子功能加载入口
     * @type {string}
     * @memberof MenuList
     */
    entry?: string;
    /**
     * 子功能显示图标，可以是文件名称也可以是文件相对网站根目录的访问路径
     * @type {string}
     * @memberof MenuList
     */
    icon?: string;
    /**
     * 
     * @type {Locales}
     * @memberof MenuList
     */
    locales?: Locales;
    /**
     * 小程序支持的平台，可选 browser, electron,可多选
     * @type {Array<string>}
     * @memberof MenuList
     */
    platforms?: Array<string>;
    /**
     * 小程序id
     * @type {string}
     * @memberof MenuList
     */
    provider?: string;
    /**
     * 插件路由
     * @type {string}
     * @memberof MenuList
     */
    route?: string;
    /**
     * 该扩展应用的首页
     * @type {string}
     * @memberof MenuList
     */
    homepage?: string;
    /**
     * 程序的加载位置  - frame：支持 taskbar, applist, contextmenu,openmethod&fullscreen,none&fullscreen
     * @type {Array<string>}
     * @memberof MenuList
     */
    renderTo?: Array<string>;
    /**
     * 小程序渲染类型
     * @type {string}
     * @memberof MenuList
     */
    renderType?: string;
    /**
     * 程序代码的ECMAScript版本，可选值为es5,es6,es2016
     * @type {string}
     * @memberof MenuList
     */
    ECMAScriptVersion?: string;
    /**
     * 加载的代码导出的库名称
     * @type {string}
     * @memberof MenuList
     */
    libraryName?: string;
    /**
     * 打开方式
     * @type {string}
     * @memberof MenuList
     */
    openType?: MenuListOpenTypeEnum;
    /**
     * 子菜单
     * @type {Array<ChildMenu>}
     * @memberof MenuList
     */
    children?: Array<ChildMenu>;
}

/**
    * @export
    * @enum {string}
    */
export enum MenuListOpenTypeEnum {
    Docked = 'docked',
    NewTab = 'new_tab'
}

/**
 * 接口调用错误信息结构基类
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 错误码
     * @type {number}
     * @memberof ModelError
     */
    code: number;
    /**
     * 错误描述
     * @type {string}
     * @memberof ModelError
     */
    message?: string;
    /**
     * 错误处理
     * @type {string}
     * @memberof ModelError
     */
    cause?: string;
    /**
     * 错误细节
     * @type {object}
     * @memberof ModelError
     */
    detail?: object;
}
/**
 * 操作策略配置
 * @export
 * @interface OperationAuditCfg
 */
export interface OperationAuditCfg {
    /**
     * 绑定审核流程key
     * @type {string}
     * @memberof OperationAuditCfg
     */
    proc_def_key: string;
    /**
     * 需要审核的操作  - `create` 新建  - `modify` 修改  - `delete` 删除  - `rename` 重命名
     * @type {Array<string>}
     * @memberof OperationAuditCfg
     */
    operation: Array<string>;
    /**
     * 作用范围
     * @type {Array<AuditObject>}
     * @memberof OperationAuditCfg
     */
    approval_scope: Array<AuditObject>;
}
/**
 * 
 * @export
 * @interface OperationAuditCfgAllOf
 */
export interface OperationAuditCfgAllOf {
    /**
     * 绑定审核流程key
     * @type {string}
     * @memberof OperationAuditCfgAllOf
     */
    proc_def_key?: string;
    /**
     * 需要审核的操作  - `create` 新建  - `modify` 修改  - `delete` 删除  - `rename` 重命名
     * @type {Array<string>}
     * @memberof OperationAuditCfgAllOf
     */
    operation?: Array<string>;
    /**
     * 作用范围
     * @type {Array<AuditObject>}
     * @memberof OperationAuditCfgAllOf
     */
    approval_scope?: Array<AuditObject>;
}
/**
 * 操作策略配置
 * @export
 * @interface OperationAuditCfgCommon
 */
export interface OperationAuditCfgCommon {
    /**
     * 绑定审核流程key
     * @type {string}
     * @memberof OperationAuditCfgCommon
     */
    proc_def_key?: string;
    /**
     * 需要审核的操作  - `create` 新建  - `modify` 修改  - `delete` 删除  - `rename` 重命名
     * @type {Array<string>}
     * @memberof OperationAuditCfgCommon
     */
    operation?: Array<string>;
}
/**
 * 操作策略配置
 * @export
 * @interface OperationAuditCfgResp
 */
export interface OperationAuditCfgResp extends OperationAuditCfgCommon {
    /**
     * 绑定审核流程key
     * @type {string}
     * @memberof OperationAuditCfgResp
     */
    proc_def_key?: string;
    /**
     * 需要审核的操作  - `create` 新建  - `modify` 修改  - `delete` 删除  - `rename` 重命名
     * @type {Array<string>}
     * @memberof OperationAuditCfgResp
     */
    operation?: Array<string>;
    /**
     * 作用范围
     * @type {Array<AuditObject>}
     * @memberof OperationAuditCfgResp
     */
    approval_scope: Array<AuditObject>;
}
/**
 * 
 * @export
 * @interface OperationAuditCfgRespAllOf
 */
export interface OperationAuditCfgRespAllOf {
    /**
     * 绑定审核流程key
     * @type {string}
     * @memberof OperationAuditCfgRespAllOf
     */
    proc_def_key?: string;
    /**
     * 需要审核的操作  - `create` 新建  - `modify` 修改  - `delete` 删除  - `rename` 重命名
     * @type {Array<string>}
     * @memberof OperationAuditCfgRespAllOf
     */
    operation?: Array<string>;
    /**
     * 作用范围
     * @type {Array<AuditObject>}
     * @memberof OperationAuditCfgRespAllOf
     */
    approval_scope?: Array<AuditObject>;
}
/**
 * 配置详情，用户配置不存在时，返回一个默认配置信息
 * @export
 * @interface TagConfig
 */
export interface TagConfig {
    /**
     * 记录唯一标识
     * @type {string}
     * @memberof TagConfig
     */
    id?: string;
    /**
     * 用户id
     * @type {string}
     * @memberof TagConfig
     */
    userid?: string;
    /**
     * 创建时间
     * @type {number}
     * @memberof TagConfig
     */
    created_at?: number;
    /**
     * 更新时间
     * @type {number}
     * @memberof TagConfig
     */
    updated_at?: number;
    /**
     * 仅展示一级标签,默认值false
     * @type {boolean}
     * @memberof TagConfig
     */
    show_first_level_only?: boolean;
    /**
     * 二级标签id列表
     * @type {Array<string>}
     * @memberof TagConfig
     */
    tag_ids?: Array<string>;
}
/**
 * 接口请求体参数
 * @export
 * @interface Tags
 */
export interface Tags {
    /**
     * 仅展示一级标签
     * @type {boolean}
     * @memberof Tags
     */
    show_first_level_only?: boolean;
    /**
     * 标签信息列表
     * @type {Array<TagsTags>}
     * @memberof Tags
     */
    tags?: Array<TagsTags>;
}
/**
 * 标签信息
 * @export
 * @interface TagsTags
 */
export interface TagsTags {
    /**
     * 一级标签全路径
     * @type {string}
     * @memberof TagsTags
     */
    path?: string;
    /**
     * 二级标签列表
     * @type {Array<string>}
     * @memberof TagsTags
     */
    child_paths?: Array<string>;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 获取导航栏插件列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        navigationMenuListGet(options: any = {}): RequestArgs {
            const localVarPath = `/navigation/menu-list`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("OAuth2", ["user"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 添加导航栏插件
         * @param {MenuInfo} [menuInfo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        navigationMenuPost(menuInfo?: MenuInfo, options: any = {}): RequestArgs {
            const localVarPath = `/navigation/menu`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("OAuth2", ["user"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof menuInfo !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(menuInfo !== undefined ? menuInfo : {}) : (menuInfo || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 配置导航栏插件顺序
         * @param {Array<object>} [requestBody] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        navigationMenuSortPost(requestBody?: Array<object>, options: any = {}): RequestArgs {
            const localVarPath = `/navigation/menu-sort`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("OAuth2", ["user"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof requestBody !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(requestBody !== undefined ? requestBody : {}) : (requestBody || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 文档上传审核-开始上传文件
         * @param {any} [uNKNOWNBASETYPE] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditBeginuploadPost(uNKNOWNBASETYPE?: any, options: any = {}): RequestArgs {
            const localVarPath = `/operation-audit/beginupload`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("OAuth2", ["user"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof uNKNOWNBASETYPE !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(uNKNOWNBASETYPE !== undefined ? uNKNOWNBASETYPE : {}) : (uNKNOWNBASETYPE || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 删除操作审核配置
         * @param {string} docId 文档唯一标识,gns需转义
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditConfigDocIdDelete(docId: string, options: any = {}): RequestArgs {
            // verify required parameter 'docId' is not null or undefined
            if (docId === null || docId === undefined) {
                throw new RequiredError('docId','Required parameter docId was null or undefined when calling operationAuditConfigDocIdDelete.');
            }
            const localVarPath = `/operation-audit-config/{doc_id}`
                .replace(`{${"doc_id"}}`, encodeURIComponent(String(docId)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("OAuth2", ["user"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 获取操作审核配置
         * @param {string} docId 文档唯一标识,gns需转义
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditConfigDocIdGet(docId: string, options: any = {}): RequestArgs {
            // verify required parameter 'docId' is not null or undefined
            if (docId === null || docId === undefined) {
                throw new RequiredError('docId','Required parameter docId was null or undefined when calling operationAuditConfigDocIdGet.');
            }
            const localVarPath = `/operation-audit-config/{doc_id}`
                .replace(`{${"doc_id"}}`, encodeURIComponent(String(docId)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("OAuth2", ["user"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 设置操作审核配置
         * @param {string} docId 文档唯一标识,gns需转义
         * @param {OperationAuditCfg} [operationAuditCfg] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditConfigDocIdPut(docId: string, operationAuditCfg?: OperationAuditCfg, options: any = {}): RequestArgs {
            // verify required parameter 'docId' is not null or undefined
            if (docId === null || docId === undefined) {
                throw new RequiredError('docId','Required parameter docId was null or undefined when calling operationAuditConfigDocIdPut.');
            }
            const localVarPath = `/operation-audit-config/{doc_id}`
                .replace(`{${"doc_id"}}`, encodeURIComponent(String(docId)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("OAuth2", ["user"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof operationAuditCfg !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(operationAuditCfg !== undefined ? operationAuditCfg : {}) : (operationAuditCfg || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 新建文件夹文件审核
         * @param {any} [uNKNOWNBASETYPE] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditDocCreatePost(uNKNOWNBASETYPE?: any, options: any = {}): RequestArgs {
            const localVarPath = `/operation-audit/doc-create`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("OAuth2", ["user"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof uNKNOWNBASETYPE !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(uNKNOWNBASETYPE !== undefined ? uNKNOWNBASETYPE : {}) : (uNKNOWNBASETYPE || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 重命名文件审核
         * @param {any} [uNKNOWNBASETYPE] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditDocRenamePost(uNKNOWNBASETYPE?: any, options: any = {}): RequestArgs {
            const localVarPath = `/operation-audit/doc-rename`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("OAuth2", ["user"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof uNKNOWNBASETYPE !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(uNKNOWNBASETYPE !== undefined ? uNKNOWNBASETYPE : {}) : (uNKNOWNBASETYPE || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 文档上传审核-结束上传文件
         * @param {any} [uNKNOWNBASETYPE] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditEnduploadPost(uNKNOWNBASETYPE?: any, options: any = {}): RequestArgs {
            const localVarPath = `/operation-audit/endupload`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("OAuth2", ["user"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof uNKNOWNBASETYPE !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(uNKNOWNBASETYPE !== undefined ? uNKNOWNBASETYPE : {}) : (uNKNOWNBASETYPE || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 查询审核操作的详细信息
         * @param {string} id 审核操作的id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditItemsIdGet(id: string, options: any = {}): RequestArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling operationAuditItemsIdGet.');
            }
            const localVarPath = `/operation-audit/items/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("OAuth2", ["user"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 获取用户个性化配置详情
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagConfigGet(options: any = {}): RequestArgs {
            const localVarPath = `/tag-config`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("OAuth2", ["user"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 创建个性化标签
         * @param {CreateTags} [createTags] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagPost(createTags?: CreateTags, options: any = {}): RequestArgs {
            const localVarPath = `/tag`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("OAuth2", ["user"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof createTags !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(createTags !== undefined ? createTags : {}) : (createTags || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 获取用户个性化标签
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagsGet(options: any = {}): RequestArgs {
            const localVarPath = `/tags`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2 required
            // oauth required
            if (configuration && configuration.accessToken) {
                const localVarAccessTokenValue = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken("OAuth2", ["user"])
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 获取导航栏插件列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        navigationMenuListGet(options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MenuList>> {
            const localVarAxiosArgs = DefaultApiAxiosParamCreator(configuration).navigationMenuListGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 添加导航栏插件
         * @param {MenuInfo} [menuInfo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        navigationMenuPost(menuInfo?: MenuInfo, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void> {
            const localVarAxiosArgs = DefaultApiAxiosParamCreator(configuration).navigationMenuPost(menuInfo, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 配置导航栏插件顺序
         * @param {Array<object>} [requestBody] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        navigationMenuSortPost(requestBody?: Array<object>, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void> {
            const localVarAxiosArgs = DefaultApiAxiosParamCreator(configuration).navigationMenuSortPost(requestBody, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 文档上传审核-开始上传文件
         * @param {any} [uNKNOWNBASETYPE] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditBeginuploadPost(uNKNOWNBASETYPE?: any, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2001> {
            const localVarAxiosArgs = DefaultApiAxiosParamCreator(configuration).operationAuditBeginuploadPost(uNKNOWNBASETYPE, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 删除操作审核配置
         * @param {string} docId 文档唯一标识,gns需转义
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditConfigDocIdDelete(docId: string, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void> {
            const localVarAxiosArgs = DefaultApiAxiosParamCreator(configuration).operationAuditConfigDocIdDelete(docId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 获取操作审核配置
         * @param {string} docId 文档唯一标识,gns需转义
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditConfigDocIdGet(docId: string, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<OperationAuditCfg> {
            const localVarAxiosArgs = DefaultApiAxiosParamCreator(configuration).operationAuditConfigDocIdGet(docId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 设置操作审核配置
         * @param {string} docId 文档唯一标识,gns需转义
         * @param {OperationAuditCfg} [operationAuditCfg] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditConfigDocIdPut(docId: string, operationAuditCfg?: OperationAuditCfg, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void> {
            const localVarAxiosArgs = DefaultApiAxiosParamCreator(configuration).operationAuditConfigDocIdPut(docId, operationAuditCfg, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 新建文件夹文件审核
         * @param {any} [uNKNOWNBASETYPE] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditDocCreatePost(uNKNOWNBASETYPE?: any, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200> {
            const localVarAxiosArgs = DefaultApiAxiosParamCreator(configuration).operationAuditDocCreatePost(uNKNOWNBASETYPE, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 重命名文件审核
         * @param {any} [uNKNOWNBASETYPE] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditDocRenamePost(uNKNOWNBASETYPE?: any, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200> {
            const localVarAxiosArgs = DefaultApiAxiosParamCreator(configuration).operationAuditDocRenamePost(uNKNOWNBASETYPE, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 文档上传审核-结束上传文件
         * @param {any} [uNKNOWNBASETYPE] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditEnduploadPost(uNKNOWNBASETYPE?: any, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2002> {
            const localVarAxiosArgs = DefaultApiAxiosParamCreator(configuration).operationAuditEnduploadPost(uNKNOWNBASETYPE, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 查询审核操作的详细信息
         * @param {string} id 审核操作的id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditItemsIdGet(id: string, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200> {
            const localVarAxiosArgs = DefaultApiAxiosParamCreator(configuration).operationAuditItemsIdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 获取用户个性化配置详情
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagConfigGet(options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TagConfig> {
            const localVarAxiosArgs = DefaultApiAxiosParamCreator(configuration).tagConfigGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 创建个性化标签
         * @param {CreateTags} [createTags] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagPost(createTags?: CreateTags, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void> {
            const localVarAxiosArgs = DefaultApiAxiosParamCreator(configuration).tagPost(createTags, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 获取用户个性化标签
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagsGet(options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Tags> {
            const localVarAxiosArgs = DefaultApiAxiosParamCreator(configuration).tagsGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 获取导航栏插件列表
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        navigationMenuListGet(options?: any): AxiosPromise<Array<MenuList>> {
            return DefaultApiFp(configuration).navigationMenuListGet(options)(axios, basePath);
        },
        /**
         * 添加导航栏插件
         * @param {MenuInfo} [menuInfo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        navigationMenuPost(menuInfo?: MenuInfo, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).navigationMenuPost(menuInfo, options)(axios, basePath);
        },
        /**
         * 配置导航栏插件顺序
         * @param {Array<object>} [requestBody] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        navigationMenuSortPost(requestBody?: Array<object>, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).navigationMenuSortPost(requestBody, options)(axios, basePath);
        },
        /**
         * 文档上传审核-开始上传文件
         * @param {any} [uNKNOWNBASETYPE] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditBeginuploadPost(uNKNOWNBASETYPE?: any, options?: any): AxiosPromise<InlineResponse2001> {
            return DefaultApiFp(configuration).operationAuditBeginuploadPost(uNKNOWNBASETYPE, options)(axios, basePath);
        },
        /**
         * 删除操作审核配置
         * @param {string} docId 文档唯一标识,gns需转义
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditConfigDocIdDelete(docId: string, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).operationAuditConfigDocIdDelete(docId, options)(axios, basePath);
        },
        /**
         * 获取操作审核配置
         * @param {string} docId 文档唯一标识,gns需转义
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditConfigDocIdGet(docId: string, options?: any): AxiosPromise<OperationAuditCfg> {
            return DefaultApiFp(configuration).operationAuditConfigDocIdGet(docId, options)(axios, basePath);
        },
        /**
         * 设置操作审核配置
         * @param {string} docId 文档唯一标识,gns需转义
         * @param {OperationAuditCfg} [operationAuditCfg] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditConfigDocIdPut(docId: string, operationAuditCfg?: OperationAuditCfg, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).operationAuditConfigDocIdPut(docId, operationAuditCfg, options)(axios, basePath);
        },
        /**
         * 新建文件夹文件审核
         * @param {any} [uNKNOWNBASETYPE] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditDocCreatePost(uNKNOWNBASETYPE?: any, options?: any): AxiosPromise<InlineResponse200> {
            return DefaultApiFp(configuration).operationAuditDocCreatePost(uNKNOWNBASETYPE, options)(axios, basePath);
        },
        /**
         * 重命名文件审核
         * @param {any} [uNKNOWNBASETYPE] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditDocRenamePost(uNKNOWNBASETYPE?: any, options?: any): AxiosPromise<InlineResponse200> {
            return DefaultApiFp(configuration).operationAuditDocRenamePost(uNKNOWNBASETYPE, options)(axios, basePath);
        },
        /**
         * 文档上传审核-结束上传文件
         * @param {any} [uNKNOWNBASETYPE] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditEnduploadPost(uNKNOWNBASETYPE?: any, options?: any): AxiosPromise<InlineResponse2002> {
            return DefaultApiFp(configuration).operationAuditEnduploadPost(uNKNOWNBASETYPE, options)(axios, basePath);
        },
        /**
         * 查询审核操作的详细信息
         * @param {string} id 审核操作的id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        operationAuditItemsIdGet(id: string, options?: any): AxiosPromise<InlineResponse200> {
            return DefaultApiFp(configuration).operationAuditItemsIdGet(id, options)(axios, basePath);
        },
        /**
         * 获取用户个性化配置详情
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagConfigGet(options?: any): AxiosPromise<TagConfig> {
            return DefaultApiFp(configuration).tagConfigGet(options)(axios, basePath);
        },
        /**
         * 创建个性化标签
         * @param {CreateTags} [createTags] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagPost(createTags?: CreateTags, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).tagPost(createTags, options)(axios, basePath);
        },
        /**
         * 获取用户个性化标签
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagsGet(options?: any): AxiosPromise<Tags> {
            return DefaultApiFp(configuration).tagsGet(options)(axios, basePath);
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 获取导航栏插件列表
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public navigationMenuListGet(options?: any) {
        return DefaultApiFp(this.configuration).navigationMenuListGet(options)(this.axios, this.basePath);
    }

    /**
     * 添加导航栏插件
     * @param {MenuInfo} [menuInfo] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public navigationMenuPost(menuInfo?: MenuInfo, options?: any) {
        return DefaultApiFp(this.configuration).navigationMenuPost(menuInfo, options)(this.axios, this.basePath);
    }

    /**
     * 配置导航栏插件顺序
     * @param {Array<object>} [requestBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public navigationMenuSortPost(requestBody?: Array<object>, options?: any) {
        return DefaultApiFp(this.configuration).navigationMenuSortPost(requestBody, options)(this.axios, this.basePath);
    }

    /**
     * 文档上传审核-开始上传文件
     * @param {any} [uNKNOWNBASETYPE] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public operationAuditBeginuploadPost(uNKNOWNBASETYPE?: any, options?: any) {
        return DefaultApiFp(this.configuration).operationAuditBeginuploadPost(uNKNOWNBASETYPE, options)(this.axios, this.basePath);
    }

    /**
     * 删除操作审核配置
     * @param {string} docId 文档唯一标识,gns需转义
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public operationAuditConfigDocIdDelete(docId: string, options?: any) {
        return DefaultApiFp(this.configuration).operationAuditConfigDocIdDelete(docId, options)(this.axios, this.basePath);
    }

    /**
     * 获取操作审核配置
     * @param {string} docId 文档唯一标识,gns需转义
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public operationAuditConfigDocIdGet(docId: string, options?: any) {
        return DefaultApiFp(this.configuration).operationAuditConfigDocIdGet(docId, options)(this.axios, this.basePath);
    }

    /**
     * 设置操作审核配置
     * @param {string} docId 文档唯一标识,gns需转义
     * @param {OperationAuditCfg} [operationAuditCfg] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public operationAuditConfigDocIdPut(docId: string, operationAuditCfg?: OperationAuditCfg, options?: any) {
        return DefaultApiFp(this.configuration).operationAuditConfigDocIdPut(docId, operationAuditCfg, options)(this.axios, this.basePath);
    }

    /**
     * 新建文件夹文件审核
     * @param {any} [uNKNOWNBASETYPE] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public operationAuditDocCreatePost(uNKNOWNBASETYPE?: any, options?: any) {
        return DefaultApiFp(this.configuration).operationAuditDocCreatePost(uNKNOWNBASETYPE, options)(this.axios, this.basePath);
    }

    /**
     * 重命名文件审核
     * @param {any} [uNKNOWNBASETYPE] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public operationAuditDocRenamePost(uNKNOWNBASETYPE?: any, options?: any) {
        return DefaultApiFp(this.configuration).operationAuditDocRenamePost(uNKNOWNBASETYPE, options)(this.axios, this.basePath);
    }

    /**
     * 文档上传审核-结束上传文件
     * @param {any} [uNKNOWNBASETYPE] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public operationAuditEnduploadPost(uNKNOWNBASETYPE?: any, options?: any) {
        return DefaultApiFp(this.configuration).operationAuditEnduploadPost(uNKNOWNBASETYPE, options)(this.axios, this.basePath);
    }

    /**
     * 查询审核操作的详细信息
     * @param {string} id 审核操作的id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public operationAuditItemsIdGet(id: string, options?: any) {
        return DefaultApiFp(this.configuration).operationAuditItemsIdGet(id, options)(this.axios, this.basePath);
    }

    /**
     * 获取用户个性化配置详情
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public tagConfigGet(options?: any) {
        return DefaultApiFp(this.configuration).tagConfigGet(options)(this.axios, this.basePath);
    }

    /**
     * 创建个性化标签
     * @param {CreateTags} [createTags] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public tagPost(createTags?: CreateTags, options?: any) {
        return DefaultApiFp(this.configuration).tagPost(createTags, options)(this.axios, this.basePath);
    }

    /**
     * 获取用户个性化标签
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public tagsGet(options?: any) {
        return DefaultApiFp(this.configuration).tagsGet(options)(this.axios, this.basePath);
    }

}


