// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/data_connection_processor.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "data-model/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataConnectionProcessor is a mock of DataConnectionProcessor interface.
type MockDataConnectionProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockDataConnectionProcessorMockRecorder
}

// MockDataConnectionProcessorMockRecorder is the mock recorder for MockDataConnectionProcessor.
type MockDataConnectionProcessorMockRecorder struct {
	mock *MockDataConnectionProcessor
}

// NewMockDataConnectionProcessor creates a new mock instance.
func NewMockDataConnectionProcessor(ctrl *gomock.Controller) *MockDataConnectionProcessor {
	mock := &MockDataConnectionProcessor{ctrl: ctrl}
	mock.recorder = &MockDataConnectionProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataConnectionProcessor) EXPECT() *MockDataConnectionProcessorMockRecorder {
	return m.recorder
}

// ComputeConfigMD5 mocks base method.
func (m *MockDataConnectionProcessor) ComputeConfigMD5(ctx context.Context, conn *interfaces.DataConnection) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputeConfigMD5", ctx, conn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComputeConfigMD5 indicates an expected call of ComputeConfigMD5.
func (mr *MockDataConnectionProcessorMockRecorder) ComputeConfigMD5(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputeConfigMD5", reflect.TypeOf((*MockDataConnectionProcessor)(nil).ComputeConfigMD5), ctx, conn)
}

// GenerateAuthInfoAndStatus mocks base method.
func (m *MockDataConnectionProcessor) GenerateAuthInfoAndStatus(ctx context.Context, conn *interfaces.DataConnection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAuthInfoAndStatus", ctx, conn)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateAuthInfoAndStatus indicates an expected call of GenerateAuthInfoAndStatus.
func (mr *MockDataConnectionProcessorMockRecorder) GenerateAuthInfoAndStatus(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAuthInfoAndStatus", reflect.TypeOf((*MockDataConnectionProcessor)(nil).GenerateAuthInfoAndStatus), ctx, conn)
}

// HideAuthInfo mocks base method.
func (m *MockDataConnectionProcessor) HideAuthInfo(ctx context.Context, conn *interfaces.DataConnection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HideAuthInfo", ctx, conn)
	ret0, _ := ret[0].(error)
	return ret0
}

// HideAuthInfo indicates an expected call of HideAuthInfo.
func (mr *MockDataConnectionProcessorMockRecorder) HideAuthInfo(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HideAuthInfo", reflect.TypeOf((*MockDataConnectionProcessor)(nil).HideAuthInfo), ctx, conn)
}

// UpdateAuthInfoAndStatus mocks base method.
func (m *MockDataConnectionProcessor) UpdateAuthInfoAndStatus(ctx context.Context, conn *interfaces.DataConnection) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAuthInfoAndStatus", ctx, conn)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAuthInfoAndStatus indicates an expected call of UpdateAuthInfoAndStatus.
func (mr *MockDataConnectionProcessorMockRecorder) UpdateAuthInfoAndStatus(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAuthInfoAndStatus", reflect.TypeOf((*MockDataConnectionProcessor)(nil).UpdateAuthInfoAndStatus), ctx, conn)
}

// ValidateWhenCreate mocks base method.
func (m *MockDataConnectionProcessor) ValidateWhenCreate(ctx context.Context, conn *interfaces.DataConnection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateWhenCreate", ctx, conn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateWhenCreate indicates an expected call of ValidateWhenCreate.
func (mr *MockDataConnectionProcessorMockRecorder) ValidateWhenCreate(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateWhenCreate", reflect.TypeOf((*MockDataConnectionProcessor)(nil).ValidateWhenCreate), ctx, conn)
}

// ValidateWhenUpdate mocks base method.
func (m *MockDataConnectionProcessor) ValidateWhenUpdate(ctx context.Context, conn, preConn *interfaces.DataConnection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateWhenUpdate", ctx, conn, preConn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateWhenUpdate indicates an expected call of ValidateWhenUpdate.
func (mr *MockDataConnectionProcessorMockRecorder) ValidateWhenUpdate(ctx, conn, preConn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateWhenUpdate", reflect.TypeOf((*MockDataConnectionProcessor)(nil).ValidateWhenUpdate), ctx, conn, preConn)
}
