// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/trace_model_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "data-model/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTraceModelService is a mock of TraceModelService interface.
type MockTraceModelService struct {
	ctrl     *gomock.Controller
	recorder *MockTraceModelServiceMockRecorder
}

// MockTraceModelServiceMockRecorder is the mock recorder for MockTraceModelService.
type MockTraceModelServiceMockRecorder struct {
	mock *MockTraceModelService
}

// NewMockTraceModelService creates a new mock instance.
func NewMockTraceModelService(ctrl *gomock.Controller) *MockTraceModelService {
	mock := &MockTraceModelService{ctrl: ctrl}
	mock.recorder = &MockTraceModelServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTraceModelService) EXPECT() *MockTraceModelServiceMockRecorder {
	return m.recorder
}

// CreateTraceModels mocks base method.
func (m *MockTraceModelService) CreateTraceModels(ctx context.Context, models []interfaces.TraceModel) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTraceModels", ctx, models)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTraceModels indicates an expected call of CreateTraceModels.
func (mr *MockTraceModelServiceMockRecorder) CreateTraceModels(ctx, models interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTraceModels", reflect.TypeOf((*MockTraceModelService)(nil).CreateTraceModels), ctx, models)
}

// DeleteTraceModels mocks base method.
func (m *MockTraceModelService) DeleteTraceModels(ctx context.Context, modelIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTraceModels", ctx, modelIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTraceModels indicates an expected call of DeleteTraceModels.
func (mr *MockTraceModelServiceMockRecorder) DeleteTraceModels(ctx, modelIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTraceModels", reflect.TypeOf((*MockTraceModelService)(nil).DeleteTraceModels), ctx, modelIDs)
}

// GetSimpleTraceModelMapByIDs mocks base method.
func (m *MockTraceModelService) GetSimpleTraceModelMapByIDs(ctx context.Context, modelIDs []string) (map[string]interfaces.TraceModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimpleTraceModelMapByIDs", ctx, modelIDs)
	ret0, _ := ret[0].(map[string]interfaces.TraceModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimpleTraceModelMapByIDs indicates an expected call of GetSimpleTraceModelMapByIDs.
func (mr *MockTraceModelServiceMockRecorder) GetSimpleTraceModelMapByIDs(ctx, modelIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimpleTraceModelMapByIDs", reflect.TypeOf((*MockTraceModelService)(nil).GetSimpleTraceModelMapByIDs), ctx, modelIDs)
}

// GetSimpleTraceModelMapByNames mocks base method.
func (m *MockTraceModelService) GetSimpleTraceModelMapByNames(ctx context.Context, modelNames []string) (map[string]interfaces.TraceModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimpleTraceModelMapByNames", ctx, modelNames)
	ret0, _ := ret[0].(map[string]interfaces.TraceModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimpleTraceModelMapByNames indicates an expected call of GetSimpleTraceModelMapByNames.
func (mr *MockTraceModelServiceMockRecorder) GetSimpleTraceModelMapByNames(ctx, modelNames interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimpleTraceModelMapByNames", reflect.TypeOf((*MockTraceModelService)(nil).GetSimpleTraceModelMapByNames), ctx, modelNames)
}

// GetTraceModelFieldInfo mocks base method.
func (m *MockTraceModelService) GetTraceModelFieldInfo(ctx context.Context, modelID string) (interfaces.TraceModelFieldInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTraceModelFieldInfo", ctx, modelID)
	ret0, _ := ret[0].(interfaces.TraceModelFieldInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTraceModelFieldInfo indicates an expected call of GetTraceModelFieldInfo.
func (mr *MockTraceModelServiceMockRecorder) GetTraceModelFieldInfo(ctx, modelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTraceModelFieldInfo", reflect.TypeOf((*MockTraceModelService)(nil).GetTraceModelFieldInfo), ctx, modelID)
}

// GetTraceModels mocks base method.
func (m *MockTraceModelService) GetTraceModels(ctx context.Context, modelIDs []string) ([]interfaces.TraceModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTraceModels", ctx, modelIDs)
	ret0, _ := ret[0].([]interfaces.TraceModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTraceModels indicates an expected call of GetTraceModels.
func (mr *MockTraceModelServiceMockRecorder) GetTraceModels(ctx, modelIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTraceModels", reflect.TypeOf((*MockTraceModelService)(nil).GetTraceModels), ctx, modelIDs)
}

// ListTraceModelSrcs mocks base method.
func (m *MockTraceModelService) ListTraceModelSrcs(ctx context.Context, queryParams interfaces.TraceModelListQueryParams) ([]interfaces.Resource, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTraceModelSrcs", ctx, queryParams)
	ret0, _ := ret[0].([]interfaces.Resource)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTraceModelSrcs indicates an expected call of ListTraceModelSrcs.
func (mr *MockTraceModelServiceMockRecorder) ListTraceModelSrcs(ctx, queryParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTraceModelSrcs", reflect.TypeOf((*MockTraceModelService)(nil).ListTraceModelSrcs), ctx, queryParams)
}

// ListTraceModels mocks base method.
func (m *MockTraceModelService) ListTraceModels(ctx context.Context, queryParams interfaces.TraceModelListQueryParams) ([]interfaces.TraceModelListEntry, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTraceModels", ctx, queryParams)
	ret0, _ := ret[0].([]interfaces.TraceModelListEntry)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTraceModels indicates an expected call of ListTraceModels.
func (mr *MockTraceModelServiceMockRecorder) ListTraceModels(ctx, queryParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTraceModels", reflect.TypeOf((*MockTraceModelService)(nil).ListTraceModels), ctx, queryParams)
}

// SimulateCreateTraceModel mocks base method.
func (m *MockTraceModelService) SimulateCreateTraceModel(ctx context.Context, model interfaces.TraceModel) (interfaces.TraceModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SimulateCreateTraceModel", ctx, model)
	ret0, _ := ret[0].(interfaces.TraceModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SimulateCreateTraceModel indicates an expected call of SimulateCreateTraceModel.
func (mr *MockTraceModelServiceMockRecorder) SimulateCreateTraceModel(ctx, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SimulateCreateTraceModel", reflect.TypeOf((*MockTraceModelService)(nil).SimulateCreateTraceModel), ctx, model)
}

// SimulateUpdateTraceModel mocks base method.
func (m *MockTraceModelService) SimulateUpdateTraceModel(ctx context.Context, model interfaces.TraceModel) (interfaces.TraceModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SimulateUpdateTraceModel", ctx, model)
	ret0, _ := ret[0].(interfaces.TraceModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SimulateUpdateTraceModel indicates an expected call of SimulateUpdateTraceModel.
func (mr *MockTraceModelServiceMockRecorder) SimulateUpdateTraceModel(ctx, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SimulateUpdateTraceModel", reflect.TypeOf((*MockTraceModelService)(nil).SimulateUpdateTraceModel), ctx, model)
}

// UpdateTraceModel mocks base method.
func (m *MockTraceModelService) UpdateTraceModel(ctx context.Context, model interfaces.TraceModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTraceModel", ctx, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTraceModel indicates an expected call of UpdateTraceModel.
func (mr *MockTraceModelServiceMockRecorder) UpdateTraceModel(ctx, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTraceModel", reflect.TypeOf((*MockTraceModelService)(nil).UpdateTraceModel), ctx, model)
}
