// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/objective_model_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "data-model/interfaces"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockObjectiveModelAccess is a mock of ObjectiveModelAccess interface.
type MockObjectiveModelAccess struct {
	ctrl     *gomock.Controller
	recorder *MockObjectiveModelAccessMockRecorder
}

// MockObjectiveModelAccessMockRecorder is the mock recorder for MockObjectiveModelAccess.
type MockObjectiveModelAccessMockRecorder struct {
	mock *MockObjectiveModelAccess
}

// NewMockObjectiveModelAccess creates a new mock instance.
func NewMockObjectiveModelAccess(ctrl *gomock.Controller) *MockObjectiveModelAccess {
	mock := &MockObjectiveModelAccess{ctrl: ctrl}
	mock.recorder = &MockObjectiveModelAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectiveModelAccess) EXPECT() *MockObjectiveModelAccessMockRecorder {
	return m.recorder
}

// CheckObjectiveModelExistByID mocks base method.
func (m *MockObjectiveModelAccess) CheckObjectiveModelExistByID(ctx context.Context, modelID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckObjectiveModelExistByID", ctx, modelID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckObjectiveModelExistByID indicates an expected call of CheckObjectiveModelExistByID.
func (mr *MockObjectiveModelAccessMockRecorder) CheckObjectiveModelExistByID(ctx, modelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckObjectiveModelExistByID", reflect.TypeOf((*MockObjectiveModelAccess)(nil).CheckObjectiveModelExistByID), ctx, modelID)
}

// CheckObjectiveModelExistByName mocks base method.
func (m *MockObjectiveModelAccess) CheckObjectiveModelExistByName(ctx context.Context, modelName string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckObjectiveModelExistByName", ctx, modelName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckObjectiveModelExistByName indicates an expected call of CheckObjectiveModelExistByName.
func (mr *MockObjectiveModelAccessMockRecorder) CheckObjectiveModelExistByName(ctx, modelName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckObjectiveModelExistByName", reflect.TypeOf((*MockObjectiveModelAccess)(nil).CheckObjectiveModelExistByName), ctx, modelName)
}

// CreateObjectiveModel mocks base method.
func (m *MockObjectiveModelAccess) CreateObjectiveModel(ctx context.Context, tx *sql.Tx, objectiveModel interfaces.ObjectiveModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObjectiveModel", ctx, tx, objectiveModel)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateObjectiveModel indicates an expected call of CreateObjectiveModel.
func (mr *MockObjectiveModelAccessMockRecorder) CreateObjectiveModel(ctx, tx, objectiveModel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObjectiveModel", reflect.TypeOf((*MockObjectiveModelAccess)(nil).CreateObjectiveModel), ctx, tx, objectiveModel)
}

// DeleteObjectiveModels mocks base method.
func (m *MockObjectiveModelAccess) DeleteObjectiveModels(ctx context.Context, tx *sql.Tx, modelIDs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectiveModels", ctx, tx, modelIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObjectiveModels indicates an expected call of DeleteObjectiveModels.
func (mr *MockObjectiveModelAccessMockRecorder) DeleteObjectiveModels(ctx, tx, modelIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectiveModels", reflect.TypeOf((*MockObjectiveModelAccess)(nil).DeleteObjectiveModels), ctx, tx, modelIDs)
}

// GetObjectiveModelsByModelIDs mocks base method.
func (m *MockObjectiveModelAccess) GetObjectiveModelsByModelIDs(ctx context.Context, modelIDs []string) ([]interfaces.ObjectiveModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectiveModelsByModelIDs", ctx, modelIDs)
	ret0, _ := ret[0].([]interfaces.ObjectiveModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectiveModelsByModelIDs indicates an expected call of GetObjectiveModelsByModelIDs.
func (mr *MockObjectiveModelAccessMockRecorder) GetObjectiveModelsByModelIDs(ctx, modelIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectiveModelsByModelIDs", reflect.TypeOf((*MockObjectiveModelAccess)(nil).GetObjectiveModelsByModelIDs), ctx, modelIDs)
}

// GetObjectiveModelsTotal mocks base method.
func (m *MockObjectiveModelAccess) GetObjectiveModelsTotal(ctx context.Context, modelsQuery interfaces.ObjectiveModelsQueryParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectiveModelsTotal", ctx, modelsQuery)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectiveModelsTotal indicates an expected call of GetObjectiveModelsTotal.
func (mr *MockObjectiveModelAccessMockRecorder) GetObjectiveModelsTotal(ctx, modelsQuery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectiveModelsTotal", reflect.TypeOf((*MockObjectiveModelAccess)(nil).GetObjectiveModelsTotal), ctx, modelsQuery)
}

// ListObjectiveModels mocks base method.
func (m *MockObjectiveModelAccess) ListObjectiveModels(ctx context.Context, modelsQuery interfaces.ObjectiveModelsQueryParams) ([]interfaces.ObjectiveModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectiveModels", ctx, modelsQuery)
	ret0, _ := ret[0].([]interfaces.ObjectiveModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectiveModels indicates an expected call of ListObjectiveModels.
func (mr *MockObjectiveModelAccessMockRecorder) ListObjectiveModels(ctx, modelsQuery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectiveModels", reflect.TypeOf((*MockObjectiveModelAccess)(nil).ListObjectiveModels), ctx, modelsQuery)
}

// UpdateObjectiveModel mocks base method.
func (m *MockObjectiveModelAccess) UpdateObjectiveModel(ctx context.Context, tx *sql.Tx, objectiveModel interfaces.ObjectiveModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateObjectiveModel", ctx, tx, objectiveModel)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateObjectiveModel indicates an expected call of UpdateObjectiveModel.
func (mr *MockObjectiveModelAccessMockRecorder) UpdateObjectiveModel(ctx, tx, objectiveModel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateObjectiveModel", reflect.TypeOf((*MockObjectiveModelAccess)(nil).UpdateObjectiveModel), ctx, tx, objectiveModel)
}
