// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/data_dict_item_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "data-model/interfaces"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataDictItemAccess is a mock of DataDictItemAccess interface.
type MockDataDictItemAccess struct {
	ctrl     *gomock.Controller
	recorder *MockDataDictItemAccessMockRecorder
}

// MockDataDictItemAccessMockRecorder is the mock recorder for MockDataDictItemAccess.
type MockDataDictItemAccessMockRecorder struct {
	mock *MockDataDictItemAccess
}

// NewMockDataDictItemAccess creates a new mock instance.
func NewMockDataDictItemAccess(ctrl *gomock.Controller) *MockDataDictItemAccess {
	mock := &MockDataDictItemAccess{ctrl: ctrl}
	mock.recorder = &MockDataDictItemAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataDictItemAccess) EXPECT() *MockDataDictItemAccessMockRecorder {
	return m.recorder
}

// AddDimensionColumn mocks base method.
func (m *MockDataDictItemAccess) AddDimensionColumn(ctx context.Context, dictStore string, new interfaces.DimensionItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDimensionColumn", ctx, dictStore, new)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDimensionColumn indicates an expected call of AddDimensionColumn.
func (mr *MockDataDictItemAccessMockRecorder) AddDimensionColumn(ctx, dictStore, new interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDimensionColumn", reflect.TypeOf((*MockDataDictItemAccess)(nil).AddDimensionColumn), ctx, dictStore, new)
}

// CountDictItemByKey mocks base method.
func (m *MockDataDictItemAccess) CountDictItemByKey(ctx context.Context, dictID, dictStore string, keys []interfaces.DimensionItem) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDictItemByKey", ctx, dictID, dictStore, keys)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDictItemByKey indicates an expected call of CountDictItemByKey.
func (mr *MockDataDictItemAccessMockRecorder) CountDictItemByKey(ctx, dictID, dictStore, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDictItemByKey", reflect.TypeOf((*MockDataDictItemAccess)(nil).CountDictItemByKey), ctx, dictID, dictStore, keys)
}

// CreateDataDictItem mocks base method.
func (m *MockDataDictItemAccess) CreateDataDictItem(ctx context.Context, dictID, itemID, dictStore string, dimension interfaces.Dimension) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDataDictItem", ctx, dictID, itemID, dictStore, dimension)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDataDictItem indicates an expected call of CreateDataDictItem.
func (mr *MockDataDictItemAccessMockRecorder) CreateDataDictItem(ctx, dictID, itemID, dictStore, dimension interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDataDictItem", reflect.TypeOf((*MockDataDictItemAccess)(nil).CreateDataDictItem), ctx, dictID, itemID, dictStore, dimension)
}

// CreateDimensionDictItems mocks base method.
func (m *MockDataDictItemAccess) CreateDimensionDictItems(ctx context.Context, tx *sql.Tx, dictID, dictStore string, dimension []interfaces.Dimension) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDimensionDictItems", ctx, tx, dictID, dictStore, dimension)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDimensionDictItems indicates an expected call of CreateDimensionDictItems.
func (mr *MockDataDictItemAccessMockRecorder) CreateDimensionDictItems(ctx, tx, dictID, dictStore, dimension interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDimensionDictItems", reflect.TypeOf((*MockDataDictItemAccess)(nil).CreateDimensionDictItems), ctx, tx, dictID, dictStore, dimension)
}

// CreateKVDictItems mocks base method.
func (m *MockDataDictItemAccess) CreateKVDictItems(ctx context.Context, tx *sql.Tx, dictID string, items []interfaces.KvDictItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKVDictItems", ctx, tx, dictID, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateKVDictItems indicates an expected call of CreateKVDictItems.
func (mr *MockDataDictItemAccessMockRecorder) CreateKVDictItems(ctx, tx, dictID, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKVDictItems", reflect.TypeOf((*MockDataDictItemAccess)(nil).CreateKVDictItems), ctx, tx, dictID, items)
}

// DeleteDataDictItem mocks base method.
func (m *MockDataDictItemAccess) DeleteDataDictItem(ctx context.Context, dictID, itemID, dictStore string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDataDictItem", ctx, dictID, itemID, dictStore)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDataDictItem indicates an expected call of DeleteDataDictItem.
func (mr *MockDataDictItemAccessMockRecorder) DeleteDataDictItem(ctx, dictID, itemID, dictStore interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDataDictItem", reflect.TypeOf((*MockDataDictItemAccess)(nil).DeleteDataDictItem), ctx, dictID, itemID, dictStore)
}

// DeleteDataDictItems mocks base method.
func (m *MockDataDictItemAccess) DeleteDataDictItems(ctx context.Context, dictID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDataDictItems", ctx, dictID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDataDictItems indicates an expected call of DeleteDataDictItems.
func (mr *MockDataDictItemAccessMockRecorder) DeleteDataDictItems(ctx, dictID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDataDictItems", reflect.TypeOf((*MockDataDictItemAccess)(nil).DeleteDataDictItems), ctx, dictID)
}

// DeleteDataDictItemsByItemIDs mocks base method.
func (m *MockDataDictItemAccess) DeleteDataDictItemsByItemIDs(ctx context.Context, tx *sql.Tx, dictID string, itemIDs []string, dictStore string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDataDictItemsByItemIDs", ctx, tx, dictID, itemIDs, dictStore)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDataDictItemsByItemIDs indicates an expected call of DeleteDataDictItemsByItemIDs.
func (mr *MockDataDictItemAccessMockRecorder) DeleteDataDictItemsByItemIDs(ctx, tx, dictID, itemIDs, dictStore interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDataDictItemsByItemIDs", reflect.TypeOf((*MockDataDictItemAccess)(nil).DeleteDataDictItemsByItemIDs), ctx, tx, dictID, itemIDs, dictStore)
}

// DeleteDimensionTable mocks base method.
func (m *MockDataDictItemAccess) DeleteDimensionTable(ctx context.Context, dictStore string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDimensionTable", ctx, dictStore)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDimensionTable indicates an expected call of DeleteDimensionTable.
func (mr *MockDataDictItemAccessMockRecorder) DeleteDimensionTable(ctx, dictStore interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDimensionTable", reflect.TypeOf((*MockDataDictItemAccess)(nil).DeleteDimensionTable), ctx, dictStore)
}

// DropDimensionColumn mocks base method.
func (m *MockDataDictItemAccess) DropDimensionColumn(ctx context.Context, dictStore string, new interfaces.DimensionItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropDimensionColumn", ctx, dictStore, new)
	ret0, _ := ret[0].(error)
	return ret0
}

// DropDimensionColumn indicates an expected call of DropDimensionColumn.
func (mr *MockDataDictItemAccessMockRecorder) DropDimensionColumn(ctx, dictStore, new interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropDimensionColumn", reflect.TypeOf((*MockDataDictItemAccess)(nil).DropDimensionColumn), ctx, dictStore, new)
}

// GetDictItemByItemID mocks base method.
func (m *MockDataDictItemAccess) GetDictItemByItemID(ctx context.Context, dictStore, itemID string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDictItemByItemID", ctx, dictStore, itemID)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDictItemByItemID indicates an expected call of GetDictItemByItemID.
func (mr *MockDataDictItemAccessMockRecorder) GetDictItemByItemID(ctx, dictStore, itemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDictItemByItemID", reflect.TypeOf((*MockDataDictItemAccess)(nil).GetDictItemByItemID), ctx, dictStore, itemID)
}

// GetDictItemIDByKey mocks base method.
func (m *MockDataDictItemAccess) GetDictItemIDByKey(ctx context.Context, dictID, dictStore string, keys []interfaces.DimensionItem) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDictItemIDByKey", ctx, dictID, dictStore, keys)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDictItemIDByKey indicates an expected call of GetDictItemIDByKey.
func (mr *MockDataDictItemAccessMockRecorder) GetDictItemIDByKey(ctx, dictID, dictStore, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDictItemIDByKey", reflect.TypeOf((*MockDataDictItemAccess)(nil).GetDictItemIDByKey), ctx, dictID, dictStore, keys)
}

// GetDictItemTotal mocks base method.
func (m *MockDataDictItemAccess) GetDictItemTotal(ctx context.Context, dict interfaces.DataDict, listDictItemsQuery interfaces.DataDictItemQueryParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDictItemTotal", ctx, dict, listDictItemsQuery)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDictItemTotal indicates an expected call of GetDictItemTotal.
func (mr *MockDataDictItemAccessMockRecorder) GetDictItemTotal(ctx, dict, listDictItemsQuery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDictItemTotal", reflect.TypeOf((*MockDataDictItemAccess)(nil).GetDictItemTotal), ctx, dict, listDictItemsQuery)
}

// GetDimensionDictItems mocks base method.
func (m *MockDataDictItemAccess) GetDimensionDictItems(ctx context.Context, dictStore string, dimension interfaces.Dimension) ([]map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDimensionDictItems", ctx, dictStore, dimension)
	ret0, _ := ret[0].([]map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDimensionDictItems indicates an expected call of GetDimensionDictItems.
func (mr *MockDataDictItemAccessMockRecorder) GetDimensionDictItems(ctx, dictStore, dimension interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDimensionDictItems", reflect.TypeOf((*MockDataDictItemAccess)(nil).GetDimensionDictItems), ctx, dictStore, dimension)
}

// GetKVDictItems mocks base method.
func (m *MockDataDictItemAccess) GetKVDictItems(ctx context.Context, dictID string) ([]map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKVDictItems", ctx, dictID)
	ret0, _ := ret[0].([]map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKVDictItems indicates an expected call of GetKVDictItems.
func (mr *MockDataDictItemAccessMockRecorder) GetKVDictItems(ctx, dictID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKVDictItems", reflect.TypeOf((*MockDataDictItemAccess)(nil).GetKVDictItems), ctx, dictID)
}

// ListDataDictItems mocks base method.
func (m *MockDataDictItemAccess) ListDataDictItems(ctx context.Context, dictID interfaces.DataDict, listDictItemsQuery interfaces.DataDictItemQueryParams) ([]map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDataDictItems", ctx, dictID, listDictItemsQuery)
	ret0, _ := ret[0].([]map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDataDictItems indicates an expected call of ListDataDictItems.
func (mr *MockDataDictItemAccessMockRecorder) ListDataDictItems(ctx, dictID, listDictItemsQuery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDataDictItems", reflect.TypeOf((*MockDataDictItemAccess)(nil).ListDataDictItems), ctx, dictID, listDictItemsQuery)
}

// UpdateDataDictItem mocks base method.
func (m *MockDataDictItemAccess) UpdateDataDictItem(ctx context.Context, dictID, itemID, dictStore string, dimension interfaces.Dimension) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataDictItem", ctx, dictID, itemID, dictStore, dimension)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDataDictItem indicates an expected call of UpdateDataDictItem.
func (mr *MockDataDictItemAccessMockRecorder) UpdateDataDictItem(ctx, dictID, itemID, dictStore, dimension interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataDictItem", reflect.TypeOf((*MockDataDictItemAccess)(nil).UpdateDataDictItem), ctx, dictID, itemID, dictStore, dimension)
}
