// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/metric_model_task_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "data-model/interfaces"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricModelTaskAccess is a mock of MetricModelTaskAccess interface.
type MockMetricModelTaskAccess struct {
	ctrl     *gomock.Controller
	recorder *MockMetricModelTaskAccessMockRecorder
}

// MockMetricModelTaskAccessMockRecorder is the mock recorder for MockMetricModelTaskAccess.
type MockMetricModelTaskAccessMockRecorder struct {
	mock *MockMetricModelTaskAccess
}

// NewMockMetricModelTaskAccess creates a new mock instance.
func NewMockMetricModelTaskAccess(ctrl *gomock.Controller) *MockMetricModelTaskAccess {
	mock := &MockMetricModelTaskAccess{ctrl: ctrl}
	mock.recorder = &MockMetricModelTaskAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricModelTaskAccess) EXPECT() *MockMetricModelTaskAccessMockRecorder {
	return m.recorder
}

// CheckMetricModelTaskExistByName mocks base method.
func (m *MockMetricModelTaskAccess) CheckMetricModelTaskExistByName(ctx context.Context, task interfaces.MetricTask, deleteTaskIDs []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckMetricModelTaskExistByName", ctx, task, deleteTaskIDs)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckMetricModelTaskExistByName indicates an expected call of CheckMetricModelTaskExistByName.
func (mr *MockMetricModelTaskAccessMockRecorder) CheckMetricModelTaskExistByName(ctx, task, deleteTaskIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMetricModelTaskExistByName", reflect.TypeOf((*MockMetricModelTaskAccess)(nil).CheckMetricModelTaskExistByName), ctx, task, deleteTaskIDs)
}

// CreateMetricTask mocks base method.
func (m *MockMetricModelTaskAccess) CreateMetricTask(ctx context.Context, tx *sql.Tx, metricTasks interfaces.MetricTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMetricTask", ctx, tx, metricTasks)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMetricTask indicates an expected call of CreateMetricTask.
func (mr *MockMetricModelTaskAccessMockRecorder) CreateMetricTask(ctx, tx, metricTasks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMetricTask", reflect.TypeOf((*MockMetricModelTaskAccess)(nil).CreateMetricTask), ctx, tx, metricTasks)
}

// DeleteMetricTaskByTaskIDs mocks base method.
func (m *MockMetricModelTaskAccess) DeleteMetricTaskByTaskIDs(ctx context.Context, tx *sql.Tx, taskIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMetricTaskByTaskIDs", ctx, tx, taskIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMetricTaskByTaskIDs indicates an expected call of DeleteMetricTaskByTaskIDs.
func (mr *MockMetricModelTaskAccessMockRecorder) DeleteMetricTaskByTaskIDs(ctx, tx, taskIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMetricTaskByTaskIDs", reflect.TypeOf((*MockMetricModelTaskAccess)(nil).DeleteMetricTaskByTaskIDs), ctx, tx, taskIDs)
}

// GetMetricTaskIDsByModelIDs mocks base method.
func (m *MockMetricModelTaskAccess) GetMetricTaskIDsByModelIDs(ctx context.Context, modelIDs []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricTaskIDsByModelIDs", ctx, modelIDs)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricTaskIDsByModelIDs indicates an expected call of GetMetricTaskIDsByModelIDs.
func (mr *MockMetricModelTaskAccessMockRecorder) GetMetricTaskIDsByModelIDs(ctx, modelIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricTaskIDsByModelIDs", reflect.TypeOf((*MockMetricModelTaskAccess)(nil).GetMetricTaskIDsByModelIDs), ctx, modelIDs)
}

// GetMetricTasksByModelIDs mocks base method.
func (m *MockMetricModelTaskAccess) GetMetricTasksByModelIDs(ctx context.Context, modelIDs []string) (map[string]interfaces.MetricTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricTasksByModelIDs", ctx, modelIDs)
	ret0, _ := ret[0].(map[string]interfaces.MetricTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricTasksByModelIDs indicates an expected call of GetMetricTasksByModelIDs.
func (mr *MockMetricModelTaskAccessMockRecorder) GetMetricTasksByModelIDs(ctx, modelIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricTasksByModelIDs", reflect.TypeOf((*MockMetricModelTaskAccess)(nil).GetMetricTasksByModelIDs), ctx, modelIDs)
}

// GetMetricTasksByTaskIDs mocks base method.
func (m *MockMetricModelTaskAccess) GetMetricTasksByTaskIDs(ctx context.Context, taskIDs []string) ([]interfaces.MetricTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricTasksByTaskIDs", ctx, taskIDs)
	ret0, _ := ret[0].([]interfaces.MetricTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricTasksByTaskIDs indicates an expected call of GetMetricTasksByTaskIDs.
func (mr *MockMetricModelTaskAccessMockRecorder) GetMetricTasksByTaskIDs(ctx, taskIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricTasksByTaskIDs", reflect.TypeOf((*MockMetricModelTaskAccess)(nil).GetMetricTasksByTaskIDs), ctx, taskIDs)
}

// UpdateMetricTask mocks base method.
func (m *MockMetricModelTaskAccess) UpdateMetricTask(ctx context.Context, tx *sql.Tx, task interfaces.MetricTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetricTask", ctx, tx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetricTask indicates an expected call of UpdateMetricTask.
func (mr *MockMetricModelTaskAccessMockRecorder) UpdateMetricTask(ctx, tx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetricTask", reflect.TypeOf((*MockMetricModelTaskAccess)(nil).UpdateMetricTask), ctx, tx, task)
}

// UpdateMetricTaskAttributes mocks base method.
func (m *MockMetricModelTaskAccess) UpdateMetricTaskAttributes(ctx context.Context, task interfaces.MetricTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetricTaskAttributes", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetricTaskAttributes indicates an expected call of UpdateMetricTaskAttributes.
func (mr *MockMetricModelTaskAccessMockRecorder) UpdateMetricTaskAttributes(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetricTaskAttributes", reflect.TypeOf((*MockMetricModelTaskAccess)(nil).UpdateMetricTaskAttributes), ctx, task)
}

// UpdateMetricTaskStatusInFinish mocks base method.
func (m *MockMetricModelTaskAccess) UpdateMetricTaskStatusInFinish(ctx context.Context, task interfaces.MetricTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetricTaskStatusInFinish", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetricTaskStatusInFinish indicates an expected call of UpdateMetricTaskStatusInFinish.
func (mr *MockMetricModelTaskAccessMockRecorder) UpdateMetricTaskStatusInFinish(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetricTaskStatusInFinish", reflect.TypeOf((*MockMetricModelTaskAccess)(nil).UpdateMetricTaskStatusInFinish), ctx, task)
}
