// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/data_view_group_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "data-model/interfaces"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataViewGroupService is a mock of DataViewGroupService interface.
type MockDataViewGroupService struct {
	ctrl     *gomock.Controller
	recorder *MockDataViewGroupServiceMockRecorder
}

// MockDataViewGroupServiceMockRecorder is the mock recorder for MockDataViewGroupService.
type MockDataViewGroupServiceMockRecorder struct {
	mock *MockDataViewGroupService
}

// NewMockDataViewGroupService creates a new mock instance.
func NewMockDataViewGroupService(ctrl *gomock.Controller) *MockDataViewGroupService {
	mock := &MockDataViewGroupService{ctrl: ctrl}
	mock.recorder = &MockDataViewGroupServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataViewGroupService) EXPECT() *MockDataViewGroupServiceMockRecorder {
	return m.recorder
}

// CheckDataViewGroupExistByName mocks base method.
func (m *MockDataViewGroupService) CheckDataViewGroupExistByName(ctx context.Context, tx *sql.Tx, name string, builtin bool) (*interfaces.DataViewGroup, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDataViewGroupExistByName", ctx, tx, name, builtin)
	ret0, _ := ret[0].(*interfaces.DataViewGroup)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckDataViewGroupExistByName indicates an expected call of CheckDataViewGroupExistByName.
func (mr *MockDataViewGroupServiceMockRecorder) CheckDataViewGroupExistByName(ctx, tx, name, builtin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDataViewGroupExistByName", reflect.TypeOf((*MockDataViewGroupService)(nil).CheckDataViewGroupExistByName), ctx, tx, name, builtin)
}

// CreateDataViewGroup mocks base method.
func (m *MockDataViewGroupService) CreateDataViewGroup(ctx context.Context, tx *sql.Tx, group *interfaces.DataViewGroup) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDataViewGroup", ctx, tx, group)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDataViewGroup indicates an expected call of CreateDataViewGroup.
func (mr *MockDataViewGroupServiceMockRecorder) CreateDataViewGroup(ctx, tx, group interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDataViewGroup", reflect.TypeOf((*MockDataViewGroupService)(nil).CreateDataViewGroup), ctx, tx, group)
}

// DeleteDataViewGroup mocks base method.
func (m *MockDataViewGroupService) DeleteDataViewGroup(ctx context.Context, groupID string, includeViews bool) ([]*interfaces.SimpleDataView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDataViewGroup", ctx, groupID, includeViews)
	ret0, _ := ret[0].([]*interfaces.SimpleDataView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDataViewGroup indicates an expected call of DeleteDataViewGroup.
func (mr *MockDataViewGroupServiceMockRecorder) DeleteDataViewGroup(ctx, groupID, includeViews interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDataViewGroup", reflect.TypeOf((*MockDataViewGroupService)(nil).DeleteDataViewGroup), ctx, groupID, includeViews)
}

// GetDataViewGroupByID mocks base method.
func (m *MockDataViewGroupService) GetDataViewGroupByID(ctx context.Context, groupID string) (*interfaces.DataViewGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataViewGroupByID", ctx, groupID)
	ret0, _ := ret[0].(*interfaces.DataViewGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataViewGroupByID indicates an expected call of GetDataViewGroupByID.
func (mr *MockDataViewGroupServiceMockRecorder) GetDataViewGroupByID(ctx, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataViewGroupByID", reflect.TypeOf((*MockDataViewGroupService)(nil).GetDataViewGroupByID), ctx, groupID)
}

// ListDataViewGroups mocks base method.
func (m *MockDataViewGroupService) ListDataViewGroups(ctx context.Context, params *interfaces.ListViewGroupQueryParams, includeViews bool) ([]*interfaces.DataViewGroup, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDataViewGroups", ctx, params, includeViews)
	ret0, _ := ret[0].([]*interfaces.DataViewGroup)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDataViewGroups indicates an expected call of ListDataViewGroups.
func (mr *MockDataViewGroupServiceMockRecorder) ListDataViewGroups(ctx, params, includeViews interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDataViewGroups", reflect.TypeOf((*MockDataViewGroupService)(nil).ListDataViewGroups), ctx, params, includeViews)
}

// MarkDataViewGroupDeleted mocks base method.
func (m *MockDataViewGroupService) MarkDataViewGroupDeleted(ctx context.Context, groupID string, includeViews bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDataViewGroupDeleted", ctx, groupID, includeViews)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDataViewGroupDeleted indicates an expected call of MarkDataViewGroupDeleted.
func (mr *MockDataViewGroupServiceMockRecorder) MarkDataViewGroupDeleted(ctx, groupID, includeViews interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDataViewGroupDeleted", reflect.TypeOf((*MockDataViewGroupService)(nil).MarkDataViewGroupDeleted), ctx, groupID, includeViews)
}

// UpdateDataViewGroup mocks base method.
func (m *MockDataViewGroupService) UpdateDataViewGroup(ctx context.Context, group *interfaces.DataViewGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataViewGroup", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDataViewGroup indicates an expected call of UpdateDataViewGroup.
func (mr *MockDataViewGroupServiceMockRecorder) UpdateDataViewGroup(ctx, group interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataViewGroup", reflect.TypeOf((*MockDataViewGroupService)(nil).UpdateDataViewGroup), ctx, group)
}
