// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/trace_model_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "data-model/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTraceModelAccess is a mock of TraceModelAccess interface.
type MockTraceModelAccess struct {
	ctrl     *gomock.Controller
	recorder *MockTraceModelAccessMockRecorder
}

// MockTraceModelAccessMockRecorder is the mock recorder for MockTraceModelAccess.
type MockTraceModelAccessMockRecorder struct {
	mock *MockTraceModelAccess
}

// NewMockTraceModelAccess creates a new mock instance.
func NewMockTraceModelAccess(ctrl *gomock.Controller) *MockTraceModelAccess {
	mock := &MockTraceModelAccess{ctrl: ctrl}
	mock.recorder = &MockTraceModelAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTraceModelAccess) EXPECT() *MockTraceModelAccessMockRecorder {
	return m.recorder
}

// CreateTraceModels mocks base method.
func (m *MockTraceModelAccess) CreateTraceModels(ctx context.Context, models []interfaces.TraceModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTraceModels", ctx, models)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTraceModels indicates an expected call of CreateTraceModels.
func (mr *MockTraceModelAccessMockRecorder) CreateTraceModels(ctx, models interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTraceModels", reflect.TypeOf((*MockTraceModelAccess)(nil).CreateTraceModels), ctx, models)
}

// DeleteTraceModels mocks base method.
func (m *MockTraceModelAccess) DeleteTraceModels(ctx context.Context, modelIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTraceModels", ctx, modelIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTraceModels indicates an expected call of DeleteTraceModels.
func (mr *MockTraceModelAccessMockRecorder) DeleteTraceModels(ctx, modelIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTraceModels", reflect.TypeOf((*MockTraceModelAccess)(nil).DeleteTraceModels), ctx, modelIDs)
}

// GetDetailedTraceModelMapByIDs mocks base method.
func (m *MockTraceModelAccess) GetDetailedTraceModelMapByIDs(ctx context.Context, modelIDs []string) (map[string]interfaces.TraceModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetailedTraceModelMapByIDs", ctx, modelIDs)
	ret0, _ := ret[0].(map[string]interfaces.TraceModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetailedTraceModelMapByIDs indicates an expected call of GetDetailedTraceModelMapByIDs.
func (mr *MockTraceModelAccessMockRecorder) GetDetailedTraceModelMapByIDs(ctx, modelIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetailedTraceModelMapByIDs", reflect.TypeOf((*MockTraceModelAccess)(nil).GetDetailedTraceModelMapByIDs), ctx, modelIDs)
}

// GetSimpleTraceModelMapByIDs mocks base method.
func (m *MockTraceModelAccess) GetSimpleTraceModelMapByIDs(ctx context.Context, modelIDs []string) (map[string]interfaces.TraceModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimpleTraceModelMapByIDs", ctx, modelIDs)
	ret0, _ := ret[0].(map[string]interfaces.TraceModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimpleTraceModelMapByIDs indicates an expected call of GetSimpleTraceModelMapByIDs.
func (mr *MockTraceModelAccessMockRecorder) GetSimpleTraceModelMapByIDs(ctx, modelIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimpleTraceModelMapByIDs", reflect.TypeOf((*MockTraceModelAccess)(nil).GetSimpleTraceModelMapByIDs), ctx, modelIDs)
}

// GetSimpleTraceModelMapByNames mocks base method.
func (m *MockTraceModelAccess) GetSimpleTraceModelMapByNames(ctx context.Context, modelNames []string) (map[string]interfaces.TraceModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimpleTraceModelMapByNames", ctx, modelNames)
	ret0, _ := ret[0].(map[string]interfaces.TraceModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimpleTraceModelMapByNames indicates an expected call of GetSimpleTraceModelMapByNames.
func (mr *MockTraceModelAccessMockRecorder) GetSimpleTraceModelMapByNames(ctx, modelNames interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimpleTraceModelMapByNames", reflect.TypeOf((*MockTraceModelAccess)(nil).GetSimpleTraceModelMapByNames), ctx, modelNames)
}

// GetTraceModelTotal mocks base method.
func (m *MockTraceModelAccess) GetTraceModelTotal(ctx context.Context, queryParams interfaces.TraceModelListQueryParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTraceModelTotal", ctx, queryParams)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTraceModelTotal indicates an expected call of GetTraceModelTotal.
func (mr *MockTraceModelAccessMockRecorder) GetTraceModelTotal(ctx, queryParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTraceModelTotal", reflect.TypeOf((*MockTraceModelAccess)(nil).GetTraceModelTotal), ctx, queryParams)
}

// ListTraceModels mocks base method.
func (m *MockTraceModelAccess) ListTraceModels(ctx context.Context, queryParams interfaces.TraceModelListQueryParams) ([]interfaces.TraceModelListEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTraceModels", ctx, queryParams)
	ret0, _ := ret[0].([]interfaces.TraceModelListEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTraceModels indicates an expected call of ListTraceModels.
func (mr *MockTraceModelAccessMockRecorder) ListTraceModels(ctx, queryParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTraceModels", reflect.TypeOf((*MockTraceModelAccess)(nil).ListTraceModels), ctx, queryParams)
}

// UpdateTraceModel mocks base method.
func (m *MockTraceModelAccess) UpdateTraceModel(ctx context.Context, model interfaces.TraceModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTraceModel", ctx, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTraceModel indicates an expected call of UpdateTraceModel.
func (mr *MockTraceModelAccessMockRecorder) UpdateTraceModel(ctx, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTraceModel", reflect.TypeOf((*MockTraceModelAccess)(nil).UpdateTraceModel), ctx, model)
}
