// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/metric_model_group_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "data-model/interfaces"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricModelGroupAccess is a mock of MetricModelGroupAccess interface.
type MockMetricModelGroupAccess struct {
	ctrl     *gomock.Controller
	recorder *MockMetricModelGroupAccessMockRecorder
}

// MockMetricModelGroupAccessMockRecorder is the mock recorder for MockMetricModelGroupAccess.
type MockMetricModelGroupAccessMockRecorder struct {
	mock *MockMetricModelGroupAccess
}

// NewMockMetricModelGroupAccess creates a new mock instance.
func NewMockMetricModelGroupAccess(ctrl *gomock.Controller) *MockMetricModelGroupAccess {
	mock := &MockMetricModelGroupAccess{ctrl: ctrl}
	mock.recorder = &MockMetricModelGroupAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricModelGroupAccess) EXPECT() *MockMetricModelGroupAccessMockRecorder {
	return m.recorder
}

// CheckMetricModelGroupExist mocks base method.
func (m *MockMetricModelGroupAccess) CheckMetricModelGroupExist(ctx context.Context, groupName string) (interfaces.MetricModelGroup, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckMetricModelGroupExist", ctx, groupName)
	ret0, _ := ret[0].(interfaces.MetricModelGroup)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckMetricModelGroupExist indicates an expected call of CheckMetricModelGroupExist.
func (mr *MockMetricModelGroupAccessMockRecorder) CheckMetricModelGroupExist(ctx, groupName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMetricModelGroupExist", reflect.TypeOf((*MockMetricModelGroupAccess)(nil).CheckMetricModelGroupExist), ctx, groupName)
}

// CreateMetricModelGroup mocks base method.
func (m *MockMetricModelGroupAccess) CreateMetricModelGroup(ctx context.Context, tx *sql.Tx, metricModelGroup interfaces.MetricModelGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMetricModelGroup", ctx, tx, metricModelGroup)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMetricModelGroup indicates an expected call of CreateMetricModelGroup.
func (mr *MockMetricModelGroupAccessMockRecorder) CreateMetricModelGroup(ctx, tx, metricModelGroup interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMetricModelGroup", reflect.TypeOf((*MockMetricModelGroupAccess)(nil).CreateMetricModelGroup), ctx, tx, metricModelGroup)
}

// DeleteMetricModelGroup mocks base method.
func (m *MockMetricModelGroupAccess) DeleteMetricModelGroup(ctx context.Context, tx *sql.Tx, groupID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMetricModelGroup", ctx, tx, groupID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMetricModelGroup indicates an expected call of DeleteMetricModelGroup.
func (mr *MockMetricModelGroupAccessMockRecorder) DeleteMetricModelGroup(ctx, tx, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMetricModelGroup", reflect.TypeOf((*MockMetricModelGroupAccess)(nil).DeleteMetricModelGroup), ctx, tx, groupID)
}

// GetMetricModelGroupByID mocks base method.
func (m *MockMetricModelGroupAccess) GetMetricModelGroupByID(ctx context.Context, groupID string) (interfaces.MetricModelGroup, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricModelGroupByID", ctx, groupID)
	ret0, _ := ret[0].(interfaces.MetricModelGroup)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMetricModelGroupByID indicates an expected call of GetMetricModelGroupByID.
func (mr *MockMetricModelGroupAccessMockRecorder) GetMetricModelGroupByID(ctx, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricModelGroupByID", reflect.TypeOf((*MockMetricModelGroupAccess)(nil).GetMetricModelGroupByID), ctx, groupID)
}

// GetMetricModelGroupByName mocks base method.
func (m *MockMetricModelGroupAccess) GetMetricModelGroupByName(ctx context.Context, tx *sql.Tx, groupName string) (interfaces.MetricModelGroup, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricModelGroupByName", ctx, tx, groupName)
	ret0, _ := ret[0].(interfaces.MetricModelGroup)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMetricModelGroupByName indicates an expected call of GetMetricModelGroupByName.
func (mr *MockMetricModelGroupAccessMockRecorder) GetMetricModelGroupByName(ctx, tx, groupName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricModelGroupByName", reflect.TypeOf((*MockMetricModelGroupAccess)(nil).GetMetricModelGroupByName), ctx, tx, groupName)
}

// GetMetricModelGroupsTotal mocks base method.
func (m *MockMetricModelGroupAccess) GetMetricModelGroupsTotal(ctx context.Context, params interfaces.ListMetricGroupQueryParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricModelGroupsTotal", ctx, params)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricModelGroupsTotal indicates an expected call of GetMetricModelGroupsTotal.
func (mr *MockMetricModelGroupAccessMockRecorder) GetMetricModelGroupsTotal(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricModelGroupsTotal", reflect.TypeOf((*MockMetricModelGroupAccess)(nil).GetMetricModelGroupsTotal), ctx, params)
}

// ListMetricModelGroups mocks base method.
func (m *MockMetricModelGroupAccess) ListMetricModelGroups(ctx context.Context, params interfaces.ListMetricGroupQueryParams) ([]*interfaces.MetricModelGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMetricModelGroups", ctx, params)
	ret0, _ := ret[0].([]*interfaces.MetricModelGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMetricModelGroups indicates an expected call of ListMetricModelGroups.
func (mr *MockMetricModelGroupAccessMockRecorder) ListMetricModelGroups(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMetricModelGroups", reflect.TypeOf((*MockMetricModelGroupAccess)(nil).ListMetricModelGroups), ctx, params)
}

// UpdateMetricModelGroup mocks base method.
func (m *MockMetricModelGroupAccess) UpdateMetricModelGroup(ctx context.Context, metricModelGroup interfaces.MetricModelGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetricModelGroup", ctx, metricModelGroup)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetricModelGroup indicates an expected call of UpdateMetricModelGroup.
func (mr *MockMetricModelGroupAccessMockRecorder) UpdateMetricModelGroup(ctx, metricModelGroup interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetricModelGroup", reflect.TypeOf((*MockMetricModelGroupAccess)(nil).UpdateMetricModelGroup), ctx, metricModelGroup)
}
