// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/data_view_monitor_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataViewMonitorService is a mock of DataViewMonitorService interface.
type MockDataViewMonitorService struct {
	ctrl     *gomock.Controller
	recorder *MockDataViewMonitorServiceMockRecorder
}

// MockDataViewMonitorServiceMockRecorder is the mock recorder for MockDataViewMonitorService.
type MockDataViewMonitorServiceMockRecorder struct {
	mock *MockDataViewMonitorService
}

// NewMockDataViewMonitorService creates a new mock instance.
func NewMockDataViewMonitorService(ctrl *gomock.Controller) *MockDataViewMonitorService {
	mock := &MockDataViewMonitorService{ctrl: ctrl}
	mock.recorder = &MockDataViewMonitorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataViewMonitorService) EXPECT() *MockDataViewMonitorServiceMockRecorder {
	return m.recorder
}

// PollingMetadata mocks base method.
func (m *MockDataViewMonitorService) PollingMetadata(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PollingMetadata", ctx)
}

// PollingMetadata indicates an expected call of PollingMetadata.
func (mr *MockDataViewMonitorServiceMockRecorder) PollingMetadata(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollingMetadata", reflect.TypeOf((*MockDataViewMonitorService)(nil).PollingMetadata), ctx)
}
