// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/vega_gateway_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	gomock "github.com/golang/mock/gomock"
)

// MockVegaGatewayAccess is a mock of VegaGatewayAccess interface.
type MockVegaGatewayAccess struct {
	ctrl     *gomock.Controller
	recorder *MockVegaGatewayAccessMockRecorder
}

// MockVegaGatewayAccessMockRecorder is the mock recorder for MockVegaGatewayAccess.
type MockVegaGatewayAccessMockRecorder struct {
	mock *MockVegaGatewayAccess
}

// NewMockVegaGatewayAccess creates a new mock instance.
func NewMockVegaGatewayAccess(ctrl *gomock.Controller) *MockVegaGatewayAccess {
	mock := &MockVegaGatewayAccess{ctrl: ctrl}
	mock.recorder = &MockVegaGatewayAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVegaGatewayAccess) EXPECT() *MockVegaGatewayAccessMockRecorder {
	return m.recorder
}
