// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/knowledge_network_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "ontology-query/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockKnowledgeNetworkService is a mock of KnowledgeNetworkService interface.
type MockKnowledgeNetworkService struct {
	ctrl     *gomock.Controller
	recorder *MockKnowledgeNetworkServiceMockRecorder
}

// MockKnowledgeNetworkServiceMockRecorder is the mock recorder for MockKnowledgeNetworkService.
type MockKnowledgeNetworkServiceMockRecorder struct {
	mock *MockKnowledgeNetworkService
}

// NewMockKnowledgeNetworkService creates a new mock instance.
func NewMockKnowledgeNetworkService(ctrl *gomock.Controller) *MockKnowledgeNetworkService {
	mock := &MockKnowledgeNetworkService{ctrl: ctrl}
	mock.recorder = &MockKnowledgeNetworkServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKnowledgeNetworkService) EXPECT() *MockKnowledgeNetworkServiceMockRecorder {
	return m.recorder
}

// SearchSubgraph mocks base method.
func (m *MockKnowledgeNetworkService) SearchSubgraph(ctx context.Context, query *interfaces.SubGraphQueryBaseOnSource) (interfaces.ObjectSubGraph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSubgraph", ctx, query)
	ret0, _ := ret[0].(interfaces.ObjectSubGraph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSubgraph indicates an expected call of SearchSubgraph.
func (mr *MockKnowledgeNetworkServiceMockRecorder) SearchSubgraph(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSubgraph", reflect.TypeOf((*MockKnowledgeNetworkService)(nil).SearchSubgraph), ctx, query)
}

// SearchSubgraphByTypePath mocks base method.
func (m *MockKnowledgeNetworkService) SearchSubgraphByTypePath(ctx context.Context, query *interfaces.SubGraphQueryBaseOnTypePath) (interfaces.PathsEntries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSubgraphByTypePath", ctx, query)
	ret0, _ := ret[0].(interfaces.PathsEntries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSubgraphByTypePath indicates an expected call of SearchSubgraphByTypePath.
func (mr *MockKnowledgeNetworkServiceMockRecorder) SearchSubgraphByTypePath(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSubgraphByTypePath", reflect.TypeOf((*MockKnowledgeNetworkService)(nil).SearchSubgraphByTypePath), ctx, query)
}
