// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/trace_model_adapter.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "uniquery/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockTraceModelAdapter is a mock of TraceModelAdapter interface.
type MockTraceModelAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockTraceModelAdapterMockRecorder
}

// MockTraceModelAdapterMockRecorder is the mock recorder for MockTraceModelAdapter.
type MockTraceModelAdapterMockRecorder struct {
	mock *MockTraceModelAdapter
}

// NewMockTraceModelAdapter creates a new mock instance.
func NewMockTraceModelAdapter(ctrl *gomock.Controller) *MockTraceModelAdapter {
	mock := &MockTraceModelAdapter{ctrl: ctrl}
	mock.recorder = &MockTraceModelAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTraceModelAdapter) EXPECT() *MockTraceModelAdapterMockRecorder {
	return m.recorder
}

// GetRelatedLogCountMap mocks base method.
func (m *MockTraceModelAdapter) GetRelatedLogCountMap(ctx context.Context, model interfaces.TraceModel, params interfaces.TraceQueryParams) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelatedLogCountMap", ctx, model, params)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelatedLogCountMap indicates an expected call of GetRelatedLogCountMap.
func (mr *MockTraceModelAdapterMockRecorder) GetRelatedLogCountMap(ctx, model, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelatedLogCountMap", reflect.TypeOf((*MockTraceModelAdapter)(nil).GetRelatedLogCountMap), ctx, model, params)
}

// GetSpan mocks base method.
func (m *MockTraceModelAdapter) GetSpan(ctx context.Context, model interfaces.TraceModel, params interfaces.SpanQueryParams) (interfaces.SpanDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpan", ctx, model, params)
	ret0, _ := ret[0].(interfaces.SpanDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpan indicates an expected call of GetSpan.
func (mr *MockTraceModelAdapterMockRecorder) GetSpan(ctx, model, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpan", reflect.TypeOf((*MockTraceModelAdapter)(nil).GetSpan), ctx, model, params)
}

// GetSpanList mocks base method.
func (m *MockTraceModelAdapter) GetSpanList(ctx context.Context, model interfaces.TraceModel, params interfaces.SpanListQueryParams) ([]interfaces.SpanListEntry, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpanList", ctx, model, params)
	ret0, _ := ret[0].([]interfaces.SpanListEntry)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSpanList indicates an expected call of GetSpanList.
func (mr *MockTraceModelAdapterMockRecorder) GetSpanList(ctx, model, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpanList", reflect.TypeOf((*MockTraceModelAdapter)(nil).GetSpanList), ctx, model, params)
}

// GetSpanMap mocks base method.
func (m *MockTraceModelAdapter) GetSpanMap(ctx context.Context, model interfaces.TraceModel, params interfaces.TraceQueryParams) (map[string]*interfaces.BriefSpan_, map[string]interfaces.SpanDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpanMap", ctx, model, params)
	ret0, _ := ret[0].(map[string]*interfaces.BriefSpan_)
	ret1, _ := ret[1].(map[string]interfaces.SpanDetail)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSpanMap indicates an expected call of GetSpanMap.
func (mr *MockTraceModelAdapterMockRecorder) GetSpanMap(ctx, model, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpanMap", reflect.TypeOf((*MockTraceModelAdapter)(nil).GetSpanMap), ctx, model, params)
}

// GetSpanRelatedLogList mocks base method.
func (m *MockTraceModelAdapter) GetSpanRelatedLogList(ctx context.Context, model interfaces.TraceModel, params interfaces.RelatedLogListQueryParams) ([]interfaces.RelatedLogListEntry, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpanRelatedLogList", ctx, model, params)
	ret0, _ := ret[0].([]interfaces.RelatedLogListEntry)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSpanRelatedLogList indicates an expected call of GetSpanRelatedLogList.
func (mr *MockTraceModelAdapterMockRecorder) GetSpanRelatedLogList(ctx, model, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpanRelatedLogList", reflect.TypeOf((*MockTraceModelAdapter)(nil).GetSpanRelatedLogList), ctx, model, params)
}
