// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/vega_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "uniquery/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockVegaService is a mock of VegaService interface.
type MockVegaService struct {
	ctrl     *gomock.Controller
	recorder *MockVegaServiceMockRecorder
}

// MockVegaServiceMockRecorder is the mock recorder for MockVegaService.
type MockVegaServiceMockRecorder struct {
	mock *MockVegaService
}

// NewMockVegaService creates a new mock instance.
func NewMockVegaService(ctrl *gomock.Controller) *MockVegaService {
	mock := &MockVegaService{ctrl: ctrl}
	mock.recorder = &MockVegaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVegaService) EXPECT() *MockVegaServiceMockRecorder {
	return m.recorder
}

// FetchDatasFromVega mocks base method.
func (m *MockVegaService) FetchDatasFromVega(ctx context.Context, sql string) (interfaces.VegaFetchData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDatasFromVega", ctx, sql)
	ret0, _ := ret[0].(interfaces.VegaFetchData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDatasFromVega indicates an expected call of FetchDatasFromVega.
func (mr *MockVegaServiceMockRecorder) FetchDatasFromVega(ctx, sql interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDatasFromVega", reflect.TypeOf((*MockVegaService)(nil).FetchDatasFromVega), ctx, sql)
}

// GetVegaViewFieldsByID mocks base method.
func (m *MockVegaService) GetVegaViewFieldsByID(ctx context.Context, viewID string) (interfaces.VegaViewWithFields, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVegaViewFieldsByID", ctx, viewID)
	ret0, _ := ret[0].(interfaces.VegaViewWithFields)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVegaViewFieldsByID indicates an expected call of GetVegaViewFieldsByID.
func (mr *MockVegaServiceMockRecorder) GetVegaViewFieldsByID(ctx, viewID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVegaViewFieldsByID", reflect.TypeOf((*MockVegaService)(nil).GetVegaViewFieldsByID), ctx, viewID)
}
