// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/event_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "uniquery/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockEventService is a mock of EventService interface.
type MockEventService struct {
	ctrl     *gomock.Controller
	recorder *MockEventServiceMockRecorder
}

// MockEventServiceMockRecorder is the mock recorder for MockEventService.
type MockEventServiceMockRecorder struct {
	mock *MockEventService
}

// NewMockEventService creates a new mock instance.
func NewMockEventService(ctrl *gomock.Controller) *MockEventService {
	mock := &MockEventService{ctrl: ctrl}
	mock.recorder = &MockEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventService) EXPECT() *MockEventServiceMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockEventService) Query(ctx context.Context, queryReq interfaces.EventQueryReq) (int, any, []interfaces.Records, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, queryReq)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(any)
	ret2, _ := ret[2].([]interfaces.Records)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Query indicates an expected call of Query.
func (mr *MockEventServiceMockRecorder) Query(ctx, queryReq interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockEventService)(nil).Query), ctx, queryReq)
}

// QuerySingleEventByEventId mocks base method.
func (m *MockEventService) QuerySingleEventByEventId(ctx context.Context, query interfaces.EventDetailsQueryReq) (interfaces.IEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuerySingleEventByEventId", ctx, query)
	ret0, _ := ret[0].(interfaces.IEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuerySingleEventByEventId indicates an expected call of QuerySingleEventByEventId.
func (mr *MockEventServiceMockRecorder) QuerySingleEventByEventId(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySingleEventByEventId", reflect.TypeOf((*MockEventService)(nil).QuerySingleEventByEventId), ctx, query)
}

// MockEventEngine is a mock of EventEngine interface.
type MockEventEngine struct {
	ctrl     *gomock.Controller
	recorder *MockEventEngineMockRecorder
}

// MockEventEngineMockRecorder is the mock recorder for MockEventEngine.
type MockEventEngineMockRecorder struct {
	mock *MockEventEngine
}

// NewMockEventEngine creates a new mock instance.
func NewMockEventEngine(ctrl *gomock.Controller) *MockEventEngine {
	mock := &MockEventEngine{ctrl: ctrl}
	mock.recorder = &MockEventEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventEngine) EXPECT() *MockEventEngineMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockEventEngine) Apply(ctx context.Context, query interfaces.EventQuery, em interfaces.EventModel) (interfaces.IEvents, interfaces.Records, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, query, em)
	ret0, _ := ret[0].(interfaces.IEvents)
	ret1, _ := ret[1].(interfaces.Records)
	ret2, _ := ret[2].(int)
	return ret0, ret1, ret2
}

// Apply indicates an expected call of Apply.
func (mr *MockEventEngineMockRecorder) Apply(ctx, query, em interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockEventEngine)(nil).Apply), ctx, query, em)
}

// Assemble mocks base method.
func (m *MockEventEngine) Assemble(Events interfaces.IEvents, sortKey, direction string, limit, offsert int64) (interfaces.IEvents, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assemble", Events, sortKey, direction, limit, offsert)
	ret0, _ := ret[0].(interfaces.IEvents)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Assemble indicates an expected call of Assemble.
func (mr *MockEventEngineMockRecorder) Assemble(Events, sortKey, direction, limit, offsert interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assemble", reflect.TypeOf((*MockEventEngine)(nil).Assemble), Events, sortKey, direction, limit, offsert)
}

// Judge mocks base method.
func (m *MockEventEngine) Judge(ctx context.Context, sr interfaces.SourceRecords, em interfaces.EventModel) (interfaces.IEvents, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Judge", ctx, sr, em)
	ret0, _ := ret[0].(interfaces.IEvents)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Judge indicates an expected call of Judge.
func (mr *MockEventEngineMockRecorder) Judge(ctx, sr, em interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Judge", reflect.TypeOf((*MockEventEngine)(nil).Judge), ctx, sr, em)
}

// QuerySingleEventByEventId mocks base method.
func (m *MockEventEngine) QuerySingleEventByEventId(ctx context.Context, em interfaces.EventModel, query interfaces.EventDetailsQueryReq) (interfaces.IEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuerySingleEventByEventId", ctx, em, query)
	ret0, _ := ret[0].(interfaces.IEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuerySingleEventByEventId indicates an expected call of QuerySingleEventByEventId.
func (mr *MockEventEngineMockRecorder) QuerySingleEventByEventId(ctx, em, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySingleEventByEventId", reflect.TypeOf((*MockEventEngine)(nil).QuerySingleEventByEventId), ctx, em, query)
}

// MockDataModelQuery is a mock of DataModelQuery interface.
type MockDataModelQuery struct {
	ctrl     *gomock.Controller
	recorder *MockDataModelQueryMockRecorder
}

// MockDataModelQueryMockRecorder is the mock recorder for MockDataModelQuery.
type MockDataModelQueryMockRecorder struct {
	mock *MockDataModelQuery
}

// NewMockDataModelQuery creates a new mock instance.
func NewMockDataModelQuery(ctrl *gomock.Controller) *MockDataModelQuery {
	mock := &MockDataModelQuery{ctrl: ctrl}
	mock.recorder = &MockDataModelQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataModelQuery) EXPECT() *MockDataModelQueryMockRecorder {
	return m.recorder
}

// FetchSourceRecordsFrom mocks base method.
func (m *MockDataModelQuery) FetchSourceRecordsFrom(ctx context.Context, format string) (interfaces.SourceRecords, interfaces.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchSourceRecordsFrom", ctx, format)
	ret0, _ := ret[0].(interfaces.SourceRecords)
	ret1, _ := ret[1].(interfaces.Record)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchSourceRecordsFrom indicates an expected call of FetchSourceRecordsFrom.
func (mr *MockDataModelQueryMockRecorder) FetchSourceRecordsFrom(ctx, format interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchSourceRecordsFrom", reflect.TypeOf((*MockDataModelQuery)(nil).FetchSourceRecordsFrom), ctx, format)
}
