// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/vega_data_source_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "uniquery/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockVegaDataSourceAccess is a mock of VegaDataSourceAccess interface.
type MockVegaDataSourceAccess struct {
	ctrl     *gomock.Controller
	recorder *MockVegaDataSourceAccessMockRecorder
}

// MockVegaDataSourceAccessMockRecorder is the mock recorder for MockVegaDataSourceAccess.
type MockVegaDataSourceAccessMockRecorder struct {
	mock *MockVegaDataSourceAccess
}

// NewMockVegaDataSourceAccess creates a new mock instance.
func NewMockVegaDataSourceAccess(ctrl *gomock.Controller) *MockVegaDataSourceAccess {
	mock := &MockVegaDataSourceAccess{ctrl: ctrl}
	mock.recorder = &MockVegaDataSourceAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVegaDataSourceAccess) EXPECT() *MockVegaDataSourceAccessMockRecorder {
	return m.recorder
}

// GetDataSourceByID mocks base method.
func (m *MockVegaDataSourceAccess) GetDataSourceByID(ctx context.Context, dataSourceID string) (*interfaces.VegaDataSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataSourceByID", ctx, dataSourceID)
	ret0, _ := ret[0].(*interfaces.VegaDataSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataSourceByID indicates an expected call of GetDataSourceByID.
func (mr *MockVegaDataSourceAccessMockRecorder) GetDataSourceByID(ctx, dataSourceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataSourceByID", reflect.TypeOf((*MockVegaDataSourceAccess)(nil).GetDataSourceByID), ctx, dataSourceID)
}
