// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/data_view_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	bytes "bytes"
	context "context"
	reflect "reflect"
	time "time"
	interfaces "uniquery/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockDataViewService is a mock of DataViewService interface.
type MockDataViewService struct {
	ctrl     *gomock.Controller
	recorder *MockDataViewServiceMockRecorder
}

// MockDataViewServiceMockRecorder is the mock recorder for MockDataViewService.
type MockDataViewServiceMockRecorder struct {
	mock *MockDataViewService
}

// NewMockDataViewService creates a new mock instance.
func NewMockDataViewService(ctrl *gomock.Controller) *MockDataViewService {
	mock := &MockDataViewService{ctrl: ctrl}
	mock.recorder = &MockDataViewServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataViewService) EXPECT() *MockDataViewServiceMockRecorder {
	return m.recorder
}

// BuildViewQuery4MetricModel mocks base method.
func (m *MockDataViewService) BuildViewQuery4MetricModel(ctx context.Context, start, end int64, view *interfaces.DataView) (interfaces.ViewQuery4Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildViewQuery4MetricModel", ctx, start, end, view)
	ret0, _ := ret[0].(interfaces.ViewQuery4Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildViewQuery4MetricModel indicates an expected call of BuildViewQuery4MetricModel.
func (mr *MockDataViewServiceMockRecorder) BuildViewQuery4MetricModel(ctx, start, end, view interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildViewQuery4MetricModel", reflect.TypeOf((*MockDataViewService)(nil).BuildViewQuery4MetricModel), ctx, start, end, view)
}

// CountMultiFields mocks base method.
func (m *MockDataViewService) CountMultiFields(ctx context.Context, viewID string, query *interfaces.DataViewQueryV1, fields []string, sep string) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMultiFields", ctx, viewID, query, fields, sep)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMultiFields indicates an expected call of CountMultiFields.
func (mr *MockDataViewServiceMockRecorder) CountMultiFields(ctx, viewID, query, fields, sep interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMultiFields", reflect.TypeOf((*MockDataViewService)(nil).CountMultiFields), ctx, viewID, query, fields, sep)
}

// DeleteDataViewPits mocks base method.
func (m *MockDataViewService) DeleteDataViewPits(ctx context.Context, pits *interfaces.DeletePits) (*interfaces.DeletePitsResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDataViewPits", ctx, pits)
	ret0, _ := ret[0].(*interfaces.DeletePitsResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDataViewPits indicates an expected call of DeleteDataViewPits.
func (mr *MockDataViewServiceMockRecorder) DeleteDataViewPits(ctx, pits interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDataViewPits", reflect.TypeOf((*MockDataViewService)(nil).DeleteDataViewPits), ctx, pits)
}

// GetDataFromOpenSearch mocks base method.
func (m *MockDataViewService) GetDataFromOpenSearch(ctx context.Context, query map[string]any, indices []string, scroll time.Duration, preference string, trackTotalHits bool) ([]byte, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataFromOpenSearch", ctx, query, indices, scroll, preference, trackTotalHits)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDataFromOpenSearch indicates an expected call of GetDataFromOpenSearch.
func (mr *MockDataViewServiceMockRecorder) GetDataFromOpenSearch(ctx, query, indices, scroll, preference, trackTotalHits interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataFromOpenSearch", reflect.TypeOf((*MockDataViewService)(nil).GetDataFromOpenSearch), ctx, query, indices, scroll, preference, trackTotalHits)
}

// GetDataFromOpenSearchWithBuffer mocks base method.
func (m *MockDataViewService) GetDataFromOpenSearchWithBuffer(ctx context.Context, query bytes.Buffer, indices []string, scroll time.Duration, preference string) ([]byte, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataFromOpenSearchWithBuffer", ctx, query, indices, scroll, preference)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDataFromOpenSearchWithBuffer indicates an expected call of GetDataFromOpenSearchWithBuffer.
func (mr *MockDataViewServiceMockRecorder) GetDataFromOpenSearchWithBuffer(ctx, query, indices, scroll, preference interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataFromOpenSearchWithBuffer", reflect.TypeOf((*MockDataViewService)(nil).GetDataFromOpenSearchWithBuffer), ctx, query, indices, scroll, preference)
}

// GetDataViewByID mocks base method.
func (m *MockDataViewService) GetDataViewByID(ctx context.Context, viewID string, includeDataScopeView bool) (*interfaces.DataView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataViewByID", ctx, viewID, includeDataScopeView)
	ret0, _ := ret[0].(*interfaces.DataView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataViewByID indicates an expected call of GetDataViewByID.
func (mr *MockDataViewServiceMockRecorder) GetDataViewByID(ctx, viewID, includeDataScopeView interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataViewByID", reflect.TypeOf((*MockDataViewService)(nil).GetDataViewByID), ctx, viewID, includeDataScopeView)
}

// GetIndices mocks base method.
func (m *MockDataViewService) GetIndices(ctx context.Context, baseTypes []string, start, end int64) ([]*interfaces.IndexShards, []string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndices", ctx, baseTypes, start, end)
	ret0, _ := ret[0].([]*interfaces.IndexShards)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetIndices indicates an expected call of GetIndices.
func (mr *MockDataViewServiceMockRecorder) GetIndices(ctx, baseTypes, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndices", reflect.TypeOf((*MockDataViewService)(nil).GetIndices), ctx, baseTypes, start, end)
}

// GetSingleViewData mocks base method.
func (m *MockDataViewService) GetSingleViewData(ctx context.Context, viewID string, query interfaces.ViewQueryInterface) (*interfaces.ViewUniResponseV2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSingleViewData", ctx, viewID, query)
	ret0, _ := ret[0].(*interfaces.ViewUniResponseV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSingleViewData indicates an expected call of GetSingleViewData.
func (mr *MockDataViewServiceMockRecorder) GetSingleViewData(ctx, viewID, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSingleViewData", reflect.TypeOf((*MockDataViewService)(nil).GetSingleViewData), ctx, viewID, query)
}

// LoadIndexShards mocks base method.
func (m *MockDataViewService) LoadIndexShards(ctx context.Context, indices string) ([]byte, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadIndexShards", ctx, indices)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LoadIndexShards indicates an expected call of LoadIndexShards.
func (mr *MockDataViewServiceMockRecorder) LoadIndexShards(ctx, indices interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadIndexShards", reflect.TypeOf((*MockDataViewService)(nil).LoadIndexShards), ctx, indices)
}

// RetrieveSingleViewData mocks base method.
func (m *MockDataViewService) RetrieveSingleViewData(ctx context.Context, viewID string, query *interfaces.DataViewQueryV1) (*interfaces.ViewInternalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveSingleViewData", ctx, viewID, query)
	ret0, _ := ret[0].(*interfaces.ViewInternalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveSingleViewData indicates an expected call of RetrieveSingleViewData.
func (mr *MockDataViewServiceMockRecorder) RetrieveSingleViewData(ctx, viewID, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveSingleViewData", reflect.TypeOf((*MockDataViewService)(nil).RetrieveSingleViewData), ctx, viewID, query)
}

// Simulate mocks base method.
func (m *MockDataViewService) Simulate(ctx context.Context, query *interfaces.DataViewSimulateQuery) (*interfaces.ViewUniResponseV2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Simulate", ctx, query)
	ret0, _ := ret[0].(*interfaces.ViewUniResponseV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Simulate indicates an expected call of Simulate.
func (mr *MockDataViewServiceMockRecorder) Simulate(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Simulate", reflect.TypeOf((*MockDataViewService)(nil).Simulate), ctx, query)
}
