// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/data_dict_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "uniquery/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockDataDictService is a mock of DataDictService interface.
type MockDataDictService struct {
	ctrl     *gomock.Controller
	recorder *MockDataDictServiceMockRecorder
}

// MockDataDictServiceMockRecorder is the mock recorder for MockDataDictService.
type MockDataDictServiceMockRecorder struct {
	mock *MockDataDictService
}

// NewMockDataDictService creates a new mock instance.
func NewMockDataDictService(ctrl *gomock.Controller) *MockDataDictService {
	mock := &MockDataDictService{ctrl: ctrl}
	mock.recorder = &MockDataDictServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataDictService) EXPECT() *MockDataDictServiceMockRecorder {
	return m.recorder
}

// LoadDict mocks base method.
func (m *MockDataDictService) LoadDict(ctx context.Context, dictName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadDict", ctx, dictName)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadDict indicates an expected call of LoadDict.
func (mr *MockDataDictServiceMockRecorder) LoadDict(ctx, dictName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadDict", reflect.TypeOf((*MockDataDictService)(nil).LoadDict), ctx, dictName)
}

// UpdateCache mocks base method.
func (m *MockDataDictService) UpdateCache(ctx context.Context, dict interfaces.DataDict) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateCache", ctx, dict)
}

// UpdateCache indicates an expected call of UpdateCache.
func (mr *MockDataDictServiceMockRecorder) UpdateCache(ctx, dict interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCache", reflect.TypeOf((*MockDataDictService)(nil).UpdateCache), ctx, dict)
}
