// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/objective_model_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "uniquery/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockObjectiveModelAccess is a mock of ObjectiveModelAccess interface.
type MockObjectiveModelAccess struct {
	ctrl     *gomock.Controller
	recorder *MockObjectiveModelAccessMockRecorder
}

// MockObjectiveModelAccessMockRecorder is the mock recorder for MockObjectiveModelAccess.
type MockObjectiveModelAccessMockRecorder struct {
	mock *MockObjectiveModelAccess
}

// NewMockObjectiveModelAccess creates a new mock instance.
func NewMockObjectiveModelAccess(ctrl *gomock.Controller) *MockObjectiveModelAccess {
	mock := &MockObjectiveModelAccess{ctrl: ctrl}
	mock.recorder = &MockObjectiveModelAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectiveModelAccess) EXPECT() *MockObjectiveModelAccessMockRecorder {
	return m.recorder
}

// GetObjectiveModel mocks base method.
func (m *MockObjectiveModelAccess) GetObjectiveModel(ctx context.Context, modelId string) (interfaces.ObjectiveModel, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectiveModel", ctx, modelId)
	ret0, _ := ret[0].(interfaces.ObjectiveModel)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetObjectiveModel indicates an expected call of GetObjectiveModel.
func (mr *MockObjectiveModelAccessMockRecorder) GetObjectiveModel(ctx, modelId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectiveModel", reflect.TypeOf((*MockObjectiveModelAccess)(nil).GetObjectiveModel), ctx, modelId)
}
