// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/vega_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "uniquery/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockVegaAccess is a mock of VegaAccess interface.
type MockVegaAccess struct {
	ctrl     *gomock.Controller
	recorder *MockVegaAccessMockRecorder
}

// MockVegaAccessMockRecorder is the mock recorder for MockVegaAccess.
type MockVegaAccessMockRecorder struct {
	mock *MockVegaAccess
}

// NewMockVegaAccess creates a new mock instance.
func NewMockVegaAccess(ctrl *gomock.Controller) *MockVegaAccess {
	mock := &MockVegaAccess{ctrl: ctrl}
	mock.recorder = &MockVegaAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVegaAccess) EXPECT() *MockVegaAccessMockRecorder {
	return m.recorder
}

// FetchDatasFromVega mocks base method.
func (m *MockVegaAccess) FetchDatasFromVega(ctx context.Context, nextUri, sql string) (interfaces.VegaFetchData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDatasFromVega", ctx, nextUri, sql)
	ret0, _ := ret[0].(interfaces.VegaFetchData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDatasFromVega indicates an expected call of FetchDatasFromVega.
func (mr *MockVegaAccessMockRecorder) FetchDatasFromVega(ctx, nextUri, sql interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDatasFromVega", reflect.TypeOf((*MockVegaAccess)(nil).FetchDatasFromVega), ctx, nextUri, sql)
}

// GetVegaViewFieldsByID mocks base method.
func (m *MockVegaAccess) GetVegaViewFieldsByID(ctx context.Context, viewID string) (interfaces.VegaViewWithFields, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVegaViewFieldsByID", ctx, viewID)
	ret0, _ := ret[0].(interfaces.VegaViewWithFields)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVegaViewFieldsByID indicates an expected call of GetVegaViewFieldsByID.
func (mr *MockVegaAccessMockRecorder) GetVegaViewFieldsByID(ctx, viewID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVegaViewFieldsByID", reflect.TypeOf((*MockVegaAccess)(nil).GetVegaViewFieldsByID), ctx, viewID)
}
