// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/promql_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "uniquery/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockPromQLService is a mock of PromQLService interface.
type MockPromQLService struct {
	ctrl     *gomock.Controller
	recorder *MockPromQLServiceMockRecorder
}

// MockPromQLServiceMockRecorder is the mock recorder for MockPromQLService.
type MockPromQLServiceMockRecorder struct {
	mock *MockPromQLService
}

// NewMockPromQLService creates a new mock instance.
func NewMockPromQLService(ctrl *gomock.Controller) *MockPromQLService {
	mock := &MockPromQLService{ctrl: ctrl}
	mock.recorder = &MockPromQLServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromQLService) EXPECT() *MockPromQLServiceMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockPromQLService) Exec(ctx context.Context, query interfaces.Query) (interfaces.PromQLResponse, []byte, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", ctx, query)
	ret0, _ := ret[0].(interfaces.PromQLResponse)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Exec indicates an expected call of Exec.
func (mr *MockPromQLServiceMockRecorder) Exec(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockPromQLService)(nil).Exec), ctx, query)
}

// GetFieldValues mocks base method.
func (m *MockPromQLService) GetFieldValues(ctx context.Context, query interfaces.Query, fieldName string) (map[string]bool, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFieldValues", ctx, query, fieldName)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFieldValues indicates an expected call of GetFieldValues.
func (mr *MockPromQLServiceMockRecorder) GetFieldValues(ctx, query, fieldName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFieldValues", reflect.TypeOf((*MockPromQLService)(nil).GetFieldValues), ctx, query, fieldName)
}

// GetFields mocks base method.
func (m *MockPromQLService) GetFields(ctx context.Context, query interfaces.Query) (map[string]bool, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFields", ctx, query)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFields indicates an expected call of GetFields.
func (mr *MockPromQLServiceMockRecorder) GetFields(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFields", reflect.TypeOf((*MockPromQLService)(nil).GetFields), ctx, query)
}

// GetLabels mocks base method.
func (m *MockPromQLService) GetLabels(ctx context.Context, query interfaces.Query) (map[string]bool, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabels", ctx, query)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLabels indicates an expected call of GetLabels.
func (mr *MockPromQLServiceMockRecorder) GetLabels(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabels", reflect.TypeOf((*MockPromQLService)(nil).GetLabels), ctx, query)
}

// Series mocks base method.
func (m *MockPromQLService) Series(matchers interfaces.Matchers) ([]byte, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Series", matchers)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Series indicates an expected call of Series.
func (mr *MockPromQLServiceMockRecorder) Series(matchers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Series", reflect.TypeOf((*MockPromQLService)(nil).Series), matchers)
}
