// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/kafka_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	reflect "reflect"

	kafka "github.com/confluentinc/confluent-kafka-go/v2/kafka"
	gomock "github.com/golang/mock/gomock"
)

// MockKafkaAccess is a mock of KafkaAccess interface.
type MockKafkaAccess struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaAccessMockRecorder
}

// MockKafkaAccessMockRecorder is the mock recorder for MockKafkaAccess.
type MockKafkaAccessMockRecorder struct {
	mock *MockKafkaAccess
}

// NewMockKafkaAccess creates a new mock instance.
func NewMockKafkaAccess(ctrl *gomock.Controller) *MockKafkaAccess {
	mock := &MockKafkaAccess{ctrl: ctrl}
	mock.recorder = &MockKafkaAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaAccess) EXPECT() *MockKafkaAccessMockRecorder {
	return m.recorder
}

// CommitOffset mocks base method.
func (m *MockKafkaAccess) CommitOffset(consumer *kafka.Consumer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitOffset", consumer)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitOffset indicates an expected call of CommitOffset.
func (mr *MockKafkaAccessMockRecorder) CommitOffset(consumer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitOffset", reflect.TypeOf((*MockKafkaAccess)(nil).CommitOffset), consumer)
}

// CreateTopicIfNotPresent mocks base method.
func (m *MockKafkaAccess) CreateTopicIfNotPresent(topics []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopicIfNotPresent", topics)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTopicIfNotPresent indicates an expected call of CreateTopicIfNotPresent.
func (mr *MockKafkaAccessMockRecorder) CreateTopicIfNotPresent(topics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopicIfNotPresent", reflect.TypeOf((*MockKafkaAccess)(nil).CreateTopicIfNotPresent), topics)
}

// DoProduce mocks base method.
func (m *MockKafkaAccess) DoProduce(p *kafka.Producer, messages []*kafka.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoProduce", p, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoProduce indicates an expected call of DoProduce.
func (mr *MockKafkaAccessMockRecorder) DoProduce(p, messages interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoProduce", reflect.TypeOf((*MockKafkaAccess)(nil).DoProduce), p, messages)
}

// NewKafkaAdminClient mocks base method.
func (m *MockKafkaAccess) NewKafkaAdminClient() (*kafka.AdminClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewKafkaAdminClient")
	ret0, _ := ret[0].(*kafka.AdminClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewKafkaAdminClient indicates an expected call of NewKafkaAdminClient.
func (mr *MockKafkaAccessMockRecorder) NewKafkaAdminClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewKafkaAdminClient", reflect.TypeOf((*MockKafkaAccess)(nil).NewKafkaAdminClient))
}

// NewKafkaConsumer mocks base method.
func (m *MockKafkaAccess) NewKafkaConsumer() (*kafka.Consumer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewKafkaConsumer")
	ret0, _ := ret[0].(*kafka.Consumer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewKafkaConsumer indicates an expected call of NewKafkaConsumer.
func (mr *MockKafkaAccessMockRecorder) NewKafkaConsumer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewKafkaConsumer", reflect.TypeOf((*MockKafkaAccess)(nil).NewKafkaConsumer))
}

// NewTrxProducer mocks base method.
func (m *MockKafkaAccess) NewTrxProducer(uniqId string) (*kafka.Producer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTrxProducer", uniqId)
	ret0, _ := ret[0].(*kafka.Producer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewTrxProducer indicates an expected call of NewTrxProducer.
func (mr *MockKafkaAccessMockRecorder) NewTrxProducer(uniqId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTrxProducer", reflect.TypeOf((*MockKafkaAccess)(nil).NewTrxProducer), uniqId)
}

// PollMessages mocks base method.
func (m *MockKafkaAccess) PollMessages(consumer *kafka.Consumer) ([]*kafka.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollMessages", consumer)
	ret0, _ := ret[0].([]*kafka.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PollMessages indicates an expected call of PollMessages.
func (mr *MockKafkaAccessMockRecorder) PollMessages(consumer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollMessages", reflect.TypeOf((*MockKafkaAccess)(nil).PollMessages), consumer)
}
