// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/data_view_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "uniquery/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockDataViewAccess is a mock of DataViewAccess interface.
type MockDataViewAccess struct {
	ctrl     *gomock.Controller
	recorder *MockDataViewAccessMockRecorder
}

// MockDataViewAccessMockRecorder is the mock recorder for MockDataViewAccess.
type MockDataViewAccessMockRecorder struct {
	mock *MockDataViewAccess
}

// NewMockDataViewAccess creates a new mock instance.
func NewMockDataViewAccess(ctrl *gomock.Controller) *MockDataViewAccess {
	mock := &MockDataViewAccess{ctrl: ctrl}
	mock.recorder = &MockDataViewAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataViewAccess) EXPECT() *MockDataViewAccessMockRecorder {
	return m.recorder
}

// GetDataViewIDByName mocks base method.
func (m *MockDataViewAccess) GetDataViewIDByName(ctx context.Context, viewName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataViewIDByName", ctx, viewName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataViewIDByName indicates an expected call of GetDataViewIDByName.
func (mr *MockDataViewAccessMockRecorder) GetDataViewIDByName(ctx, viewName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataViewIDByName", reflect.TypeOf((*MockDataViewAccess)(nil).GetDataViewIDByName), ctx, viewName)
}

// GetDataViewsByIDs mocks base method.
func (m *MockDataViewAccess) GetDataViewsByIDs(ctx context.Context, ids string, includeDataScopeView bool) ([]*interfaces.DataView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataViewsByIDs", ctx, ids, includeDataScopeView)
	ret0, _ := ret[0].([]*interfaces.DataView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataViewsByIDs indicates an expected call of GetDataViewsByIDs.
func (mr *MockDataViewAccessMockRecorder) GetDataViewsByIDs(ctx, ids, includeDataScopeView interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataViewsByIDs", reflect.TypeOf((*MockDataViewAccess)(nil).GetDataViewsByIDs), ctx, ids, includeDataScopeView)
}
