// tslint:disable
/**
 * 内容自动化
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ExecutorAccessorDto } from './executor-accessor-dto';
import { ExecutorActionDto } from './executor-action-dto';

/**
 * 
 * @export
 * @interface ExecutorDto
 */
export interface ExecutorDto {
    /**
     * 
     * @type {number}
     * @memberof ExecutorDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutorDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutorDto
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ExecutorDto
     */
    status: ExecutorDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ExecutorDto
     */
    created_at?: number;
    /**
     * 
     * @type {number}
     * @memberof ExecutorDto
     */
    updated_at?: number;
    /**
     * 
     * @type {Array<ExecutorAccessorDto>}
     * @memberof ExecutorDto
     */
    accessors?: Array<ExecutorAccessorDto>;
    /**
     * 
     * @type {Array<ExecutorActionDto>}
     * @memberof ExecutorDto
     */
    actions?: Array<ExecutorActionDto>;
}

/**
    * @export
    * @enum {string}
    */
export enum ExecutorDtoStatusEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}



