// tslint:disable
/**
 * 内容自动化
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ExecutorActionInputDto } from './executor-action-input-dto';
import { ExecutorActionOutputDto } from './executor-action-output-dto';

/**
 * 
 * @export
 * @interface ExecutorActionDto
 */
export interface ExecutorActionDto {
    /**
     * 
     * @type {number}
     * @memberof ExecutorActionDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutorActionDto
     */
    name: string;

    operator?: string;
    
    /**
     * 
     * @type {string}
     * @memberof ExecutorActionDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutorActionDto
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutorActionDto
     */
    type: ExecutorActionDtoTypeEnum;
    /**
     * 
     * @type {Array<ExecutorActionInputDto>}
     * @memberof ExecutorActionDto
     */
    inputs?: Array<ExecutorActionInputDto>;
    /**
     * 
     * @type {Array<ExecutorActionOutputDto>}
     * @memberof ExecutorActionDto
     */
    outputs?: Array<ExecutorActionOutputDto>;
    /**
     * 
     * @type {object}
     * @memberof ExecutorActionDto
     */
    config?: object;
    /**
     * 
     * @type {number}
     * @memberof ExecutorActionDto
     */
    created_at?: number;
    /**
     * 
     * @type {number}
     * @memberof ExecutorActionDto
     */
    updated_at?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum ExecutorActionDtoTypeEnum {
    Python = 'python'
}



