// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/resource_data_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockResourceDataService is a mock of ResourceDataService interface.
type MockResourceDataService struct {
	ctrl     *gomock.Controller
	recorder *MockResourceDataServiceMockRecorder
}

// MockResourceDataServiceMockRecorder is the mock recorder for MockResourceDataService.
type MockResourceDataServiceMockRecorder struct {
	mock *MockResourceDataService
}

// NewMockResourceDataService creates a new mock instance.
func NewMockResourceDataService(ctrl *gomock.Controller) *MockResourceDataService {
	mock := &MockResourceDataService{ctrl: ctrl}
	mock.recorder = &MockResourceDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceDataService) EXPECT() *MockResourceDataServiceMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockResourceDataService) Query(ctx context.Context, resource *interfaces.Resource, params *interfaces.ResourceDataQueryParams) ([]map[string]any, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, resource, params)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Query indicates an expected call of Query.
func (mr *MockResourceDataServiceMockRecorder) Query(ctx, resource, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockResourceDataService)(nil).Query), ctx, resource, params)
}
