// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/connector_type_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockConnectorTypeService is a mock of ConnectorTypeService interface.
type MockConnectorTypeService struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorTypeServiceMockRecorder
}

// MockConnectorTypeServiceMockRecorder is the mock recorder for MockConnectorTypeService.
type MockConnectorTypeServiceMockRecorder struct {
	mock *MockConnectorTypeService
}

// NewMockConnectorTypeService creates a new mock instance.
func NewMockConnectorTypeService(ctrl *gomock.Controller) *MockConnectorTypeService {
	mock := &MockConnectorTypeService{ctrl: ctrl}
	mock.recorder = &MockConnectorTypeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectorTypeService) EXPECT() *MockConnectorTypeServiceMockRecorder {
	return m.recorder
}

// CheckExistByName mocks base method.
func (m *MockConnectorTypeService) CheckExistByName(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistByName", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistByName indicates an expected call of CheckExistByName.
func (mr *MockConnectorTypeServiceMockRecorder) CheckExistByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistByName", reflect.TypeOf((*MockConnectorTypeService)(nil).CheckExistByName), ctx, name)
}

// CheckExistByType mocks base method.
func (m *MockConnectorTypeService) CheckExistByType(ctx context.Context, tp string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistByType", ctx, tp)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistByType indicates an expected call of CheckExistByType.
func (mr *MockConnectorTypeServiceMockRecorder) CheckExistByType(ctx, tp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistByType", reflect.TypeOf((*MockConnectorTypeService)(nil).CheckExistByType), ctx, tp)
}

// DeleteByType mocks base method.
func (m *MockConnectorTypeService) DeleteByType(ctx context.Context, tp string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByType", ctx, tp)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByType indicates an expected call of DeleteByType.
func (mr *MockConnectorTypeServiceMockRecorder) DeleteByType(ctx, tp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByType", reflect.TypeOf((*MockConnectorTypeService)(nil).DeleteByType), ctx, tp)
}

// GetByType mocks base method.
func (m *MockConnectorTypeService) GetByType(ctx context.Context, tp string) (*interfaces.ConnectorType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByType", ctx, tp)
	ret0, _ := ret[0].(*interfaces.ConnectorType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByType indicates an expected call of GetByType.
func (mr *MockConnectorTypeServiceMockRecorder) GetByType(ctx, tp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByType", reflect.TypeOf((*MockConnectorTypeService)(nil).GetByType), ctx, tp)
}

// List mocks base method.
func (m *MockConnectorTypeService) List(ctx context.Context, params interfaces.ConnectorTypesQueryParams) ([]*interfaces.ConnectorType, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.ConnectorType)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockConnectorTypeServiceMockRecorder) List(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConnectorTypeService)(nil).List), ctx, params)
}

// Register mocks base method.
func (m *MockConnectorTypeService) Register(ctx context.Context, ct *interfaces.ConnectorTypeReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, ct)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockConnectorTypeServiceMockRecorder) Register(ctx, ct interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockConnectorTypeService)(nil).Register), ctx, ct)
}

// SetEnabled mocks base method.
func (m *MockConnectorTypeService) SetEnabled(ctx context.Context, tp string, enabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEnabled", ctx, tp, enabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEnabled indicates an expected call of SetEnabled.
func (mr *MockConnectorTypeServiceMockRecorder) SetEnabled(ctx, tp, enabled interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnabled", reflect.TypeOf((*MockConnectorTypeService)(nil).SetEnabled), ctx, tp, enabled)
}

// Update mocks base method.
func (m *MockConnectorTypeService) Update(ctx context.Context, ct *interfaces.ConnectorTypeReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, ct)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockConnectorTypeServiceMockRecorder) Update(ctx, ct interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConnectorTypeService)(nil).Update), ctx, ct)
}
