// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/connector_type_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"
	interfaces "vega-backend/interfaces"

	gomock "github.com/golang/mock/gomock"
)

// MockConnectorTypeAccess is a mock of ConnectorTypeAccess interface.
type MockConnectorTypeAccess struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorTypeAccessMockRecorder
}

// MockConnectorTypeAccessMockRecorder is the mock recorder for MockConnectorTypeAccess.
type MockConnectorTypeAccessMockRecorder struct {
	mock *MockConnectorTypeAccess
}

// NewMockConnectorTypeAccess creates a new mock instance.
func NewMockConnectorTypeAccess(ctrl *gomock.Controller) *MockConnectorTypeAccess {
	mock := &MockConnectorTypeAccess{ctrl: ctrl}
	mock.recorder = &MockConnectorTypeAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectorTypeAccess) EXPECT() *MockConnectorTypeAccessMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockConnectorTypeAccess) Create(ctx context.Context, ct *interfaces.ConnectorType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ct)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockConnectorTypeAccessMockRecorder) Create(ctx, ct interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConnectorTypeAccess)(nil).Create), ctx, ct)
}

// DeleteByType mocks base method.
func (m *MockConnectorTypeAccess) DeleteByType(ctx context.Context, tp string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByType", ctx, tp)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByType indicates an expected call of DeleteByType.
func (mr *MockConnectorTypeAccessMockRecorder) DeleteByType(ctx, tp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByType", reflect.TypeOf((*MockConnectorTypeAccess)(nil).DeleteByType), ctx, tp)
}

// GetByName mocks base method.
func (m *MockConnectorTypeAccess) GetByName(ctx context.Context, name string) (*interfaces.ConnectorType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*interfaces.ConnectorType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockConnectorTypeAccessMockRecorder) GetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockConnectorTypeAccess)(nil).GetByName), ctx, name)
}

// GetByType mocks base method.
func (m *MockConnectorTypeAccess) GetByType(ctx context.Context, tp string) (*interfaces.ConnectorType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByType", ctx, tp)
	ret0, _ := ret[0].(*interfaces.ConnectorType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByType indicates an expected call of GetByType.
func (mr *MockConnectorTypeAccessMockRecorder) GetByType(ctx, tp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByType", reflect.TypeOf((*MockConnectorTypeAccess)(nil).GetByType), ctx, tp)
}

// List mocks base method.
func (m *MockConnectorTypeAccess) List(ctx context.Context, params interfaces.ConnectorTypesQueryParams) ([]*interfaces.ConnectorType, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*interfaces.ConnectorType)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockConnectorTypeAccessMockRecorder) List(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConnectorTypeAccess)(nil).List), ctx, params)
}

// SetEnabled mocks base method.
func (m *MockConnectorTypeAccess) SetEnabled(ctx context.Context, tp string, enabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEnabled", ctx, tp, enabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEnabled indicates an expected call of SetEnabled.
func (mr *MockConnectorTypeAccessMockRecorder) SetEnabled(ctx, tp, enabled interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnabled", reflect.TypeOf((*MockConnectorTypeAccess)(nil).SetEnabled), ctx, tp, enabled)
}

// Update mocks base method.
func (m *MockConnectorTypeAccess) Update(ctx context.Context, ct *interfaces.ConnectorType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, ct)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockConnectorTypeAccessMockRecorder) Update(ctx, ct interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConnectorTypeAccess)(nil).Update), ctx, ct)
}
