// Code generated by MockGen. DO NOT EDIT.
// Source: driven_ontology_query.go
//
// Generated by this command:
//
//	mockgen -source=driven_ontology_query.go -destination=../mocks/driven_ontology_query.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	interfaces "github.com/kweaver-ai/adp/context-loader/agent-retrieval/server/interfaces"
)

// MockDrivenOntologyQuery is a mock of DrivenOntologyQuery interface.
type MockDrivenOntologyQuery struct {
	ctrl     *gomock.Controller
	recorder *MockDrivenOntologyQueryMockRecorder
	isgomock struct{}
}

// MockDrivenOntologyQueryMockRecorder is the mock recorder for MockDrivenOntologyQuery.
type MockDrivenOntologyQueryMockRecorder struct {
	mock *MockDrivenOntologyQuery
}

// NewMockDrivenOntologyQuery creates a new mock instance.
func NewMockDrivenOntologyQuery(ctrl *gomock.Controller) *MockDrivenOntologyQuery {
	mock := &MockDrivenOntologyQuery{ctrl: ctrl}
	mock.recorder = &MockDrivenOntologyQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDrivenOntologyQuery) EXPECT() *MockDrivenOntologyQueryMockRecorder {
	return m.recorder
}

// QueryActions mocks base method.
func (m *MockDrivenOntologyQuery) QueryActions(ctx context.Context, req *interfaces.QueryActionsRequest) (*interfaces.QueryActionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryActions", ctx, req)
	ret0, _ := ret[0].(*interfaces.QueryActionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryActions indicates an expected call of QueryActions.
func (mr *MockDrivenOntologyQueryMockRecorder) QueryActions(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryActions", reflect.TypeOf((*MockDrivenOntologyQuery)(nil).QueryActions), ctx, req)
}

// QueryInstanceSubgraph mocks base method.
func (m *MockDrivenOntologyQuery) QueryInstanceSubgraph(ctx context.Context, req *interfaces.QueryInstanceSubgraphReq) (*interfaces.QueryInstanceSubgraphResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryInstanceSubgraph", ctx, req)
	ret0, _ := ret[0].(*interfaces.QueryInstanceSubgraphResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryInstanceSubgraph indicates an expected call of QueryInstanceSubgraph.
func (mr *MockDrivenOntologyQueryMockRecorder) QueryInstanceSubgraph(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryInstanceSubgraph", reflect.TypeOf((*MockDrivenOntologyQuery)(nil).QueryInstanceSubgraph), ctx, req)
}

// QueryLogicProperties mocks base method.
func (m *MockDrivenOntologyQuery) QueryLogicProperties(ctx context.Context, req *interfaces.QueryLogicPropertiesReq) (*interfaces.QueryLogicPropertiesResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryLogicProperties", ctx, req)
	ret0, _ := ret[0].(*interfaces.QueryLogicPropertiesResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryLogicProperties indicates an expected call of QueryLogicProperties.
func (mr *MockDrivenOntologyQueryMockRecorder) QueryLogicProperties(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryLogicProperties", reflect.TypeOf((*MockDrivenOntologyQuery)(nil).QueryLogicProperties), ctx, req)
}

// QueryObjectInstances mocks base method.
func (m *MockDrivenOntologyQuery) QueryObjectInstances(ctx context.Context, req *interfaces.QueryObjectInstancesReq) (*interfaces.QueryObjectInstancesResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryObjectInstances", ctx, req)
	ret0, _ := ret[0].(*interfaces.QueryObjectInstancesResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryObjectInstances indicates an expected call of QueryObjectInstances.
func (mr *MockDrivenOntologyQueryMockRecorder) QueryObjectInstances(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryObjectInstances", reflect.TypeOf((*MockDrivenOntologyQuery)(nil).QueryObjectInstances), ctx, req)
}
