// Code generated by MockGen. DO NOT EDIT.
// Source: drivenadapters.go
//
// Generated by this command:
//
//	mockgen -source=drivenadapters.go -destination=../mocks/drivenadapters.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "devops.aishu.cn/AISHUDevOps/DIP/_git/agent-retrieval/server/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockHydra is a mock of Hydra interface.
type MockHydra struct {
	ctrl     *gomock.Controller
	recorder *MockHydraMockRecorder
	isgomock struct{}
}

// MockHydraMockRecorder is the mock recorder for MockHydra.
type MockHydraMockRecorder struct {
	mock *MockHydra
}

// NewMockHydra creates a new mock instance.
func NewMockHydra(ctrl *gomock.Controller) *MockHydra {
	mock := &MockHydra{ctrl: ctrl}
	mock.recorder = &MockHydraMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHydra) EXPECT() *MockHydraMockRecorder {
	return m.recorder
}

// Introspect mocks base method.
func (m *MockHydra) Introspect(ctx context.Context, token string) (*interfaces.TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Introspect", ctx, token)
	ret0, _ := ret[0].(*interfaces.TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Introspect indicates an expected call of Introspect.
func (mr *MockHydraMockRecorder) Introspect(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Introspect", reflect.TypeOf((*MockHydra)(nil).Introspect), ctx, token)
}

// MockUserManagement is a mock of UserManagement interface.
type MockUserManagement struct {
	ctrl     *gomock.Controller
	recorder *MockUserManagementMockRecorder
	isgomock struct{}
}

// MockUserManagementMockRecorder is the mock recorder for MockUserManagement.
type MockUserManagementMockRecorder struct {
	mock *MockUserManagement
}

// NewMockUserManagement creates a new mock instance.
func NewMockUserManagement(ctrl *gomock.Controller) *MockUserManagement {
	mock := &MockUserManagement{ctrl: ctrl}
	mock.recorder = &MockUserManagementMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserManagement) EXPECT() *MockUserManagementMockRecorder {
	return m.recorder
}

// GetUsersInfo mocks base method.
func (m *MockUserManagement) GetUsersInfo(ctx context.Context, userIDs, fields []string) ([]*interfaces.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersInfo", ctx, userIDs, fields)
	ret0, _ := ret[0].([]*interfaces.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersInfo indicates an expected call of GetUsersInfo.
func (mr *MockUserManagementMockRecorder) GetUsersInfo(ctx, userIDs, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersInfo", reflect.TypeOf((*MockUserManagement)(nil).GetUsersInfo), ctx, userIDs, fields)
}
