// Code generated by MockGen. DO NOT EDIT.
// Source: tx.go
//
// Generated by this command:
//
//	mockgen -source=tx.go -destination=../../mocks/model_tx.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDBTx is a mock of DBTx interface.
type MockDBTx struct {
	ctrl     *gomock.Controller
	recorder *MockDBTxMockRecorder
	isgomock struct{}
}

// MockDBTxMockRecorder is the mock recorder for MockDBTx.
type MockDBTxMockRecorder struct {
	mock *MockDBTx
}

// NewMockDBTx creates a new mock instance.
func NewMockDBTx(ctrl *gomock.Controller) *MockDBTx {
	mock := &MockDBTx{ctrl: ctrl}
	mock.recorder = &MockDBTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBTx) EXPECT() *MockDBTxMockRecorder {
	return m.recorder
}

// GetTx mocks base method.
func (m *MockDBTx) GetTx(ctx context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTx", ctx)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTx indicates an expected call of GetTx.
func (mr *MockDBTxMockRecorder) GetTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTx", reflect.TypeOf((*MockDBTx)(nil).GetTx), ctx)
}
