// Code generated by MockGen. DO NOT EDIT.
// Source: driveradapters.go
//
// Generated by this command:
//
//	mockgen -source=driveradapters.go -destination=../mocks/driveradapters.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockHTTPRouterInterface is a mock of HTTPRouterInterface interface.
type MockHTTPRouterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPRouterInterfaceMockRecorder
	isgomock struct{}
}

// MockHTTPRouterInterfaceMockRecorder is the mock recorder for MockHTTPRouterInterface.
type MockHTTPRouterInterfaceMockRecorder struct {
	mock *MockHTTPRouterInterface
}

// NewMockHTTPRouterInterface creates a new mock instance.
func NewMockHTTPRouterInterface(ctrl *gomock.Controller) *MockHTTPRouterInterface {
	mock := &MockHTTPRouterInterface{ctrl: ctrl}
	mock.recorder = &MockHTTPRouterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPRouterInterface) EXPECT() *MockHTTPRouterInterfaceMockRecorder {
	return m.recorder
}

// RegisterRouter mocks base method.
func (m *MockHTTPRouterInterface) RegisterRouter(engine *gin.RouterGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterRouter", engine)
}

// RegisterRouter indicates an expected call of RegisterRouter.
func (mr *MockHTTPRouterInterfaceMockRecorder) RegisterRouter(engine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRouter", reflect.TypeOf((*MockHTTPRouterInterface)(nil).RegisterRouter), engine)
}
