openapi: 3.0.2
info:
  title: 行动召回接口
  version: 1.0.0
  description: 根据对象实例标识召回关联行动，返回符合 Function Call 规范的工具定义。当前仅支持单个对象、type=tool。

servers:
  - url: http://agent-retrieval:30779
    description: 行动召回服务

tags:
  - name: action-recall
    description: 行动召回相关接口

paths:
  /api/agent-retrieval/in/v1/kn/get_action_info:
    post:
      summary: get_action_info
      description: 根据对象实例标识召回关联行动，返回 _dynamic_tools。
      operationId: getActionInfo
      tags:
        - action-recall
      parameters:
        - name: x-account-id
          in: header
          description: 账户 ID
          required: true
          schema:
            type: string
          example: bdb78b62-6c48-11f0-af96-fa8dcc0a06b2
        - name: x-account-type
          in: header
          description: 账户类型
          required: true
          schema:
            type: string
            enum:
              - user
              - system
          example: user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActionRecallRequest'
            examples:
              disease_example:
                summary: 疾病对象示例
                value:
                  kn_id: kn_medical
                  at_id: generate_treatment_plan
                  _instance_identity:
                    disease_id: disease_000001
      responses:
        '200':
          description: 成功返回动态工具列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionRecallResponse'
              examples:
                成功:
                  value:
                    _dynamic_tools:
                      - name: 工具名
                        description: 工具描述
                        parameters: {}
                        api_url: http://...
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalid_request:
                  value:
                    code: INVALID_REQUEST
                    description: _instance_identity 格式错误
        '500':
          description: 服务器内部错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '502':
          description: 上游服务不可用
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ActionRecallRequest:
      type: object
      required:
        - kn_id
        - at_id
        - _instance_identity
      properties:
        kn_id:
          type: string
          description: 知识网络ID
        at_id:
          type: string
          description: 行动类ID（从 Schema 获取）
        _instance_identity:
          type: object
          description: 对象实例标识（主键键值对）。**必须从 query_object_instance 或 query_instance_subgraph 返回的 _instance_identity 字段提取，不可臆造。** 当前仅支持单个对象。
          additionalProperties:
            oneOf:
              - type: string
              - type: number
              - type: boolean
              - type: integer
          example:
            disease_id: disease_000001
          minProperties: 1

    ActionRecallResponse:
      type: object
      required:
        - _dynamic_tools
      properties:
        headers:
          type: object
          additionalProperties: true
        _dynamic_tools:
          type: array
          description: Function Call 格式的工具列表
          items:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              parameters:
                type: object
              api_url:
                type: string
              fixed_params:
                type: object

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        description:
          type: string

  securitySchemes:
    AccountAuth:
      type: apiKey
      in: header
      name: x-account-id
      description: 账户 ID 认证

security:
  - AccountAuth: []

