// tslint:disable
/**
 * automation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as globalImportUrl from "url";
import { Configuration } from "./configuration";
import globalAxios, { AxiosPromise, AxiosInstance } from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
    BASE_PATH,
    COLLECTION_FORMATS,
    RequestArgs,
    BaseAPI,
    RequiredError,
} from "./base";

/**
 * 自动化任务分支定义参数
 * @export
 * @interface Branch
 */
export interface Branch {
    /**
     * 节点id，唯一标识
     * @type {string}
     * @memberof Branch
     */
    id: string;
    /**
     * 分支判断条件配置
     * @type {Array<Array<object>>}
     * @memberof Branch
     */
    conditions: Array<Array<object>>;
    /**
     * 分支下的节点 同外层steps结构一致
     * @type {Array<Step>}
     * @memberof Branch
     */
    steps?: Array<Step>;
}
/**
 *
 * @export
 * @interface DaGs
 */
export interface DaGs {
    /**
     * 任务列表
     * @type {Array<DaGsDags>}
     * @memberof DaGs
     */
    dags?: Array<DaGsDags>;
    /**
     * 页码
     * @type {number}
     * @memberof DaGs
     */
    page?: number;
    /**
     * 每页显示数目，-1 取消分页
     * @type {number}
     * @memberof DaGs
     */
    limit?: number;
    /**
     * 任务总数
     * @type {number}
     * @memberof DaGs
     */
    total?: number;
}
/**
 *
 * @export
 * @interface DaGsDags
 */
export interface DaGsDags {
    /**
     * 任务id
     * @type {string}
     * @memberof DaGsDags
     */
    id?: string;
    /**
     * 任务名称
     * @type {string}
     * @memberof DaGsDags
     */
    title?: string;
    /**
     * 任务包含的动作
     * @type {Array<string>}
     * @memberof DaGsDags
     */
    actions?: Array<string>;
    /**
     * 创建时间
     * @type {number}
     * @memberof DaGsDags
     */
    created_at?: number;
    /**
     * 更新时间降序排列
     * @type {number}
     * @memberof DaGsDags
     */
    updated_at?: number;
    /**
     * 任务状态  - normal: 启用中   - stopped: 已停用
     * @type {string}
     * @memberof DaGsDags
     */
    status?: string;
}
/**
 * 自动化任务配置参数
 * @export
 * @interface Dag
 */
export interface Dag {
    /**
     * 任务名称,不能包含 / : * ? \" < > | 特殊字符，长度不能超过128个字符
     * @type {string}
     * @memberof Dag
     */
    title: string;
    /**
     * 详情描述,不允许换行输入,不允许超过300个字符
     * @type {string}
     * @memberof Dag
     */
    description?: string;
    /**
     * 任务状态,默认启用  - normal: 启用中   - stopped: 已停用
     * @type {string}
     * @memberof Dag
     */
    status?: string;
    /**
     * 自动化流程定义
     * @type {Array<Step>}
     * @memberof Dag
     */
    steps: Array<Step>;

    [key: string]: any;
}
/**
 *
 * @export
 * @interface DagDetail
 */
export interface DagDetail {
    /**
     * 节点运行id
     * @type {string}
     * @memberof DagDetail
     */
    id?: string;
    /**
     * 任务创建时间
     * @type {number}
     * @memberof DagDetail
     */
    created_at?: number;
    /**
     * 任务更新时间
     * @type {number}
     * @memberof DagDetail
     */
    updated_at?: number;
    /**
     * 任务名称,不能包含 / : * ? \" < > | 特殊字符，长度不能超过128个字符
     * @type {string}
     * @memberof DagDetail
     */
    title: string;
    /**
     * 详情描述,不允许换行输入,不允许超过300个字符
     * @type {string}
     * @memberof DagDetail
     */
    description?: string;
    /**
     * 任务状态,默认启用  - normal: 启用中   - stopped: 已停用
     * @type {string}
     * @memberof DagDetail
     */
    status?: string;
    /**
     * 自动化流程定义
     * @type {Array<Step>}
     * @memberof DagDetail
     */
    steps: Array<Step>;
}
/**
 * 自动化任务分支条件定义参数
 * @export
 * @interface DagDetailAllOf
 */
export interface DagDetailAllOf {
    /**
     * 节点运行id
     * @type {string}
     * @memberof DagDetailAllOf
     */
    id?: string;
    /**
     * 任务创建时间
     * @type {number}
     * @memberof DagDetailAllOf
     */
    created_at?: number;
    /**
     * 任务更新时间
     * @type {number}
     * @memberof DagDetailAllOf
     */
    updated_at?: number;
}
/**
 *
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 任务状态  - canceled: 取消
     * @type {string}
     * @memberof InlineObject
     */
    status: string;
}
/**
 *
 * @export
 * @interface InlineResponse201
 */
export interface InlineResponse201 {
    /**
     *
     * @type {string}
     * @memberof InlineResponse201
     */
    id?: string;
}
/**
 * 接口调用错误信息结构基类
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 错误码
     * @type {string}
     * @memberof ModelError
     */
    code: string;
    /**
     * 错误描述
     * @type {string}
     * @memberof ModelError
     */
    description: string;
    /**
     * 错误处理
     * @type {string}
     * @memberof ModelError
     */
    solution: string;
    /**
     * 错误细节
     * @type {object}
     * @memberof ModelError
     */
    detail?: object;
}
/**
 *
 * @export
 * @interface Progress
 */
export interface Progress {
    /**
     * 总任务数
     * @type {number}
     * @memberof Progress
     */
    total?: number;
    /**
     * 运行成功数
     * @type {number}
     * @memberof Progress
     */
    success?: number;
    /**
     * 运行失败数
     * @type {number}
     * @memberof Progress
     */
    failed?: number;
}
/**
 * 自动化任务步骤定义参数
 * @export
 * @interface Step
 */
export interface Step {
    /**
     * 节点id，唯一标识
     * @type {string}
     * @memberof Step
     */
    id: string;
    /**
     * 节点名称
     * @type {string}
     * @memberof Step
     */
    title: string;
    /**
     * 节点函数
     * @type {string}
     * @memberof Step
     */
    operator: string;
    /**
     * 节点参数,用户可自定格式为`key:value`任意类型参数
     * @type {object}
     * @memberof Step
     */
    parameters?: object;
    /**
     * 分支节点
     * @type {Array<Branch>}
     * @memberof Step
     */
    branches?: Array<Branch>;

    steps?: Step[];

    dataSource?: Step;
}
/**
 * 建议的名称，若传入的名称不存在则使用上传的名称，若存在则根据重名策略生成可用名称
 * @export
 * @interface SuggestName
 */
export interface SuggestName {
    /**
     *
     * @type {string}
     * @memberof SuggestName
     */
    name: string;
}

/**
 * 节点日志详情
 * @export
 * @interface LogResult
 */
export interface LogResult {
    id: string;
    operator: string;
    started_at: number;
    status: string;
    inputs: any;
    outputs: any;
    name?: string;
    metadata?: any;
}

/**
 * 任务运行结果
 * @export
 * @interface TaskResult
 */
export interface TaskResult {
    /**
     * 运行结果
     * @type {Array<TaskResultResults>}
     * @memberof TaskResult
     */
    results?: Array<TaskResultResults>;
    /**
     *
     * @type {Progress}
     * @memberof TaskResult
     */
    progress?: Progress;
    /**
     * 页码
     * @type {number}
     * @memberof TaskResult
     */
    page?: number;
    /**
     * 每页显示数目，-1 取消分页
     * @type {number}
     * @memberof TaskResult
     */
    limit?: number;
    /**
     * 任务总数
     * @type {number}
     * @memberof TaskResult
     */
    total?: number;
}
/**
 *
 * @export
 * @interface TaskResultResults
 */
export interface TaskResultResults {
    /**
     * 节点运行id
     * @type {string}
     * @memberof TaskResultResults
     */
    id?: string;
    /**
     * 节点运行状态  - success: 运行成功  - failed: 运行失败  - canceled: 运行取消  - running: 运行中  - scheduled:等待中
     * @type {string}
     * @memberof TaskResultResults
     */
    status?: string;
    /**
     * 任务开始时间
     * @type {number}
     * @memberof TaskResultResults
     */
    started_at?: number;
    /**
     * 任务结束时间
     * @type {number}
     * @memberof TaskResultResults
     */
    ended_at?: number;
}
/**
 * 自动化任务配置参数
 * @export
 * @interface UpdateDag
 */
export interface UpdateDag {
    /**
     * 任务名称,不能包含 / : * ? \" < > | 特殊字符，长度不能超过128个字符
     * @type {string}
     * @memberof UpdateDag
     */
    title?: string;
    /**
     * 详情描述,不允许换行输入,不允许超过300个字符
     * @type {string}
     * @memberof UpdateDag
     */
    description?: string;
    /**
     * 任务状态,默认启用  - normal: 启用中   - stopped: 已停用
     * @type {string}
     * @memberof UpdateDag
     */
    status?: string;
    /**
     * 自动化流程定义
     * @type {Array<Step>}
     * @memberof UpdateDag
     */
    steps?: Array<Step>;

    [key: string]: any
}

export interface CreateAlertParams {
    /**
     * 告警接收人列表
     */
    alert_users: Array<{
        /**
         * 用户ID
         */
        id: string;
        /**
         * 用户类型
         */
        type: string;
    }>;
    /**
     * 任务ID列表
     */
    dag_ids: string[];
    /**
     * 告警频率（小时）
     */
    frequency: number;
    /**
     * 告警阈值
     */
    threshold: number;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (
    configuration?: Configuration
) {
    return {
        /**
         * 删除任务
         * @summary /dag/{dagId}
         * @param {string} dagId 任务ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagDagIdDelete: async (
            dagId: string,
            options: any = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'dagId' is not null or undefined
            if (dagId === null || dagId === undefined) {
                throw new RequiredError(
                    "dagId",
                    "Required parameter dagId was null or undefined when calling dagDagIdDelete."
                );
            }
            const localVarPath = `/dag/{dagId}`.replace(
                `{${"dagId"}}`,
                encodeURIComponent(String(dagId))
            );
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = {
                method: "DELETE",
                ...baseOptions,
                ...options,
            };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = {
                ...localVarUrlObj.query,
                ...localVarQueryParameter,
                ...options.query,
            };
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 获取任务详情
         * @summary /dag/{dagId}
         * @param {string} dagId 任务ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagDagIdGet: async (
            dagId: string,
            options: any = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'dagId' is not null or undefined
            if (dagId === null || dagId === undefined) {
                throw new RequiredError(
                    "dagId",
                    "Required parameter dagId was null or undefined when calling dagDagIdGet."
                );
            }
            const localVarPath = `/dag/{dagId}`.replace(
                `{${"dagId"}}`,
                encodeURIComponent(String(dagId))
            );
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = {
                method: "GET",
                ...baseOptions,
                ...options,
            };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = {
                ...localVarUrlObj.query,
                ...localVarQueryParameter,
                ...options.query,
            };
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 更新任务
         * @summary /dag/{dagId}
         * @param {string} dagId 任务ID
         * @param {UpdateDag} [updateDag]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagDagIdPut: async (
            dagId: string,
            updateDag?: UpdateDag,
            options: any = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'dagId' is not null or undefined
            if (dagId === null || dagId === undefined) {
                throw new RequiredError(
                    "dagId",
                    "Required parameter dagId was null or undefined when calling dagDagIdPut."
                );
            }
            const localVarPath = `/dag/{dagId}`.replace(
                `{${"dagId"}}`,
                encodeURIComponent(String(dagId))
            );
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = {
                method: "PUT",
                ...baseOptions,
                ...options,
            };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter["Content-Type"] = "application/json";

            localVarUrlObj.query = {
                ...localVarUrlObj.query,
                ...localVarQueryParameter,
                ...options.query,
            };
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };
            const needsSerialization =
                typeof updateDag !== "string" ||
                localVarRequestOptions.headers["Content-Type"] ===
                "application/json";
            localVarRequestOptions.data = needsSerialization
                ? JSON.stringify(updateDag !== undefined ? updateDag : {})
                : updateDag || "";

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 任务运行详情
         * @summary /dag/{dagId}/result/{resultId}
         * @param {string} dagId 任务ID
         * @param {string} resultId 任务运行结果ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagDagIdResultResultIdGet: async (
            dagId: string,
            resultId: string,
            options: any = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'dagId' is not null or undefined
            if (dagId === null || dagId === undefined) {
                throw new RequiredError(
                    "dagId",
                    "Required parameter dagId was null or undefined when calling dagDagIdResultResultIdGet."
                );
            }
            // verify required parameter 'resultId' is not null or undefined
            if (resultId === null || resultId === undefined) {
                throw new RequiredError(
                    "resultId",
                    "Required parameter resultId was null or undefined when calling dagDagIdResultResultIdGet."
                );
            }
            const localVarPath = `/dag/{dagId}/result/{resultId}`
                .replace(`{${"dagId"}}`, encodeURIComponent(String(dagId)))
                .replace(
                    `{${"resultId"}}`,
                    encodeURIComponent(String(resultId))
                );
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = {
                method: "GET",
                ...baseOptions,
                ...options,
            };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = {
                ...localVarUrlObj.query,
                ...localVarQueryParameter,
                ...options.query,
            };
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 任务运行统计
         * @summary /dag/{dagId}/results
         * @param {string} dagId 任务ID
         * @param {string} [type] 节点运行状态  - success: 运行成功  - failed: 运行失败  - canceled: 运行取消  - running: 运行中  - scheduled:等待中
         * @param {number} [page] 页码，默认值为0
         * @param {string} [limit] 每页显示条目数，默认值为20，有效值在1-100之间，-1 取消分页
         * @param {string} [sortby] 排序字段，默认为started_at,仅支持started_at
         * @param {string} [order] 排序规则。默认为desc，仅支持desc和asc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagDagIdResultsGet: async (
            dagId: string,
            type?: string,
            page?: number,
            limit?: string,
            sortby?: string,
            order?: string,
            options: any = {},

        ): Promise<RequestArgs> => {
            // verify required parameter 'dagId' is not null or undefined
            if (dagId === null || dagId === undefined) {
                throw new RequiredError(
                    "dagId",
                    "Required parameter dagId was null or undefined when calling dagDagIdResultsGet."
                );
            }
            const localVarPath = `/dag/{dagId}/results`.replace(
                `{${"dagId"}}`,
                encodeURIComponent(String(dagId))
            );
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = {
                method: "GET",
                ...baseOptions,
                ...options,
            };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (type !== undefined) {
                localVarQueryParameter["type"] = type;
            }

            if (page !== undefined) {
                localVarQueryParameter["page"] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter["limit"] = limit;
            }

            if (sortby !== undefined) {
                localVarQueryParameter["sortby"] = sortby;
            }

            if (order !== undefined) {
                localVarQueryParameter["order"] = order;
            }

            localVarUrlObj.query = {
                ...localVarUrlObj.query,
                ...localVarQueryParameter,
                ...options.query,
            };
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 创建任务
         * @summary /dag
         * @param {Dag} [dag]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagPost: async (dag?: Dag, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/dag`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = {
                method: "POST",
                ...baseOptions,
                ...options,
            };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter["Content-Type"] = "application/json";

            localVarUrlObj.query = {
                ...localVarUrlObj.query,
                ...localVarQueryParameter,
                ...options.query,
            };
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };
            const needsSerialization =
                typeof dag !== "string" ||
                localVarRequestOptions.headers["Content-Type"] ===
                "application/json";
            localVarRequestOptions.data = needsSerialization
                ? JSON.stringify(dag !== undefined ? dag : {})
                : dag || "";

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 获取创建任务的建议名称
         * @summary /dag/suggestname/{name}
         * @param {string} name 建议名称公共前缀,不能包含 / : * ? \&quot; &lt; &gt; | 特殊字符
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagSuggestnameNameGet: async (
            name: string,
            options: any = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            if (name === null || name === undefined) {
                throw new RequiredError(
                    "name",
                    "Required parameter name was null or undefined when calling dagSuggestnameNameGet."
                );
            }
            const localVarPath = `/dag/suggestname/{name}`.replace(
                `{${"name"}}`,
                encodeURIComponent(String(name))
            );
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = {
                method: "GET",
                ...baseOptions,
                ...options,
            };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = {
                ...localVarUrlObj.query,
                ...localVarQueryParameter,
                ...options.query,
            };
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 列举任务
         * @summary /dags
         * @param {string} [keyword] 关键字，用于搜索筛选任务名称
         * @param {number} [page] 页码，默认值为0
         * @param {string} [limit] 每页显示条目数，默认值为20，有效值在1-100之间，-1 取消分页
         * @param {string} [sortby] 排序字段，默认为updated_at,仅支持name、created_at和updated_at
         * @param {string} [order] 排序规则。默认为desc，仅支持desc和asc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagsGet: async (
            keyword?: string,
            page?: number,
            limit?: string,
            sortby?: string,
            order?: string,
            options: any = {}
        ): Promise<RequestArgs> => {
            const localVarPath = `/dags`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = {
                method: "GET",
                ...baseOptions,
                ...options,
            };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (keyword !== undefined) {
                localVarQueryParameter["keyword"] = keyword;
            }

            if (page !== undefined) {
                localVarQueryParameter["page"] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter["limit"] = limit;
            }

            if (sortby !== undefined) {
                localVarQueryParameter["sortby"] = sortby;
            }

            if (order !== undefined) {
                localVarQueryParameter["order"] = order;
            }

            localVarUrlObj.query = {
                ...localVarUrlObj.query,
                ...localVarQueryParameter,
                ...options.query,
            };
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 运行任务
         * @summary /run-instance/{dagId}
         * @param {string} dagId 任务ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runInstanceDagIdPost: async (
            dagId: string,
            options: any = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'dagId' is not null or undefined
            if (dagId === null || dagId === undefined) {
                throw new RequiredError(
                    "dagId",
                    "Required parameter dagId was null or undefined when calling runInstanceDagIdPost."
                );
            }
            const localVarPath = `/run-instance/{dagId}`.replace(
                `{${"dagId"}}`,
                encodeURIComponent(String(dagId))
            );
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = {
                method: "POST",
                ...baseOptions,
                ...options,
            };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = {
                ...localVarUrlObj.query,
                ...localVarQueryParameter,
                ...options.query,
            };
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 取消运行任务
         * @summary /run-instance/{instanceId}
         * @param {string} instanceId 任务ID
         * @param {InlineObject} [inlineObject]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runInstanceInstanceIdPut: async (
            instanceId: string,
            inlineObject?: InlineObject,
            options: any = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'instanceId' is not null or undefined
            if (instanceId === null || instanceId === undefined) {
                throw new RequiredError(
                    "instanceId",
                    "Required parameter instanceId was null or undefined when calling runInstanceInstanceIdPut."
                );
            }
            const localVarPath = `/run-instance/{instanceId}`.replace(
                `{${"instanceId"}}`,
                encodeURIComponent(String(instanceId))
            );
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = {
                method: "PUT",
                ...baseOptions,
                ...options,
            };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter["Content-Type"] = "application/json";

            localVarUrlObj.query = {
                ...localVarUrlObj.query,
                ...localVarQueryParameter,
                ...options.query,
            };
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };
            const needsSerialization =
                typeof inlineObject !== "string" ||
                localVarRequestOptions.headers["Content-Type"] ===
                "application/json";
            localVarRequestOptions.data = needsSerialization
                ? JSON.stringify(inlineObject !== undefined ? inlineObject : {})
                : inlineObject || "";

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },

        /**
        * 创建告警
        * @summary /alert
        * @param {CreateAlertParams} params 创建告警参数
        * @param {*} [options] Override http request option.
        * @throws {RequiredError}
        */
        createAlert: async (
            params: CreateAlertParams,
            options: any = {}
        ): Promise<RequestArgs> => {
            const localVarPath = `/alarm-rule`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = {
                method: "POST",
                ...baseOptions,
                ...options,
            };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter["Content-Type"] = "application/json";

            localVarUrlObj.query = {
                ...localVarUrlObj.query,
                ...localVarQueryParameter,
                ...options.query,
            };
            delete localVarUrlObj.search;
            let headersFromBaseOptions =
                baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers,
            };
            localVarRequestOptions.data = params;

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },

        /**
        * 更新告警规则
        * @summary /alarm-rules/{id}
        * @param {string} id 规则ID
        * @param {CreateAlertParams} params 更新参数
        * @param {*} [options] Override http request option.
        * @throws {RequiredError}
        */
        updateAlert: async (
            id: string,
            params: CreateAlertParams,
            options: any = {}
        ): Promise<RequestArgs> => {
            if (id === null || id === undefined) {
                throw new RequiredError(
                    "id",
                    "Required parameter id was null or undefined when calling updateAlert."
                );
            }
            const localVarPath = `/alarm-rules/${encodeURIComponent(String(id))}`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = {
                method: "PUT",
                ...baseOptions,
                ...options,
            };
            const localVarHeaderParameter = {} as any;
            localVarHeaderParameter["Content-Type"] = "application/json";
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...baseOptions?.headers,
                ...options.headers,
            };
            localVarRequestOptions.data = params;

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 获取告警规则列表
         * @summary /alarm-rules
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAlerts: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/alarm-rules`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = {
                method: "GET",
                ...baseOptions,
                ...options,
            };
            const localVarHeaderParameter = {} as any;
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...baseOptions?.headers,
                ...options.headers,
            };

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        }
    };
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function (configuration?: Configuration) {
    return {
        /**
         * 删除任务
         * @summary /dag/{dagId}
         * @param {string} dagId 任务ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dagDagIdDelete(
            dagId: string,
            options?: any
        ): Promise<
            (axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>
        > {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
                configuration
            ).dagDagIdDelete(dagId, options);
            return (
                axios: AxiosInstance = globalAxios,
                basePath: string = BASE_PATH
            ) => {
                const axiosRequestArgs = {
                    ...localVarAxiosArgs.options,
                    url: basePath + localVarAxiosArgs.url,
                };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 获取任务详情
         * @summary /dag/{dagId}
         * @param {string} dagId 任务ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dagDagIdGet(
            dagId: string,
            options?: any
        ): Promise<
            (
                axios?: AxiosInstance,
                basePath?: string
            ) => AxiosPromise<DagDetail>
        > {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
                configuration
            ).dagDagIdGet(dagId, options);
            return (
                axios: AxiosInstance = globalAxios,
                basePath: string = BASE_PATH
            ) => {
                const axiosRequestArgs = {
                    ...localVarAxiosArgs.options,
                    url: basePath + localVarAxiosArgs.url,
                };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 更新任务
         * @summary /dag/{dagId}
         * @param {string} dagId 任务ID
         * @param {UpdateDag} [updateDag]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dagDagIdPut(
            dagId: string,
            updateDag?: UpdateDag,
            options?: any
        ): Promise<
            (axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>
        > {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
                configuration
            ).dagDagIdPut(dagId, updateDag, options);
            return (
                axios: AxiosInstance = globalAxios,
                basePath: string = BASE_PATH
            ) => {
                const axiosRequestArgs = {
                    ...localVarAxiosArgs.options,
                    url: basePath + localVarAxiosArgs.url,
                };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 任务运行详情
         * @summary /dag/{dagId}/result/{resultId}
         * @param {string} dagId 任务ID
         * @param {string} resultId 任务运行结果ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dagDagIdResultResultIdGet(
            dagId: string,
            resultId: string,
            options?: any
        ): Promise<
            (
                axios?: AxiosInstance,
                basePath?: string
            ) => AxiosPromise<Array<LogResult>>
        > {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
                configuration
            ).dagDagIdResultResultIdGet(dagId, resultId, options);
            return (
                axios: AxiosInstance = globalAxios,
                basePath: string = BASE_PATH
            ) => {
                const axiosRequestArgs = {
                    ...localVarAxiosArgs.options,
                    url: basePath + localVarAxiosArgs.url,
                };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 任务运行统计
         * @summary /dag/{dagId}/results
         * @param {string} dagId 任务ID
         * @param {string} [type] 节点运行状态  - success: 运行成功  - failed: 运行失败  - canceled: 运行取消  - running: 运行中  - scheduled:等待中
         * @param {number} [page] 页码，默认值为0
         * @param {string} [limit] 每页显示条目数，默认值为20，有效值在1-100之间，-1 取消分页
         * @param {string} [sortby] 排序字段，默认为started_at,仅支持started_at
         * @param {string} [order] 排序规则。默认为desc，仅支持desc和asc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dagDagIdResultsGet(
            dagId: string,
            type?: string,
            page?: number,
            limit?: string,
            sortby?: string,
            order?: string,
            options?: any
        ): Promise<
            (
                axios?: AxiosInstance,
                basePath?: string
            ) => AxiosPromise<TaskResult>
        > {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
                configuration
            ).dagDagIdResultsGet(
                dagId,
                type,
                page,
                limit,
                sortby,
                order,
                options
            );
            return (
                axios: AxiosInstance = globalAxios,
                basePath: string = BASE_PATH
            ) => {
                const axiosRequestArgs = {
                    ...localVarAxiosArgs.options,
                    url: basePath + localVarAxiosArgs.url,
                };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 创建任务
         * @summary /dag
         * @param {Dag} [dag]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dagPost(
            dag?: Dag,
            options?: any
        ): Promise<
            (
                axios?: AxiosInstance,
                basePath?: string
            ) => AxiosPromise<InlineResponse201>
        > {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
                configuration
            ).dagPost(dag, options);
            return (
                axios: AxiosInstance = globalAxios,
                basePath: string = BASE_PATH
            ) => {
                const axiosRequestArgs = {
                    ...localVarAxiosArgs.options,
                    url: basePath + localVarAxiosArgs.url,
                };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 获取创建任务的建议名称
         * @summary /dag/suggestname/{name}
         * @param {string} name 建议名称公共前缀,不能包含 / : * ? \&quot; &lt; &gt; | 特殊字符
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dagSuggestnameNameGet(
            name: string,
            options?: any
        ): Promise<
            (
                axios?: AxiosInstance,
                basePath?: string
            ) => AxiosPromise<SuggestName>
        > {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
                configuration
            ).dagSuggestnameNameGet(name, options);
            return (
                axios: AxiosInstance = globalAxios,
                basePath: string = BASE_PATH
            ) => {
                const axiosRequestArgs = {
                    ...localVarAxiosArgs.options,
                    url: basePath + localVarAxiosArgs.url,
                };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 列举任务
         * @summary /dags
         * @param {string} [keyword] 关键字，用于搜索筛选任务名称
         * @param {number} [page] 页码，默认值为0
         * @param {string} [limit] 每页显示条目数，默认值为20，有效值在1-100之间，-1 取消分页
         * @param {string} [sortby] 排序字段，默认为updated_at,仅支持name、created_at和updated_at
         * @param {string} [order] 排序规则。默认为desc，仅支持desc和asc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dagsGet(
            keyword?: string,
            page?: number,
            limit?: string,
            sortby?: string,
            order?: string,
            options?: any
        ): Promise<
            (axios?: AxiosInstance, basePath?: string) => AxiosPromise<DaGs>
        > {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
                configuration
            ).dagsGet(keyword, page, limit, sortby, order, options);
            return (
                axios: AxiosInstance = globalAxios,
                basePath: string = BASE_PATH
            ) => {
                const axiosRequestArgs = {
                    ...localVarAxiosArgs.options,
                    url: basePath + localVarAxiosArgs.url,
                };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 运行任务
         * @summary /run-instance/{dagId}
         * @param {string} dagId 任务ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runInstanceDagIdPost(
            dagId: string,
            options?: any
        ): Promise<
            (axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>
        > {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
                configuration
            ).runInstanceDagIdPost(dagId, options);
            return (
                axios: AxiosInstance = globalAxios,
                basePath: string = BASE_PATH
            ) => {
                const axiosRequestArgs = {
                    ...localVarAxiosArgs.options,
                    url: basePath + localVarAxiosArgs.url,
                };
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 取消运行任务
         * @summary /run-instance/{instanceId}
         * @param {string} instanceId 任务ID
         * @param {InlineObject} [inlineObject]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runInstanceInstanceIdPut(
            instanceId: string,
            inlineObject?: InlineObject,
            options?: any
        ): Promise<
            (axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>
        > {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
                configuration
            ).runInstanceInstanceIdPut(instanceId, inlineObject, options);
            return (
                axios: AxiosInstance = globalAxios,
                basePath: string = BASE_PATH
            ) => {
                const axiosRequestArgs = {
                    ...localVarAxiosArgs.options,
                    url: basePath + localVarAxiosArgs.url,
                };
                return axios.request(axiosRequestArgs);
            };
        },
        async createAlert(
            params: CreateAlertParams,
            options?: any
        ): Promise<
            (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
        > {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
                configuration
            ).createAlert(params, options);
            return (
                axios: AxiosInstance = globalAxios,
                basePath: string = BASE_PATH
            ) => {
                const axiosRequestArgs = {
                    ...localVarAxiosArgs.options,
                    url: basePath + localVarAxiosArgs.url,
                };
                return axios.request(axiosRequestArgs);
            };
        },
        async updateAlert(id: string, params: CreateAlertParams, options?: any): Promise<
            (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
        > {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
                configuration
            ).updateAlert(id, params, options);
            return (
                axios: AxiosInstance = globalAxios,
                basePath: string = BASE_PATH
            ) => {
                const axiosRequestArgs = {
                    ...localVarAxiosArgs.options,
                    url: basePath + localVarAxiosArgs.url,
                };
                return axios.request(axiosRequestArgs);
            };
        },
        async getAlerts(options?: any): Promise<
            (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
        > {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(
                configuration
            ).getAlerts(options);
            return (
                axios: AxiosInstance = globalAxios,
                basePath: string = BASE_PATH
            ) => {
                const axiosRequestArgs = {
                    ...localVarAxiosArgs.options,
                    url: basePath + localVarAxiosArgs.url,
                };
                return axios.request(axiosRequestArgs);
            };
        },
    };
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (
    configuration?: Configuration,
    basePath?: string,
    axios?: AxiosInstance
) {
    return {
        /**
         * 删除任务
         * @summary /dag/{dagId}
         * @param {string} dagId 任务ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagDagIdDelete(dagId: string, options?: any): AxiosPromise<object> {
            return DefaultApiFp(configuration)
                .dagDagIdDelete(dagId, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * 获取任务详情
         * @summary /dag/{dagId}
         * @param {string} dagId 任务ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagDagIdGet(dagId: string, options?: any): AxiosPromise<DagDetail> {
            return DefaultApiFp(configuration)
                .dagDagIdGet(dagId, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * 更新任务
         * @summary /dag/{dagId}
         * @param {string} dagId 任务ID
         * @param {UpdateDag} [updateDag]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagDagIdPut(
            dagId: string,
            updateDag?: UpdateDag,
            options?: any
        ): AxiosPromise<object> {
            return DefaultApiFp(configuration)
                .dagDagIdPut(dagId, updateDag, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * 任务运行详情
         * @summary /dag/{dagId}/result/{resultId}
         * @param {string} dagId 任务ID
         * @param {string} resultId 任务运行结果ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagDagIdResultResultIdGet(
            dagId: string,
            resultId: string,
            options?: any
        ): AxiosPromise<Array<LogResult>> {
            return DefaultApiFp(configuration)
                .dagDagIdResultResultIdGet(dagId, resultId, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * 任务运行统计
         * @summary /dag/{dagId}/results
         * @param {string} dagId 任务ID
         * @param {string} [type] 节点运行状态  - success: 运行成功  - failed: 运行失败  - canceled: 运行取消  - running: 运行中  - scheduled:等待中
         * @param {number} [page] 页码，默认值为0
         * @param {string} [limit] 每页显示条目数，默认值为20，有效值在1-100之间，-1 取消分页
         * @param {string} [sortby] 排序字段，默认为started_at,仅支持started_at
         * @param {string} [order] 排序规则。默认为desc，仅支持desc和asc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagDagIdResultsGet(
            dagId: string,
            type?: string,
            page?: number,
            limit?: string,
            sortby?: string,
            order?: string,
            options?: any
        ): AxiosPromise<TaskResult> {
            return DefaultApiFp(configuration)
                .dagDagIdResultsGet(
                    dagId,
                    type,
                    page,
                    limit,
                    sortby,
                    order,
                    options
                )
                .then((request) => request(axios, basePath));
        },
        /**
         * 创建任务
         * @summary /dag
         * @param {Dag} [dag]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagPost(dag?: Dag, options?: any): AxiosPromise<InlineResponse201> {
            return DefaultApiFp(configuration)
                .dagPost(dag, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * 获取创建任务的建议名称
         * @summary /dag/suggestname/{name}
         * @param {string} name 建议名称公共前缀,不能包含 / : * ? \&quot; &lt; &gt; | 特殊字符
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagSuggestnameNameGet(
            name: string,
            options?: any
        ): AxiosPromise<SuggestName> {
            return DefaultApiFp(configuration)
                .dagSuggestnameNameGet(name, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * 列举任务
         * @summary /dags
         * @param {string} [keyword] 关键字，用于搜索筛选任务名称
         * @param {number} [page] 页码，默认值为0
         * @param {string} [limit] 每页显示条目数，默认值为20，有效值在1-100之间，-1 取消分页
         * @param {string} [sortby] 排序字段，默认为updated_at,仅支持name、created_at和updated_at
         * @param {string} [order] 排序规则。默认为desc，仅支持desc和asc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dagsGet(
            keyword?: string,
            page?: number,
            limit?: string,
            sortby?: string,
            order?: string,
            options?: any
        ): AxiosPromise<DaGs> {
            return DefaultApiFp(configuration)
                .dagsGet(keyword, page, limit, sortby, order, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * 运行任务
         * @summary /run-instance/{dagId}
         * @param {string} dagId 任务ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runInstanceDagIdPost(
            dagId: string,
            options?: any
        ): AxiosPromise<object> {
            return DefaultApiFp(configuration)
                .runInstanceDagIdPost(dagId, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * 取消运行任务
         * @summary /run-instance/{instanceId}
         * @param {string} instanceId 任务ID
         * @param {InlineObject} [inlineObject]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runInstanceInstanceIdPut(
            instanceId: string,
            inlineObject?: InlineObject,
            options?: any
        ): AxiosPromise<object> {
            return DefaultApiFp(configuration)
                .runInstanceInstanceIdPut(instanceId, inlineObject, options)
                .then((request) => request(axios, basePath));
        },
        /**
         * 创建告警
         * @summary /alert
         * @param {CreateAlertParams} params 创建告警参数
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAlert(params: CreateAlertParams, options?: any): AxiosPromise<any> {
            return DefaultApiFp(configuration)
                .createAlert(params, options)
                .then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 删除任务
     * @summary /dag/{dagId}
     * @param {string} dagId 任务ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public dagDagIdDelete(dagId: string, options?: any) {
        return DefaultApiFp(this.configuration)
            .dagDagIdDelete(dagId, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * 获取任务详情
     * @summary /dag/{dagId}
     * @param {string} dagId 任务ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public dagDagIdGet(dagId: string, options?: any) {
        return DefaultApiFp(this.configuration)
            .dagDagIdGet(dagId, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * 更新任务
     * @summary /dag/{dagId}
     * @param {string} dagId 任务ID
     * @param {UpdateDag} [updateDag]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public dagDagIdPut(dagId: string, updateDag?: UpdateDag, options?: any) {
        return DefaultApiFp(this.configuration)
            .dagDagIdPut(dagId, updateDag, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * 任务运行详情
     * @summary /dag/{dagId}/result/{resultId}
     * @param {string} dagId 任务ID
     * @param {string} resultId 任务运行结果ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public dagDagIdResultResultIdGet(
        dagId: string,
        resultId: string,
        options?: any
    ) {
        return DefaultApiFp(this.configuration)
            .dagDagIdResultResultIdGet(dagId, resultId, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * 任务运行统计
     * @summary /dag/{dagId}/results
     * @param {string} dagId 任务ID
     * @param {string} [type] 节点运行状态  - success: 运行成功  - failed: 运行失败  - canceled: 运行取消  - running: 运行中  - scheduled:等待中
     * @param {number} [page] 页码，默认值为0
     * @param {string} [limit] 每页显示条目数，默认值为20，有效值在1-100之间，-1 取消分页
     * @param {string} [sortby] 排序字段，默认为started_at,仅支持started_at
     * @param {string} [order] 排序规则。默认为desc，仅支持desc和asc
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public dagDagIdResultsGet(
        dagId: string,
        type?: string,
        page?: number,
        limit?: string,
        sortby?: string,
        order?: string,
        options?: any
    ) {
        return DefaultApiFp(this.configuration)
            .dagDagIdResultsGet(
                dagId,
                type,
                page,
                limit,
                sortby,
                order,
                options
            )
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * 创建任务
     * @summary /dag
     * @param {Dag} [dag]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public dagPost(dag?: Dag, options?: any) {
        return DefaultApiFp(this.configuration)
            .dagPost(dag, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * 获取创建任务的建议名称
     * @summary /dag/suggestname/{name}
     * @param {string} name 建议名称公共前缀,不能包含 / : * ? \&quot; &lt; &gt; | 特殊字符
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public dagSuggestnameNameGet(name: string, options?: any) {
        return DefaultApiFp(this.configuration)
            .dagSuggestnameNameGet(name, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * 列举任务
     * @summary /dags
     * @param {string} [keyword] 关键字，用于搜索筛选任务名称
     * @param {number} [page] 页码，默认值为0
     * @param {string} [limit] 每页显示条目数，默认值为20，有效值在1-100之间，-1 取消分页
     * @param {string} [sortby] 排序字段，默认为updated_at,仅支持name、created_at和updated_at
     * @param {string} [order] 排序规则。默认为desc，仅支持desc和asc
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public dagsGet(
        keyword?: string,
        page?: number,
        limit?: string,
        sortby?: string,
        order?: string,
        options?: any
    ) {
        return DefaultApiFp(this.configuration)
            .dagsGet(keyword, page, limit, sortby, order, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * 运行任务
     * @summary /run-instance/{dagId}
     * @param {string} dagId 任务ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public runInstanceDagIdPost(dagId: string, options?: any) {
        return DefaultApiFp(this.configuration)
            .runInstanceDagIdPost(dagId, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * 取消运行任务
     * @summary /run-instance/{instanceId}
     * @param {string} instanceId 任务ID
     * @param {InlineObject} [inlineObject]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public runInstanceInstanceIdPut(
        instanceId: string,
        inlineObject?: InlineObject,
        options?: any
    ) {
        return DefaultApiFp(this.configuration)
            .runInstanceInstanceIdPut(instanceId, inlineObject, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * 创建告警
     * @summary /alert
     * @param {CreateAlertParams} params 创建告警参数
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createAlert(params: CreateAlertParams, options?: any) {
        return DefaultApiFp(this.configuration)
            .createAlert(params, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * 更新告警规则
     * @summary /alarm-rules/{id}
     * @param {string} id 规则ID
     * @param {CreateAlertParams} params 更新参数
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateAlert(id: string, params: CreateAlertParams, options?: any) {
        return DefaultApiFp(this.configuration)
            .updateAlert(id, params, options)
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * 获取告警规则列表
     * @summary /alarm-rules
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getAlerts(options?: any) {
        return DefaultApiFp(this.configuration)
            .getAlerts(options)
            .then((request) => request(this.axios, this.basePath));
    }
}
