// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/business_system_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBusinessSystemAccess is a mock of BusinessSystemAccess interface.
type MockBusinessSystemAccess struct {
	ctrl     *gomock.Controller
	recorder *MockBusinessSystemAccessMockRecorder
}

// MockBusinessSystemAccessMockRecorder is the mock recorder for MockBusinessSystemAccess.
type MockBusinessSystemAccessMockRecorder struct {
	mock *MockBusinessSystemAccess
}

// NewMockBusinessSystemAccess creates a new mock instance.
func NewMockBusinessSystemAccess(ctrl *gomock.Controller) *MockBusinessSystemAccess {
	mock := &MockBusinessSystemAccess{ctrl: ctrl}
	mock.recorder = &MockBusinessSystemAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBusinessSystemAccess) EXPECT() *MockBusinessSystemAccessMockRecorder {
	return m.recorder
}

// BindResource mocks base method.
func (m *MockBusinessSystemAccess) BindResource(ctx context.Context, bd_id, rid, rtype string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindResource", ctx, bd_id, rid, rtype)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindResource indicates an expected call of BindResource.
func (mr *MockBusinessSystemAccessMockRecorder) BindResource(ctx, bd_id, rid, rtype interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindResource", reflect.TypeOf((*MockBusinessSystemAccess)(nil).BindResource), ctx, bd_id, rid, rtype)
}

// UnbindResource mocks base method.
func (m *MockBusinessSystemAccess) UnbindResource(ctx context.Context, bd_id, rid, rtype string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnbindResource", ctx, bd_id, rid, rtype)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnbindResource indicates an expected call of UnbindResource.
func (mr *MockBusinessSystemAccessMockRecorder) UnbindResource(ctx, bd_id, rid, rtype interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnbindResource", reflect.TypeOf((*MockBusinessSystemAccess)(nil).UnbindResource), ctx, bd_id, rid, rtype)
}
