// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/user_mgmt_access.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserMgmtAccess is a mock of UserMgmtAccess interface.
type MockUserMgmtAccess struct {
	ctrl     *gomock.Controller
	recorder *MockUserMgmtAccessMockRecorder
}

// MockUserMgmtAccessMockRecorder is the mock recorder for MockUserMgmtAccess.
type MockUserMgmtAccessMockRecorder struct {
	mock *MockUserMgmtAccess
}

// NewMockUserMgmtAccess creates a new mock instance.
func NewMockUserMgmtAccess(ctrl *gomock.Controller) *MockUserMgmtAccess {
	mock := &MockUserMgmtAccess{ctrl: ctrl}
	mock.recorder = &MockUserMgmtAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserMgmtAccess) EXPECT() *MockUserMgmtAccessMockRecorder {
	return m.recorder
}

// GetAccountNames mocks base method.
func (m *MockUserMgmtAccess) GetAccountNames(ctx context.Context, accountInfos []*interfaces.AccountInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountNames", ctx, accountInfos)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAccountNames indicates an expected call of GetAccountNames.
func (mr *MockUserMgmtAccessMockRecorder) GetAccountNames(ctx, accountInfos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountNames", reflect.TypeOf((*MockUserMgmtAccess)(nil).GetAccountNames), ctx, accountInfos)
}
