// Copyright The kweaver.ai Authors.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for details.

// Code generated by MockGen. DO NOT EDIT.
// Source: ../interfaces/job_service.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	sql "database/sql"
	interfaces "ontology-manager/interfaces"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockJobService is a mock of JobService interface.
type MockJobService struct {
	ctrl     *gomock.Controller
	recorder *MockJobServiceMockRecorder
}

// MockJobServiceMockRecorder is the mock recorder for MockJobService.
type MockJobServiceMockRecorder struct {
	mock *MockJobService
}

// NewMockJobService creates a new mock instance.
func NewMockJobService(ctrl *gomock.Controller) *MockJobService {
	mock := &MockJobService{ctrl: ctrl}
	mock.recorder = &MockJobServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobService) EXPECT() *MockJobServiceMockRecorder {
	return m.recorder
}

// CreateJob mocks base method.
func (m *MockJobService) CreateJob(ctx context.Context, jobInfo *interfaces.JobInfo) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", ctx, jobInfo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockJobServiceMockRecorder) CreateJob(ctx, jobInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockJobService)(nil).CreateJob), ctx, jobInfo)
}

// DeleteJobsByIDs mocks base method.
func (m *MockJobService) DeleteJobsByIDs(ctx context.Context, knID, branch string, jobIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJobsByIDs", ctx, knID, branch, jobIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJobsByIDs indicates an expected call of DeleteJobsByIDs.
func (mr *MockJobServiceMockRecorder) DeleteJobsByIDs(ctx, knID, branch, jobIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJobsByIDs", reflect.TypeOf((*MockJobService)(nil).DeleteJobsByIDs), ctx, knID, branch, jobIDs)
}

// DeleteJobsByKnID mocks base method.
func (m *MockJobService) DeleteJobsByKnID(ctx context.Context, tx *sql.Tx, knID, branch string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJobsByKnID", ctx, tx, knID, branch)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJobsByKnID indicates an expected call of DeleteJobsByKnID.
func (mr *MockJobServiceMockRecorder) DeleteJobsByKnID(ctx, tx, knID, branch interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJobsByKnID", reflect.TypeOf((*MockJobService)(nil).DeleteJobsByKnID), ctx, tx, knID, branch)
}

// GetJobByID mocks base method.
func (m *MockJobService) GetJobByID(ctx context.Context, jobID string) (*interfaces.JobInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobByID", ctx, jobID)
	ret0, _ := ret[0].(*interfaces.JobInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobByID indicates an expected call of GetJobByID.
func (mr *MockJobServiceMockRecorder) GetJobByID(ctx, jobID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobByID", reflect.TypeOf((*MockJobService)(nil).GetJobByID), ctx, jobID)
}

// GetJobsByIDs mocks base method.
func (m *MockJobService) GetJobsByIDs(ctx context.Context, jobIDs []string) (map[string]*interfaces.JobInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobsByIDs", ctx, jobIDs)
	ret0, _ := ret[0].(map[string]*interfaces.JobInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobsByIDs indicates an expected call of GetJobsByIDs.
func (mr *MockJobServiceMockRecorder) GetJobsByIDs(ctx, jobIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobsByIDs", reflect.TypeOf((*MockJobService)(nil).GetJobsByIDs), ctx, jobIDs)
}

// ListJobs mocks base method.
func (m *MockJobService) ListJobs(ctx context.Context, queryParams interfaces.JobsQueryParams) ([]*interfaces.JobInfo, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobs", ctx, queryParams)
	ret0, _ := ret[0].([]*interfaces.JobInfo)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListJobs indicates an expected call of ListJobs.
func (mr *MockJobServiceMockRecorder) ListJobs(ctx, queryParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobs", reflect.TypeOf((*MockJobService)(nil).ListJobs), ctx, queryParams)
}

// ListTasks mocks base method.
func (m *MockJobService) ListTasks(ctx context.Context, queryParams interfaces.TasksQueryParams) ([]*interfaces.TaskInfo, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", ctx, queryParams)
	ret0, _ := ret[0].([]*interfaces.TaskInfo)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockJobServiceMockRecorder) ListTasks(ctx, queryParams interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockJobService)(nil).ListTasks), ctx, queryParams)
}
